'use client';
import {lazy,Suspense,useState} from 'react';
const BiochemistryWorkbench=lazy(()=>import('./biochemistry-workbench'));
const OmicsWorkbench=lazy(()=>import('./omics-workbench'));
import SpanishBookshelf from './spanish-bookshelf';
import {academicBooks} from '@/lib/academic-books';
import {ancestry,descendants,safeUrl,type Item} from '@/lib/content';
export function isGraduate(item:Item,all:Item[]){return [...ancestry(item,all),item].some(i=>['sub-metabolomica','sub-volatilomica'].includes(i.id));}
export function Bookshelf({item,all}:{item:Item;all:Item[]}){
 const paths=[...ancestry(item,all),item].map(i=>i.id);const books=academicBooks.filter(b=>b.branches.some(id=>paths.includes(id)));
 if(!books.length)return <SpanishBookshelf item={item} all={all}/>;
 return <><SpanishBookshelf item={item} all={all}/><section className="bookshelf"><h2>Referencias especializadas adicionales</h2>{books.map(b=>{const resource=all.find(i=>i.id==='libro-'+b.id);if(!resource)return null;return <article key={b.id}><span className="eyebrow">LIBRO DE REFERENCIA</span><h3>{resource.title}</h3><p>{resource.description}</p><p>{b.scope}</p><a className="text-link" href={safeUrl(resource.url)} target="_blank" rel="noreferrer">Consultar libro en el sitio original ↗</a></article>})}<p className="muted">Las descargas gratuitas están disponibles únicamente cuando las ofrece el autor o la editorial. Los textos comerciales requieren compra o acceso de biblioteca.</p></section></>;
}
export function SeparationLab(){const [distance,setDistance]=useState(1.8),[width,setWidth]=useState(.45);const resolution=distance/(4*width);const points=Array.from({length:241},(_,i)=>{const x=i/24;const signal=Math.exp(-.5*((x-4)/width)**2)+.8*Math.exp(-.5*((x-4-distance)/width)**2);return `${30+x*46},${180-signal*105}`}).join(' ');return <section className="separation-lab"><div><span className="eyebrow">LABORATORIO CONCEPTUAL</span><h2>¿Puedes separar estas dos señales?</h2><p>Explora cómo la distancia entre picos y su anchura modifican la resolución.</p></div><svg viewBox="0 0 510 215" role="img" aria-label={'Cromatograma simulado. Resolución '+resolution.toFixed(2)}><path d="M30 20V180H495" fill="none" stroke="currentColor"/><polyline points={points} fill="none" stroke="#087466" strokeWidth="3"/><text x="195" y="208">Tiempo de retención (min)</text><text x="36" y="20">Señal relativa</text>{[0,2,4,6,8,10].map(n=><text key={n} x={25+n*46} y="196">{n}</text>)}</svg><div className="lab-controls"><label>Distancia entre picos: {distance.toFixed(1)} min<input type="range" min="0.4" max="4" step="0.1" value={distance} onChange={e=>setDistance(Number(e.target.value))}/></label><label>Desviación estándar σ: {width.toFixed(2)} min<input type="range" min="0.15" max="0.9" step="0.05" value={width} onChange={e=>setWidth(Number(e.target.value))}/></label><output aria-live="polite">Rₛ = {resolution.toFixed(2)} · {resolution>=1.5?'Separación aproximadamente a línea base':'Solapamiento de señales'}</output></div><p className="muted">Modelo didáctico: dos gaussianas con igual σ; anchura de base aproximada w = 4σ y Rₛ = 2Δt/(w₁ + w₂). No representa datos experimentales ni predice el rendimiento de un instrumento.</p></section>}
export function GraduateShell({root,item,all,children}:{root:Item;item:Item;all:Item[];children:React.ReactNode}){const course=all.find(i=>i.kind==='course'&&i.parent===root.id);const scoped=descendants(root.id,all);const units=scoped.filter(i=>i.kind==='unit');const [view,setView]=useState('programa');return <div className={'graduate-environment '+(root.id==='sub-volatilomica'?'volatile':'metabolic')}><a className="skip" href="#contenido-posgrado">Saltar al contenido</a><header className="graduate-header"><a href="#inicio">← AulaQuímica</a><span>POSGRADO · AULA DE INVESTIGACIÓN</span><a href="/acceso">Mi cuenta</a></header><div className="graduate-hero"><span className="eyebrow">SEMINARIO Y PROYECTO</span><h1>{root.title}</h1><p>{course?.description||root.description}</p><div className="graduate-stats"><span>{units.length} unidades</span><span>{scoped.filter(i=>i.kind==='topic').length} temas propuestos</span><span>Plan editable · 2 semestres</span></div></div><div className="graduate-layout"><aside><nav aria-label={'Navegación de '+root.title}>{[['programa','Plan y unidades'],['procesamiento','Programas y procesamiento'],['bioquimica','Bioquímica y biomarcadores'],['biblioteca','Biblioteca'],['laboratorio','Laboratorio conceptual']].map(([id,label])=><button type="button" key={id} onClick={()=>setView(id)} aria-current={view===id?'page':undefined}>{label}</button>)}</nav><h2>Unidades</h2>{units.map((u,n)=><a key={u.id} href={'#'+u.id} onClick={()=>setView('programa')}>{String(n+1).padStart(2,'0')} · {u.title}</a>)}</aside><main id="contenido-posgrado" tabIndex={-1}>{view==='bioquimica'?<Suspense fallback={<p>Cargando bioquímica…</p>}><BiochemistryWorkbench volatile={root.id==='sub-volatilomica'}/></Suspense>:view==='procesamiento'?<Suspense fallback={<p>Cargando guías…</p>}><OmicsWorkbench volatile={root.id==='sub-volatilomica'}/></Suspense>:view==='biblioteca'?<Bookshelf item={root} all={all}/>:view==='laboratorio'?<SeparationLab/>:<><nav className="breadcrumbs" aria-label="Ubicación"><a href={'#'+root.id} onClick={()=>setView('programa')}>{root.title}</a>{ancestry(item,all).filter(i=>i.id!==root.id).map(i=><a href={'#'+i.id} key={i.id}> / {i.title}</a>)}</nav>{children}</>}</main></div><footer className="graduate-footer">Propuesta académica editable. Los materiales de clase se incorporan progresivamente.</footer></div>}
