'use client';
import {useEffect,useRef,useState} from 'react';
import {molecules} from '@/lib/molecule-models';
import {biology,BiologyDrawing} from './biology-models';
export default function AugmentedClassroom(){
 const video=useRef<HTMLVideoElement>(null),stream=useRef<MediaStream|null>(null),request=useRef(0);
 const [selected,setSelected]=useState(0),[active,setActive]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('Vista de práctica: puedes explorar los modelos sin activar la cámara.'),[model,setModel]=useState('water'),[angle,setAngle]=useState(20),[scale,setScale]=useState(1),[x,setX]=useState(0),[y,setY]=useState(0),[facing,setFacing]=useState('environment');
 function stop(){request.current++;stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;if(video.current)video.current.srcObject=null;setActive(false);setBusy(false)}
 useEffect(()=>{const hide=()=>{if(document.hidden){stop();setMessage('Cámara apagada al salir de esta pestaña. Puedes activarla nuevamente.')}};document.addEventListener('visibilitychange',hide);return()=>{request.current++;stream.current?.getTracks().forEach(t=>t.stop());document.removeEventListener('visibilitychange',hide)}},[]);
 async function start(){stop();const ticket=++request.current;setBusy(true);setMessage('Solicitando permiso de cámara…');try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('La cámara necesita HTTPS y un navegador compatible. Puedes usar la vista de práctica.');const media=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:{ideal:facing},width:{ideal:1280},height:{ideal:720}}});if(ticket!==request.current){media.getTracks().forEach(t=>t.stop());return}stream.current=media;if(video.current){video.current.srcObject=media;await video.current.play()}if(ticket!==request.current)return;setActive(true);setMessage('Cámara activa. No se graba ni se envían imágenes.')}catch(error){if(ticket!==request.current)return;stop();const name=error instanceof Error?error.name:'';setMessage(name==='NotAllowedError'?'Permiso denegado. Habilita la cámara para este sitio en tu navegador y vuelve a intentarlo.':name==='NotFoundError'?'No se encontró una cámara. Puedes continuar con la vista de práctica.':error instanceof Error?error.message:'No se pudo activar la cámara.')}finally{if(ticket===request.current)setBusy(false)}}
 const molecule=molecules[model],a=angle*Math.PI/180;
 const points=molecule?.atoms.map(([element,px,py,pz])=>({element,x:(px*Math.cos(a)+pz*Math.sin(a))*85,y:py*85,z:pz*Math.cos(a)-px*Math.sin(a)}));
 return <section className="immersive-room"><span className="eyebrow">EXPLORA · OBSERVA · COMPARA</span><h2>Realidad aumentada: aula visual</h2><p>Superpone un modelo sobre la cámara y ajústalo con los controles. Esta vista no reconoce imágenes ni fija objetos al mundo real. Los esquemas no están a escala.</p><div className="visual-workspace"><div><div className="camera-stage"><video ref={video} muted playsInline aria-label="Vista local de tu cámara"/>{!active&&<span className="camera-placeholder">Vista de práctica · Cámara apagada</span>}<svg viewBox="0 0 600 400" role="img" aria-label={molecule?.name||biology[model]?.name}><g transform={`translate(${300+x} ${200+y}) scale(${scale})`}>
 {points?<>{molecule.bonds.map(([from,to,order],n)=>{const p=points[from],q=points[to],length=Math.hypot(q.x-p.x,q.y-p.y)||1;return <g key={n}>{Array.from({length:order},(_,i)=>{const d=(i-(order-1)/2)*7,dx=-(q.y-p.y)/length*d,dy=(q.x-p.x)/length*d;return <line key={i} x1={p.x+dx} y1={p.y+dy} x2={q.x+dx} y2={q.y+dy} stroke="#d0e3ed" strokeWidth="4"/>})}</g>})}{points.map((p,i)=>({...p,i})).sort((p,q)=>p.z-q.z).map(p=><g key={p.i} transform={`translate(${p.x} ${p.y})`}><circle r={p.element==='H'?15:22} fill={p.element==='O'?'#d73d48':p.element==='N'?'#2378d8':p.element==='Cl'?'#29844b':p.element==='C'?'#354957':'#fff'} stroke="#b5d4df" strokeWidth="2"/><circle cx="-6" cy="-7" r="6" fill="white" opacity=".22"/><text textAnchor="middle" dy="5" fill={p.element==='H'?'#143e52':'white'} fontWeight="bold" fontSize="14">{p.element}</text></g>)}</>:<g transform={`rotate(${angle})`}><BiologyDrawing model={model} selected={selected} onSelect={setSelected}/></g>}

 </g></svg></div><p role="status">{message}</p><div className="visual-actions"><button className="button" onClick={start} disabled={busy||active}>{busy?'Esperando permiso…':'Activar cámara'}</button><button className="button secondary" onClick={()=>{stop();setMessage('Cámara apagada.')}} disabled={!busy&&!active}>Apagar cámara</button></div></div><div className="visual-controls"><label>Modelo<select value={model} onChange={e=>{setModel(e.target.value);setSelected(0);setAngle(0)}}><optgroup label="Moléculas">{Object.entries(molecules).map(([id,m])=><option key={id} value={id}>{m.name}</option>)}</optgroup>{['Células','Virus','Organismos','Plantas'].map(group=><optgroup key={group} label={group}>{Object.entries(biology).filter(([,m])=>m.group===group).map(([id,m])=><option key={id} value={id}>{m.name}</option>)}</optgroup>)}</select></label><label>Cámara<select value={facing} disabled={active||busy} onChange={e=>setFacing(e.target.value)}><option value="environment">Trasera / entorno</option><option value="user">Frontal</option></select></label>{[['Giro',angle,setAngle,0,360],['Tamaño',scale,setScale,.5,1.4],['Posición horizontal',x,setX,-100,100],['Posición vertical',y,setY,-60,60]].map(([label,value,set,min,max])=><label key={String(label)}>{String(label)}<input type="range" aria-label={String(label)} min={Number(min)} max={Number(max)} step={label==='Tamaño'?.05:1} value={Number(value)} onChange={e=>(set as (n:number)=>void)(Number(e.target.value))}/></label>)}<button className="button secondary" onClick={()=>{setAngle(20);setScale(1);setX(0);setY(0)}}>Centrar modelo</button><p>{molecule?.note||biology[model]?.note}</p>{!molecule&&<div className="organelle-panel"><label>Estructura para estudiar<select value={selected} onChange={e=>setSelected(Number(e.target.value))}>{biology[model].parts.map((p,i)=><option key={p} value={i}>{i+1}. {p.split('|')[0]}</option>)}</select></label><p aria-live="polite"><strong>{selected+1}. {biology[model].parts[selected]?.split('|')[0]}</strong><br/>{biology[model].parts[selected]?.split('|')[1]}</p><small>Pulsa un número del modelo o elige una estructura. Esquemas didácticos, no reconstrucciones microscópicas.</small></div>}<small>La cámara funciona solo mientras permaneces en esta aula y pestaña. No requiere micrófono.</small></div></div></section>
}
