'use client';
import {useEffect,useRef,useState} from 'react';
const molecules:Record<string,{name:string;note:string;atoms:[string,number,number,number][]}>={
 water:{name:'Agua · H₂O',note:'Geometría angular, aproximadamente 104,5°. Rojo: oxígeno; blanco: hidrógeno.',atoms:[['O',0,0,0],['H',-.79,.61,0],['H',.79,.61,0]]},
 carbon:{name:'Dióxido de carbono · CO₂',note:'Geometría lineal, 180°. Las dos líneas representan enlaces dobles.',atoms:[['C',0,0,0],['O',-1.2,0,0],['O',1.2,0,0]]},
 methane:{name:'Metano · CH₄',note:'Geometría tetraédrica, aproximadamente 109,5°. Gira el modelo para explorar la profundidad.',atoms:[['C',0,0,0],['H',.7,.7,.7],['H',-.7,-.7,.7],['H',-.7,.7,-.7],['H',.7,-.7,-.7]]},
 ammonia:{name:'Amoniaco · NH₃',note:'Geometría piramidal trigonal. Azul: nitrógeno. El par libre no está representado.',atoms:[['N',0,-.3,0],['H',0,.55,1],['H',-.86,.55,-.5],['H',.86,.55,-.5]]}
};
export default function AugmentedClassroom(){
 const video=useRef<HTMLVideoElement>(null),stream=useRef<MediaStream|null>(null),request=useRef(0);
 const [active,setActive]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('Vista de práctica: puedes explorar los modelos sin activar la cámara.'),[model,setModel]=useState('water'),[angle,setAngle]=useState(20),[scale,setScale]=useState(1),[x,setX]=useState(0),[y,setY]=useState(0),[facing,setFacing]=useState('environment');
 function stop(){request.current++;stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;if(video.current)video.current.srcObject=null;setActive(false);setBusy(false)}
 useEffect(()=>{const hide=()=>{if(document.hidden){stop();setMessage('Cámara apagada al salir de esta pestaña. Puedes activarla nuevamente.')}};document.addEventListener('visibilitychange',hide);return()=>{request.current++;stream.current?.getTracks().forEach(t=>t.stop());document.removeEventListener('visibilitychange',hide)}},[]);
 async function start(){stop();const ticket=++request.current;setBusy(true);setMessage('Solicitando permiso de cámara…');try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('La cámara necesita HTTPS y un navegador compatible. Puedes usar la vista de práctica.');const media=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:{ideal:facing},width:{ideal:1280},height:{ideal:720}}});if(ticket!==request.current){media.getTracks().forEach(t=>t.stop());return}stream.current=media;if(video.current){video.current.srcObject=media;await video.current.play()}if(ticket!==request.current)return;setActive(true);setMessage('Cámara activa. No se graba ni se envían imágenes.')}catch(error){if(ticket!==request.current)return;stop();const name=error instanceof Error?error.name:'';setMessage(name==='NotAllowedError'?'Permiso denegado. Habilita la cámara para este sitio en tu navegador y vuelve a intentarlo.':name==='NotFoundError'?'No se encontró una cámara. Puedes continuar con la vista de práctica.':error instanceof Error?error.message:'No se pudo activar la cámara.')}finally{if(ticket===request.current)setBusy(false)}}
 const molecule=molecules[model],a=angle*Math.PI/180;
 const points=molecule?.atoms.map(([element,px,py,pz])=>({element,x:(px*Math.cos(a)+pz*Math.sin(a))*85,y:py*85,z:pz*Math.cos(a)-px*Math.sin(a)}));
 return <section className="immersive-room"><span className="eyebrow">EXPLORA · OBSERVA · COMPARA</span><h2>Realidad aumentada: aula visual</h2><p>Superpone un modelo sobre la cámara y ajústalo con los controles. Esta vista no reconoce imágenes ni fija objetos al mundo real. Los esquemas no están a escala.</p><div className="visual-workspace"><div><div className="camera-stage"><video ref={video} muted playsInline aria-label="Vista local de tu cámara"/>{!active&&<span className="camera-placeholder">Vista de práctica · Cámara apagada</span>}<svg viewBox="0 0 600 400" role="img" aria-label={molecule?.name||('Esquema de '+(model==='plant'?'célula vegetal':'célula animal'))}><g transform={`translate(${300+x} ${200+y}) scale(${scale})`}>
 {points?<>{points.slice(1).map((p,n)=><g key={'bond'+n}>{(model==='carbon'?[-4,4]:[0]).map(offset=><line key={offset} x1={points[0].x} y1={points[0].y+offset} x2={p.x} y2={p.y+offset} stroke="#c2dce8" strokeWidth="7"/>)}</g>)}{points.map((p,i)=>({...p,i})).sort((p,q)=>p.z-q.z).map(p=><g key={p.i} transform={`translate(${p.x} ${p.y})`}><circle r={p.element==='H'?20:29} fill={p.element==='O'?'#d73d48':p.element==='N'?'#2378d8':p.element==='C'?'#354957':'#fff'} stroke="#b5d4df" strokeWidth="2"/><text textAnchor="middle" dy="6" fill={p.element==='H'?'#143e52':'white'} fontWeight="bold" fontSize="18">{p.element}</text></g>)}</>:<g transform={`rotate(${angle})`}>{model==='plant'?<rect x="-160" y="-125" width="320" height="250" rx="35" fill="#badc93" stroke="#326d36" strokeWidth="12"/>:<ellipse rx="160" ry="122" fill="#bee6f0" stroke="#358da0" strokeWidth="6"/>}<ellipse cx="38" cy="-5" rx={model==='plant'?78:55} ry={model==='plant'?80:48} fill={model==='plant'?'#a6e0ee':'#8b83bb'} stroke="#47547e" strokeWidth="3"/>{model==='plant'&&<circle cx="-85" cy="25" r="30" fill="#8b83bb"/>}<text x={model==='plant'?-85:38} y={model==='plant'?30:0} textAnchor="middle" fontSize="13" fill="#172e49">Núcleo</text>{model==='plant'&&<text x="38" y="0" textAnchor="middle" fontSize="13">Vacuola</text>}{[-1,1].map(n=><g key={n}><ellipse cx={n*108} cy="-65" rx="25" ry="12" fill={model==='plant'?'#34894e':'#df9262'} stroke="#356456" strokeWidth="2"/><path d={`M ${n*108-15} -65 l 10 -5 l 10 10 l 10 -5`} stroke="white" fill="none"/></g>)}<text y="95" textAnchor="middle" fontSize="14">Citoplasma</text></g>}
 </g></svg></div><p role="status">{message}</p><div className="visual-actions"><button className="button" onClick={start} disabled={busy||active}>{busy?'Esperando permiso…':'Activar cámara'}</button><button className="button secondary" onClick={()=>{stop();setMessage('Cámara apagada.')}} disabled={!busy&&!active}>Apagar cámara</button></div></div><div className="visual-controls"><label>Modelo<select value={model} onChange={e=>setModel(e.target.value)}>{Object.entries(molecules).map(([id,m])=><option key={id} value={id}>{m.name}</option>)}<option value="animal">Célula animal</option><option value="plant">Célula vegetal</option></select></label><label>Cámara<select value={facing} disabled={active||busy} onChange={e=>setFacing(e.target.value)}><option value="environment">Trasera / entorno</option><option value="user">Frontal</option></select></label>{[['Giro',angle,setAngle,0,360],['Tamaño',scale,setScale,.5,1.4],['Posición horizontal',x,setX,-100,100],['Posición vertical',y,setY,-60,60]].map(([label,value,set,min,max])=><label key={String(label)}>{String(label)}<input type="range" aria-label={String(label)} min={Number(min)} max={Number(max)} step={label==='Tamaño'?.05:1} value={Number(value)} onChange={e=>(set as (n:number)=>void)(Number(e.target.value))}/></label>)}<button className="button secondary" onClick={()=>{setAngle(20);setScale(1);setX(0);setY(0)}}>Centrar modelo</button><p>{molecule?.note||(model==='plant'?'Modelo simplificado: pared celular, citoplasma, núcleo, vacuola central y cloroplastos.':'Modelo simplificado: membrana, citoplasma, núcleo y mitocondrias. No representa todos los orgánulos.')}</p><small>La cámara funciona solo mientras permaneces en esta aula y pestaña. No requiere micrófono.</small></div></div></section>
}
