'use client';
import {Code} from './omics-workbench';
import {signalCode,statistics,retention} from '@/lib/omics-code';
import {gcmsReader} from '@/lib/gcms-python-course';
export default function GcmsPythonLab(){return <div className="gcms-python-lab"><p><strong>Cómo trabajar:</strong> descarga el código y ejecútalo en tu computador o en un cuaderno Python. Esta sección no sube ni procesa archivos instrumentales en el servidor de la página.</p>
 <section><h3>1. Preparar datos y entorno</h3><p>Conserva los originales y registra muestra, blanco, QC, lote y orden de inyección. Convierte con el software compatible con tu instrumento a mzML MS1 centroidado y comprueba que se conservaron tiempos, espectros y unidades. No cambies la extensión de un archivo para convertirlo.</p><Code title="Instalación en un entorno propio" filename="instalacion-gcms.txt" code={'python -m venv .venv\n# Windows PowerShell: .venv\\Scripts\\Activate.ps1\n# macOS / Linux: source .venv/bin/activate\npython -m pip install pyteomics numpy lxml pandas scipy matplotlib scikit-learn statsmodels\npython -m pip freeze > versiones.txt'}/></section>
 <section><h3>2. Leer mzML y observar TIC / EIC</h3><p>La plantilla suma intensidades centroidadas MS1 dentro de una ventana de m/z. Produce <code>cromatogramas.csv</code>, <code>eic.svg</code> y <code>parametros.json</code>. El modo demo usa una señal sintética; no simula espectros reales ni identifica moléculas.</p><Code title="Lector GC-MS y demo ejecutable" filename="gcms_taller.py" code={gcmsReader}/><Code title="Comandos de práctica" filename="ejecutar-gcms.txt" code={'# Primera prueba, sin datos instrumentales:\npython gcms_taller.py --demo --out demo_gcms\n\n# Después, con una copia de tu mzML centroidado:\npython gcms_taller.py muestra.mzML --mz 93 --tol 0.5 --out resultados_muestra_01\n# Ajusta m/z y tolerancia al método. Utiliza una carpeta de salida nueva.'}/><p>Compara muestra, blanco y QC con iguales parámetros. Para deconvolución y alineamiento no dirigido consulta <a href="https://pymassspec.readthedocs.io/en/master/" target="_blank" rel="noreferrer">PyMassSpec</a>, AMDIS o MS-DIAL; un EIC no resuelve por sí solo una coelución.</p></section>
 <section><h3>3. Integrar una región dirigida y revisar retención</h3><p>Selecciona una región aislada del EIC y guárdala como <code>signal.csv</code> con <code>rt_s,intensity</code>: convierte minutos a segundos y usa intensidad EIC. Revisa los extremos y el fondo antes de integrar. La plantilla aplica una corrección simple; no reemplaza una validación del método.</p><Code title="Fondo e integración de una región revisada" filename="integrar_gcms.py" code={signalCode('Python','GC-MS')}/><Code title="Índices lineales de retención con n-alcanos" filename="indices_gcms.py" code={retention.Python}/></section>
 <section><h3>4. Construir la matriz y explorar calidad</h3><p>Tras revisar componentes, alineamiento y áreas, prepara <code>features.csv</code> (sample_id,F001,F002,…) y <code>metadata.csv</code> (sample_id,type,group,batch,order); type=sample/qc/blank. Conserva otra tabla con RT, m/z, anotación, evidencia y unidades.</p><p>La plantilla siguiente calcula resúmenes QC y PCA. Sus filtros e imputación son ejemplos para revisar; no corrige automáticamente todos los efectos de lote ni valida biomarcadores.</p><Code title="Control descriptivo y PCA de la matriz revisada" filename="qc_pca_gcms.py" code={statistics.Python}/></section>
 <section><h3>5. Entregar un análisis reproducible</h3><ul><li>Datos o identificadores de acceso, metadatos y versiones.</li><li>Parámetros, gráficos de blancos/QC y criterios de exclusión.</li><li>Matriz revisada y niveles de confianza de anotación.</li><li>Interpretación con limitaciones y próximos controles.</li></ul><p>El docente puede publicar datos, presentaciones y guías adicionales en el espacio del taller. No incluyas datos personales de participantes en los archivos de práctica.</p></section>
 </div>}
