'use client';
import {useRef,useState} from 'react';
const chapters=[{"title":"Introducción de los COV","text":"Una jeringa introduce una alícuota del espacio de cabeza en el inyector caliente. También puede usarse SPME: los COV se desorben de la fibra, sin inyectar líquido.","start":0},{"title":"Transporte por el gas portador","text":"El gas portador arrastra la banda de moléculas hacia la columna capilar. El modo split o splitless controla la fracción transferida; depende del método.","start":18},{"title":"Partición en la columna","text":"Los COV alternan entre el gas móvil y la película de fase estacionaria. Una interacción mayor con esa película aumenta el tiempo de retención.","start":31},{"title":"Separación y elución","text":"La volatilidad, la afinidad por la fase y la temperatura del horno determinan la separación. Los compuestos salen en bandas; el orden no depende solo de su masa.","start":45},{"title":"Transferencia e ionización EI","text":"La línea caliente conduce los COV a la fuente bajo vacío. En ionización electrónica, típicamente a 70 eV, se forman iones moleculares y fragmentos cargados.","start":59},{"title":"Filtrado por masa/carga","text":"En este ejemplo, un cuadrupolo transmite iones de una relación m/z seleccionada. Al barrer distintos valores se obtiene un espectro. Los neutros no se detectan como iones.","start":76},{"title":"Detección y cromatograma","text":"El detector convierte los impactos de iones en señal eléctrica. El TIC suma la señal iónica de cada barrido y la representa frente al tiempo de retención.","start":92},{"title":"Interpretar y confirmar","text":"Un espectro muestra intensidad frente a m/z. Se compara con bibliotecas, índices de retención y estándares. Una coincidencia de biblioteca no confirma por sí sola la identidad.","start":107}];
export default function GcmsJourney(){
 const video=useRef<HTMLVideoElement>(null);const [current,setCurrent]=useState(0);
 return <section className="gcms-journey" aria-labelledby="gcms-video-title">
 <span className="eyebrow">VIDEO ANIMADO · NARRACIÓN EN ESPAÑOL</span><h3 id="gcms-video-title">El viaje de los COV: de la muestra al espectro</h3>
 <p>Recorre un sistema GC–MS con ionización electrónica y analizador cuadrupolar. Reproduce el video o selecciona una etapa para revisarla.</p>
 <video ref={video} controls playsInline preload="metadata" poster="/learning-media/recorrido-cov-gcms.jpg" onTimeUpdate={()=>{const t=video.current?.currentTime||0;setCurrent(Math.max(0,chapters.findLastIndex(c=>c.start<=t)))}}>
 <source src="/learning-media/recorrido-cov-gcms.mp4" type="video/mp4"/><track kind="captions" src="/learning-media/recorrido-cov-gcms.vtt" srcLang="es" label="Español"/>
 Tu navegador no reproduce este video. Consulta la explicación por etapas debajo.</video>
 <nav className="gcms-chapters" aria-label="Etapas del video GC-MS">{chapters.map((c,i)=><button type="button" key={c.title} aria-pressed={current===i} onClick={()=>{if(video.current){video.current.currentTime=c.start;setCurrent(i)}}}>{i+1}. {c.title}</button>)}</nav>
 <p><strong>Para interpretar la animación:</strong> la fuente EI forma iones y puede fragmentarlos; el cuadrupolo filtra por m/z y el detector registra los iones transmitidos. Los colores, trayectorias, tiempos y señales son ilustrativos, no datos experimentales. Voz sintética en español.</p>
 <details><summary>Leer la explicación completa</summary><ol>{chapters.map(c=><li key={c.title}><h4>{c.title}</h4><p>{c.text}</p></li>)}</ol></details>
 <details><summary>Preguntas para discutir</summary><ul><li>¿Por qué dos COV transportados por el mismo gas pueden salir en momentos diferentes?</li><li>¿Dónde se originan los fragmentos y qué selecciona el cuadrupolo?</li><li>¿Qué diferencia hay entre un pico del cromatograma y una barra del espectro?</li><li>¿Qué evidencias adicionales necesitas para confirmar un compuesto?</li></ul></details>
 <p className="muted">Fundamentos: <a href="https://www.agilent.com/en/product/gas-chromatography/what-is-gas-chromatography" target="_blank" rel="noreferrer">cromatografía de gases</a> · <a href="https://www.agilent.com/en/product/gas-chromatography-mass-spectrometry-gc-ms/gcms-fundamentals/gcms-faqs" target="_blank" rel="noreferrer">ionización y GC–MS</a>.</p>
 <style>{`.gcms-journey{padding:24px;border:1px solid #b9d4dc;border-radius:16px;background:#fff;margin:24px 0 36px}.gcms-journey video{display:block;width:100%;height:auto;background:#081e2b;border-radius:12px;margin:20px 0}.gcms-chapters{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:8px}.gcms-chapters button{padding:12px;text-align:left;border:1px solid #b9d4dc;border-radius:8px;background:#f2f8f8;color:#17394b;cursor:pointer}.gcms-chapters button[aria-pressed=true]{background:#087466;color:#fff}.gcms-journey details{margin:16px 0}.gcms-journey p{line-height:1.7}@media(max-width:600px){.gcms-journey{padding:12px}}`}</style>
 </section>;
}
