import {AcademicProfiles} from './sections';
const profile={id:'gonzalo-taborda-ocampo',kind:'profile',title:'Gonzalo Taborda Ocampo',name:'Gonzalo Taborda Ocampo',status:'published',position:1,scholar:'https://scholar.google.com/citations?user=evwBqfMAAAAJ&hl=es',researchgate:'https://www.researchgate.net/profile/Gonzalo-Taborda',orcid:'https://orcid.org/0000-0003-4358-1506'};
export default function GonzaloProfile(){return <section aria-labelledby="gonzalo-profile-title" className="gonzalo-profile"><span className="eyebrow">DOCENCIA E INVESTIGACIÓN</span><h2 id="gonzalo-profile-title">Gonzalo Taborda Ocampo</h2><p className="lead">Profesor titular del Departamento de Química de la Universidad de Caldas y doctor en Ciencias Químicas. Su producción científica aborda el análisis instrumental, los compuestos volátiles, los alimentos y las aplicaciones de la metabolómica.</p>
<section className="text-section"><h3>Formación académica</h3><ul>
<li>Doctorado en Ciencias Químicas · Universidad Autónoma de Madrid.</li>
<li>Maestría en Ciencias Químicas · Universidad del Valle.</li>
<li>Especialización en Ciencia y Tecnología de los Alimentos (DEA) · Universidad Autónoma de Madrid.</li>
<li>Licenciatura en Biología y Química · Universidad de Caldas.</li></ul>
<p className="muted">Fuentes: <a href="https://doctoradoagrarias.ucaldas.edu.co/wp-content/uploads/2022/10/DCA_2018_compressed.pdf" target="_blank" rel="noreferrer">perfil académico del Doctorado en Ciencias Agrarias</a> y <a href="https://www.ucaldas.edu.co/portal/universidad-de-caldas-cuenta-con-nuevo-vicerrector-de-investigaciones-y-posgrados/" target="_blank" rel="noreferrer">reseña institucional de 2022</a>.</p></section>
<section className="text-section"><h3>Trayectoria docente e investigativa</h3><p>La Universidad de Caldas lo registra como profesor titular de su Departamento de Química. Figura en los equipos docentes de los doctorados en Ciencias Agrarias y en Ciencias. Su actividad reúne docencia universitaria, investigación y gestión académica.</p><p>La reseña institucional de mayo de 2022 documenta su labor como jefe de la Oficina de Investigaciones desde 2018 y su nombramiento como vicerrector de Investigaciones y Posgrados en 2022. En esa misma reseña se registra su reconocimiento como investigador sénior por Minciencias.</p><p className="muted">Fuentes: <a href="https://www.ucaldas.edu.co/portal/transparencia/contactos-y-directorios/" target="_blank" rel="noreferrer">directorio institucional</a> · <a href="https://doctoradoagrarias.ucaldas.edu.co/teachers/gonzalo-taborda-ocampo/" target="_blank" rel="noreferrer">equipo docente de Ciencias Agrarias</a> · <a href="https://investigacionesyposgrados.ucaldas.edu.co/wp-content/uploads/Brochure_Doctorado_Ciencias.pdf" target="_blank" rel="noreferrer">Doctorado en Ciencias</a> · <a href="https://www.ucaldas.edu.co/portal/universidad-de-caldas-cuenta-con-nuevo-vicerrector-de-investigaciones-y-posgrados/" target="_blank" rel="noreferrer">trayectoria y nombramiento de 2022</a>.</p></section>
<section className="text-section"><h3>Áreas de interés</h3><p>Síntesis temática de las investigaciones seleccionadas a continuación:</p><ul><li>Química analítica, cromatografía y espectrometría de masas.</li><li>Volatilómica y caracterización de aromas en matrices alimentarias.</li><li>Metabolómica y xenometabolómica aplicadas a biomarcadores de toxicidad.</li><li>Calidad e inocuidad de alimentos, café y frutos tropicales.</li><li>Biosensores y desarrollo de herramientas de detección analítica.</li></ul></section>
<section className="text-section"><h3>Investigaciones y publicaciones seleccionadas</h3><div className="gonzalo-research-grid">
<article><h4>Volatilómica del aguacate Hass</h4><p>Estudio de los compuestos volátiles de cáscara, pulpa y semilla mediante HS-SPME y GC–MS, con análisis de rutas metabólicas asociadas. Trabajo en coautoría publicado en Food Science &amp; Nutrition (2025).</p><a href="https://doi.org/10.1002/fsn3.70489" target="_blank" rel="noreferrer">Consultar artículo · DOI 10.1002/fsn3.70489</a></article>
<article><h4>Exposición a endosulfán y posibles biomarcadores</h4><p>Investigación en coautoría sobre cambios del perfil de volátiles en tejidos de aguacate Hass expuestos a endosulfán y candidatos a biomarcadores de toxicidad. Sustainable Food Technology (2025).</p><a href="https://pubs.rsc.org/en/content/articlelanding/2025/fb/d5fb00163c" target="_blank" rel="noreferrer">Consultar artículo · Royal Society of Chemistry</a></article>
<article><h4>Xenometabolómica y toxicidad</h4><p>Revisión en coautoría sobre aplicaciones de la xenometabolómica para estudiar respuestas frente a contaminantes e identificar biomarcadores. Biosalud; publicación en línea en 2025, volumen 19(1), rotulado 2020.</p><a href="https://revistasojs.ucaldas.edu.co/index.php/biosalud/article/view/9851" target="_blank" rel="noreferrer">Consultar revisión · Biosalud</a></article>
<article><h4>Fermentación y aroma del café colombiano</h4><p>Trabajo en coautoría que compara procesos poscosecha y tiempos de fermentación a partir del perfil volátil y sensorial del café. Coffee Science, volumen 17 (2022).</p><a href="https://coffeescience.ufla.br/index.php/Coffeescience/article/view/2016" target="_blank" rel="noreferrer">Consultar artículo · Coffee Science</a></article></div></section>
<section className="text-section"><h3>Proyectos destacados y desarrollos</h3><div className="gonzalo-research-grid"><article><h4>Biosensor para ocratoxina A en café</h4><p>Coinventor de la patente colombiana NC2017/0012960, relacionada con la fabricación de un chip, la inmovilización de peroxidasa y la detección de ocratoxina A en café. La Universidad de Caldas anunció su concesión en 2020; los titulares son la Universidad de Caldas y el SENA Regional Caldas.</p><a href="https://www.ucaldas.edu.co/portal/superintendencia-de-industria-y-comercio-otorgo-2-nuevas-patentes-a-la-universidad-de-caldas/" target="_blank" rel="noreferrer">Ver desarrollo y coinventores · Universidad de Caldas</a></article>
<article><h4>Colaboración en tecnologías de nariz electrónica</h4><p>La Universidad de Pamplona documentó en abril de 2026 su participación, junto con Jeny Aguirre Salazar, en la coordinación y desarrollo de la agenda académica e institucional vinculada a la entrega de una nariz electrónica a la Industria Licorera de Caldas.</p><a href="https://www.unipamplona.edu.co/unipamplona/portalIG/home_1/recursos/noticias_2026/abril/20042026/nota_sec_nariz_electronica.jsp" target="_blank" rel="noreferrer">Consultar iniciativa · Universidad de Pamplona</a></article></div></section><AcademicProfiles profile={profile}/><p>ORCID: <a href={profile.orcid} target="_blank" rel="noreferrer">0000-0003-4358-1506</a></p><style>{`.gonzalo-profile{margin-top:56px;padding-top:40px;border-top:1px solid #b9d4dc}.gonzalo-profile h3{font-size:1.65rem;margin-top:32px}.gonzalo-research-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,300px),1fr));gap:20px}.gonzalo-research-grid article{padding:22px;border:1px solid #b9d4dc;border-radius:12px;background:#fff}.gonzalo-research-grid h4{font-size:1.2rem;margin:0 0 14px}.gonzalo-profile li{margin:10px 0}.gonzalo-profile>h2{font-size:clamp(2rem,4vw,3.2rem);margin:12px 0 20px}`}</style></section>}
