const python:Record<string,[string,string]>={PySCF:['pyscf','pyscf'],'RDKit':['rdkit','rdkit'],'ASE':['ase','ase'],'cclib':['cclib','cclib'],'JupyterLab':['jupyterlab','jupyterlab'],'NumPy':['numpy','numpy'],'SciPy':['scipy','scipy'],'pandas':['pandas','pandas'],'Matplotlib':['matplotlib','matplotlib'],'MDAnalysis':['MDAnalysis','MDAnalysis'],'MDTraj':['mdtraj','mdtraj'],'3Dmol.js / py3Dmol':['py3Dmol','py3Dmol']};
const conda:Record<string,[string,string]>={'Open Babel':['openbabel','obabel -V'],'xTB':['xtb','xtb --version'],'Psi4':['psi4','psi4 --version'],'OpenMM':['openmm','python -m openmm.testInstallation'],'AmberTools':['ambertools','cpptraj --version']};
const desktop:Record<string,[string,string]>={
 'Avogadro':['Descarga el instalador de Windows, DMG de macOS o distribución Linux. Instálalo y abre la aplicación. Los motores de cálculo se instalan por separado.','Construye H₂O, guarda XYZ y vuelve a abrirlo.'],
 'ORCA':['Solicita acceso académico/personal o una licencia comercial. Descarga el paquete de tu plataforma, descomprímelo y sigue la guía de variables de entorno. Instala MPI solo si usarás ejecución paralela y con la versión indicada por ORCA.','Ejecuta el ejemplo de agua del tutorial en modo serial usando la ruta completa al ejecutable; confirma terminación normal.'],
 'Miniforge':['Descarga el instalador de tu sistema y arquitectura. Instala para tu usuario; abre Miniforge Prompt en Windows o la terminal inicializada en macOS/Linux.','Ejecuta conda --version y conda info.'],
 'GROMACS':['En Linux/macOS instala una distribución compatible o compila siguiendo la guía con CMake y compilador C/C++. En Windows usa la ruta WSL/Linux documentada. Selecciona FFT y soporte GPU según hardware; no actives CUDA sin GPU/controlador compatibles.','Ejecuta gmx --version y los tests oficiales de la distribución.'],
 'LAMMPS':['Elige binario/paquete o compilación CMake. Comprueba que incluya los paquetes de potenciales usados en clase; MPI y aceleradores son opcionales.','Ejecuta lmp -h y un ejemplo incluido, verificando el archivo log.lammps.'],
 'NAMD':['Regístrate y acepta la licencia de UIUC. Elige la compilación CPU/GPU y sistema correctos. Extrae el paquete y conserva la documentación.','Ejecuta un tutorial de la misma versión y revisa energía y finalización.'],
 'CP2K':['Usa un paquete compatible o sigue la compilación oficial con su toolchain. Instala las bibliotecas numéricas requeridas y conserva los archivos de bases y pseudopotenciales.','Ejecuta cp2k --version (o el nombre de binario de la distribución) y un test oficial.'],
 'Quantum ESPRESSO':['Descarga el paquete oficial y sigue la compilación/instalación de tu plataforma con compiladores y bibliotecas numéricas. Descarga pseudopotenciales apropiados por separado.','Ejecuta pw.x -h y un ejemplo oficial; verifica ruta de pseudopotenciales.'],
 'NWChem':['Selecciona binario compatible o sigue la guía de compilación con MPI y bibliotecas numéricas. Configura las rutas de bases indicadas por la distribución.','Ejecuta un ejemplo pequeño oficial y comprueba el cierre correcto.'],
 'VMD':['Regístrate y acepta la licencia. Descarga el paquete de tu plataforma y sigue su instalación; no necesitas instalar NAMD para visualizar.','Abre una estructura PDB y, si está disponible, su trayectoria compatible.'],
 'UCSF ChimeraX':['Acepta la licencia no comercial si corresponde o solicita la comercial. Descarga e instala la versión para tu sistema. Usa Toolshed únicamente para extensiones compatibles.','Abre un PDB local y cambia entre representación de cintas y átomos.'],
 'PyMOL · edición comercial':['Adquiere o usa la licencia institucional autorizada. Descarga el instalador desde tu cuenta, instala y activa con el mecanismo de licencia proporcionado.','Abre un PDB y guarda una sesión PSE.'],
 'PyMOL · código abierto':['Abre el repositorio oficial y sigue las instrucciones de compilación de esa versión o una distribución comunitaria autorizada. Revisa dependencias C/C++, OpenGL y Qt; no uses el instalador comercial como si fuera abierto.','Inicia pymol, abre un PDB y verifica la representación.'],
 'Jmol / JSmol':['Descarga el ZIP oficial. Para escritorio instala un entorno Java compatible y abre Jmol.jar. JSmol se integra en un servidor web, sin instalar Java en el navegador.','En escritorio ejecuta java -jar Jmol.jar y abre XYZ o PDB.'],
 'Mol*':['Para uso inmediato abre el visor de la web oficial. Para integración local descarga el código y sigue su README con Node y el gestor de paquetes indicado.','Carga un archivo mmCIF/PDB y comprueba las cadenas.'],
 'OVITO Basic':['Descarga específicamente Basic para tu plataforma e instala o extrae el paquete. Revisa requisitos gráficos.','Abre un archivo de ejemplo o una trayectoria LAMMPS compatible.'],
 'OVITO Pro':['Compra o utiliza una licencia institucional Pro. Descarga Pro, instala y activa según el portal de licencias; Basic no activa las funciones Pro.','Abre un ejemplo y verifica que estén disponibles los modificadores licenciados.'],
 'Gaussian':['Solicita licencia institucional o individual al proveedor y recibe los medios oficiales. Sigue el manual de tu plataforma, configura rutas y directorio scratch con espacio suficiente.','Ejecuta el ejemplo de validación distribuido y comprueba Normal termination.'],
 'GaussView':['Obtén una licencia de GaussView, descarga/recibe su instalador autorizado y configura el vínculo a Gaussian si se calculará. Son licencias separadas.','Construye agua, genera una entrada y abre un resultado de ejemplo.'],
 'Q-Chem':['Solicita licencia y paquete de plataforma al proveedor. Instala siguiendo el manual, configura el archivo/servidor de licencias y directorio temporal.','Ejecuta el cálculo de ejemplo oficial y confirma la licencia y finalización.'],
 'AMS · Amsterdam Modeling Suite':['Solicita prueba o licencia. Descarga desde tu cuenta SCM, instala y activa la licencia con los módulos y equipos autorizados.','Abre AMSinput y ejecuta el tutorial inicial de un motor incluido en tu licencia.'],
 'BIOVIA Materials Studio':['Solicita acceso institucional/comercial a BIOVIA. Descarga desde el portal autorizado e instala cliente, servidor de cálculo y gestor de licencias que correspondan a tu contrato.','Abre un proyecto de ejemplo y prueba un módulo realmente licenciado.'],
 'Amber':['Solicita la licencia de Amber y descarga la distribución oficial. Instala las dependencias y compila mediante la guía CMake, con CUDA solo si procede. AmberTools tiene una distribución distinta.','Ejecuta la suite de pruebas indicada por el manual antes de producir trayectorias.'],
 'Extensiones de PySCF':['Instala y verifica primero PySCF. Selecciona una extensión concreta en la lista oficial; revisa su licencia, compatibilidad y comando de instalación propio. No instales todas indiscriminadamente.','Ejecuta el ejemplo y test de la extensión elegida.'],
 'OPI · ORCA Python Interface':['Instala primero una versión compatible de ORCA y un entorno Python. Sigue el comando de instalación de OPI de su guía oficial y configura la ruta al motor.','Ejecuta el ejemplo inicial de OPI con el motor ORCA y confirma el archivo de salida.']
};
export default function InstallationGuide({name,url}:{name:string;url:string}){const p=python[name],c=conda[name],d=desktop[name];return <details className="install-guide"><summary>Guía de instalación · {name}</summary><ol><li>Comprueba sistema operativo, arquitectura, memoria y licencia en la <a href={url} target="_blank" rel="noreferrer">documentación oficial</a>. En Windows, usa WSL cuando la distribución solo admita Linux.</li>{p?<><li>Instala Python compatible con la versión del paquete. Crea un entorno independiente en la carpeta de trabajo.</li><li><pre><code>{`python -m venv .venv\n# Windows PowerShell:\n.venv\\Scripts\\Activate.ps1\n# macOS/Linux (alternativa):\nsource .venv/bin/activate\npython -m pip install --upgrade pip\npython -m pip install ${p[0]}\npython -c "import ${p[1]}; print('Importación correcta')"\npython -m pip freeze > requirements.txt`}</code></pre>Ejecuta solo la activación que corresponda a tu sistema. Si no hay un paquete binario compatible, sigue la ruta de compilación oficial; no cambies permisos globales para forzar la instalación.</li>{name==='JupyterLab'&&<li>Ejecuta <code>jupyter lab</code> y crea un cuaderno con el entorno instalado.</li>}</>:c?<><li>Instala Miniforge para tu sistema y abre su terminal.</li><li><pre><code>{`conda create -n aula-${name.toLowerCase().replace(/[^a-z]/g,'')} -c conda-forge ${c[0]}\nconda activate aula-${name.toLowerCase().replace(/[^a-z]/g,'')}\n${c[1]}\nconda env export > environment.yml`}</code></pre>La disponibilidad depende de plataforma y arquitectura; si Conda no encuentra una compilación, usa la alternativa oficial, no paquetes de terceros desconocidos.</li></>:<><li>{d?.[0]||'Sigue la instalación de la distribución oficial seleccionada.'}</li><li><strong>Verificación:</strong> {d?.[1]||'Ejecuta el ejemplo oficial incluido.'}</li></>}<li>Guarda versión, sistema, comandos y prueba realizada en el informe. Un resultado científico requiere validar el método además de instalar el programa.</li></ol></details>}
