'use client';
import {lazy,Suspense,useEffect,useState} from 'react';
const AugmentedClassroom=lazy(()=>import('./augmented-classroom'));
const ComputationalClassroom=lazy(()=>import('./computational-classroom'));
import {schoolGrades} from '@/lib/course-metadata';
import {Atom,ArrowUpRight,ArrowRight,BookOpen,FlaskConical,Search,FileText,Play,GraduationCap,Leaf,Microscope,ChevronRight,UserRound,Menu,Download,Mail,Orbit,Dna,Scale} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Item,ancestry,descendants,safeUrl,kinds,educationLabel} from '@/lib/content';
import {AnnualPlan,AcademicProfiles,profileSocial,ResearchOverview,ResearchCards,UniversityCatalog} from './sections';
import {Bookshelf,GraduateShell,isGraduate,SeparationLab} from './academic';
const nav=[['inicio','Inicio'],['octavo','Ciencias Naturales 8°'],['noveno','Ciencias Naturales 9°'],['ramas','Ramas y posgrados'],['decimo','Química de Décimo'],['once','Química de Once'],['laboratorios-experimentales','Lab. experimental'],['laboratorios-teoricos','Lab. teórico'],['analisis-instrumental','Datos instrumentales'],['realidad-aumentada','Realidad aumentada'],['quimica-computacional','Química computacional'],['investigaciones','Investigaciones'],['sobre-mi','Sobre mí'],['contacto','Contacto']];
const icons=[Atom,FlaskConical,Orbit,Microscope,Scale,Dna,Leaf];
export function Choice({value,onChange,options,label}:{value:string;onChange:(s:string)=>void;options:[string,string][];label:string}){return <Select value={value||'_'} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue placeholder={label}/></SelectTrigger><SelectContent>{options.map(([id,text])=><SelectItem value={id||'_'} key={id}>{text}</SelectItem>)}</SelectContent></Select>}
function Tag({children}:{children:React.ReactNode}){return <span className="tag">{children}</span>}
function Social({value}:{value?:string}){return <>{(value||'').split('\n').map((line,n)=>{const [label,url]=line.split('|');return safeUrl(url)?<a key={n} href={safeUrl(url)} target="_blank" rel="noreferrer">{label} <ArrowUpRight size={14}/></a>:null})}</>}
const empty=(text:string)=><div className="empty-state"><BookOpen size={28}/><p>{text}</p></div>;
function Rows({items,all}:{items:Item[];all:Item[]}){return <div className="resource-list">{items.map(i=><a className="resource-row" href={'#'+i.id} key={i.id}><span className="resource-icon">{i.resourceType==='Video'?<Play size={21}/>:i.kind==='topic'?<BookOpen size={21}/>:<FileText size={21}/>}</span><span><small>{educationLabel(i,all)&&educationLabel(i,all)+' · '}{ancestry(i,all).filter(p=>['course','branch','subbranch'].includes(p.kind)).map(p=>p.title).join(' · ')}{i.kind==='resource'&&' · '+i.resourceType}</small><strong>{i.title}</strong>{i.description&&<p>{i.description}</p>}</span>{i.example&&<Tag>Ejemplo</Tag>}{i.kind==="resource"&&ancestry(i,all).some(p=>p.current)&&<Tag>Período actual</Tag>}<ArrowUpRight size={19}/></a>)}</div>}
export default function Portal({initial,error}:{initial:Item[];error?:string}){
 const [route,setRoute]=useState('inicio'),[menu,setMenu]=useState(false),[query,setQuery]=useState(''),[area,setArea]=useState('_'),[year,setYear]=useState('_'),[pubtype,setPubtype]=useState('_');
 const all=initial,profile=all.find(i=>i.kind==='profile');
 useEffect(()=>{const go=()=>{if(location.hash==='#contenido'){document.getElementById('contenido')?.focus();return}try{setRoute(decodeURIComponent(location.hash.slice(1))||'inicio')}catch{setRoute('inicio')}setMenu(false);window.scrollTo(0,0)};go();window.addEventListener('hashchange',go);return()=>window.removeEventListener('hashchange',go)},[]);
 useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const c=new AbortController();Promise.resolve(ctx.registerTool({name:'buscar_materiales',description:'Busca materiales publicados y abre los resultados en la biblioteca.',inputSchema:{type:'object',properties:{consulta:{type:'string'}},required:['consulta'],additionalProperties:false},annotations:{readOnlyHint:true},execute:async(input:any)=>{if(typeof input?.consulta!=='string'||input.consulta.length>200)throw new Error('Consulta inválida');setQuery(input.consulta);location.hash='buscar';return all.filter(i=>['branch','subbranch','course','topic','resource','research'].includes(i.kind)&&(i.title+' '+(i.description||'')).toLowerCase().includes(input.consulta.toLowerCase())).map(i=>({titulo:i.title,nivel:educationLabel(i,all),enlace:'#'+i.id}));}},{signal:c.signal})).catch(()=>{});return()=>c.abort()},[all]);
 const item=all.find(i=>i.id===route),branches=all.filter(i=>i.kind==='branch');
 function search(e:React.FormEvent){e.preventDefault();location.hash='buscar';setRoute('buscar')}
 const searchForm=<form className="search-box" onSubmit={search}><Search size={21}/><input aria-label="Buscar en el sitio" value={query} onChange={e=>setQuery(e.target.value)} placeholder="¿Qué quieres aprender hoy?"/><button type="submit" aria-label="Buscar"><ArrowRight size={22}/></button></form>;
 const branchGrid=<div className="branch-grid">{branches.map((b,n)=>{const Icon=icons[n%icons.length];return <a href={'#'+b.id} className="branch-card" key={b.id}><Icon size={26}/><h3>{b.title}</h3><small className="level-badge">{educationLabel(b,all)}</small><p>{b.description}</p><span>{all.some(i=>i.parent===b.id&&i.kind==="subbranch")?all.filter(i=>i.parent===b.id&&i.kind==="subbranch").length+" subramas":"Explorar asignaturas"} <ArrowRight size={16}/></span></a>})}</div>;
 const gradRoot=item&&[...ancestry(item,all),item].find(i=>['sub-metabolomica','sub-volatilomica'].includes(i.id));
 if(gradRoot){const active=item!.id===gradRoot.id?all.find(i=>i.kind==='course'&&i.parent===gradRoot.id)||item!:item!;return <GraduateShell key={gradRoot.id} root={gradRoot} item={active} all={all}><h2>{active.title}</h2><p className="lead">{active.description}</p>{['course','unit','branch'].includes(active.kind)?<Course item={active} all={all}/>:active.kind==='resource'?<Resource item={active}/>:<><p className="prose">{active.body}</p><h3>Objetivos</h3><p className="prose">{active.objectives||'Pendientes de completar.'}</p><h3>Actividades</h3><p className="prose">{active.activities||'Pendientes de publicar.'}</p><Rows all={all} items={all.filter(r=>r.kind==='resource'&&r.links?.includes(active.id))}/></>}</GraduateShell>}
 const recent=all.filter(i=>['topic','resource'].includes(i.kind)).sort((a,b)=>Number(!!b.featured)-Number(!!a.featured)||String(b.updatedAt||'').localeCompare(String(a.updatedAt||''))).slice(0,5);
 return <><a className="skip" href="#contenido">Saltar al contenido</a><header><div className="topbar wrap"><a href="#inicio" className="brand"><span className="brand-mark"><Atom size={26}/></span><span>Aula<span className="brand-light">Química</span><small>UN ESPACIO PARA APRENDER</small></span></a><span className="header-note">La química, más cerca de ti.</span><a href="/acceso" className="admin-link"><UserRound size={16}/> Mi cuenta</a><button className="mobile-toggle" onClick={()=>setMenu(!menu)} aria-label="Abrir menú" aria-expanded={menu}><Menu/></button></div><div className={'nav-shell '+(menu?'open':'')}><nav className="wrap main-nav" aria-label="Menú principal">{nav.map(([id,label])=><a key={id} href={'#'+id} aria-current={route===id?'page':undefined} className={route===id?'active':''}>{label}</a>)}</nav></div></header>
 <main id="contenido" className="wrap" tabIndex={-1}>{error&&<p className="notice" role="alert">{error}</p>}
 {route==='inicio'?<><section className="intro"><div className="intro-copy"><span className="eyebrow">COLEGIO · UNIVERSIDAD · INVESTIGACIÓN</span><h1>La química se entiende<br/>mejor <em>cuando conecta.</em></h1><p>Un espacio para explorar, aprender y compartir.<br/>Encuentra los materiales de tu clase y sigue descubriendo.</p>{searchForm}<div className="search-hint">Busca temas, guías, videos o investigaciones.</div></div><aside className="intro-note"><span className="note-label">EL PUNTO DE PARTIDA</span><div className="element"><small>6</small><strong>C</strong><span>Curiosidad</span><small>∞ posibilidades</small></div><p>Observa. Pregunta.<br/><strong>Encuentra conexiones.</strong></p><span className="note-line">Del aula al mundo que nos rodea.</span></aside></section>
 <section className="grade-section"><div className="section-heading"><div><span className="eyebrow">TU AULA, A UN CLIC</span><h2>¿Por dónde empezamos?</h2></div><span className="muted">Elige tu grado y encuentra tu material.</span></div><div className="grade-grid">{schoolGrades.map((g,n)=><a className={'grade-card grade-'+(n%2)} href={'#'+g.id} key={g.id}><div><span className="grade-label"><GraduationCap size={19}/>{g.level}</span><h2>{g.title}</h2><p>{g.description}</p><span className="grade-bottom">Unidades, guías y videos {g.id==='once'&&<span className="mini-tag">+ Saber 11</span>}<ArrowRight size={22}/></span></div><span className="grade-number">{g.number}<sup>°</sup></span></a>)}</div></section>
 <section><div className="section-heading"><div><span className="eyebrow">PREGRADO · FORMACIÓN UNIVERSITARIA</span><h2>Pregrado y posgrado</h2></div><a className="text-link" href="#ramas">Ver ramas y asignaturas <ArrowUpRight size={16}/></a></div>{branchGrid}</section>
 <section className="lower-grid"><div><div className="section-heading"><div><span className="eyebrow">PARA SEGUIR APRENDIENDO</span><h2>Destacados y recientes</h2></div></div>{recent.length?<Rows items={recent} all={all}/>:empty('Pronto encontrarás materiales destacados.')}</div><aside className="research-callout"><Microscope size={32}/><span className="eyebrow">MÁS ALLÁ DEL AULA</span><h2>Conocimiento<br/>que se comparte.</h2><p>Artículos, proyectos y trabajos académicos en un mismo espacio.</p><a href="#investigaciones">Explorar investigaciones <ArrowUpRight size={18}/></a></aside></section>
 <section className="teacher-strip"><div className="portrait">{validAsset(profile?.image)?<img src={profile?.image} alt={profile?.name||'Fotografía del docente'}/>:<UserRound size={42}/>}</div><div><span className="eyebrow">DETRÁS DE ESTE ESPACIO</span><h2>{profile?.name||'Tu docente e investigador'}</h2><p>{profile?.description||'Trayectoria, intereses y proyectos que conectan docencia e investigación. Perfil pendiente de completar.'}</p></div><a className="button secondary" href="#sobre-mi">Conoce mi perfil <ArrowUpRight size={17}/></a></section><p className="example-note">Los temas iniciales son ejemplos didácticos editables. No constituyen un currículo oficial ni materiales atribuidos al docente.</p></>:
 <><div className="page-search">{searchForm}</div>
 {route==='ramas'?<><span className="eyebrow">BIBLIOTECA UNIVERSITARIA</span><h1>Ramas y asignaturas universitarias</h1><p className="lead">Química general y las ramas fundamentales corresponden a pregrado. Metabolómica y Volatilómica tienen aulas propias de posgrado. Explora sus áreas de especialización o entra directamente a una asignatura.</p><div className="level-navigation"><a href="#decimo">Educación media: Décimo</a><a href="#once">Educación media: Once</a></div><h2>Ramas y especialidades</h2>{branchGrid}<UniversityCatalog all={all}/></>:
 route==='buscar'?<><span className="eyebrow">BIBLIOTECA</span><h1>Resultados de búsqueda</h1><p className="lead">{query?'Resultados para «'+query+'»':'Escribe un tema o una palabra clave.'}</p>{(()=>{const norm=(s:string)=>s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');const hits=all.filter(i=>['branch','subbranch','topic','resource','research','course'].includes(i.kind)&&norm([i.title,i.description,i.keywords,...ancestry(i,all).map(x=>x.title)].join(' ')).includes(norm(query)));return query?(hits.length?<Rows items={hits} all={all}/>:empty('No encontramos coincidencias. Prueba con otro término.')):null})()}</>:
 route==='investigaciones'?<><span className="eyebrow">CONOCIMIENTO QUE SE COMPARTE</span><h1>Investigaciones</h1><p className="lead">Artículos, proyectos y trabajos académicos.</p><ResearchOverview profile={profile} all={all} setType={setPubtype}/><div className="filters"><input aria-label="Buscar investigaciones" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Título, autor o palabra clave"/><Choice label="Área" value={area} onChange={setArea} options={[['_','Todas las áreas'],...all.filter(i=>['branch','subbranch'].includes(i.kind)).map(i=>[i.title,i.title] as [string,string])]}/><Choice label="Año" value={year} onChange={setYear} options={[['_','Todos los años'],...Array.from(new Set(all.filter(i=>i.kind==='research'&&i.date).map(i=>i.date!.slice(0,4)))).sort().reverse().map(y=>[y,y] as [string,string])]}/><Choice label="Tipo de publicación" value={pubtype} onChange={setPubtype} options={[['_','Todos los tipos'],...['Artículo','Proyecto','Trabajo académico','Otro'].map(v=>[v,v] as [string,string])]}/></div>{(()=>{const hits=all.filter(i=>i.kind==='research'&&(area==='_'||i.area===area)&&(year==='_'||i.date?.startsWith(year))&&(pubtype==='_'||i.publicationType===pubtype)&&[i.title,i.authors,i.description,i.keywords].join(' ').toLowerCase().includes(query.toLowerCase()));return hits.length?<ResearchCards items={hits}/>:empty('Aún no hay publicaciones que coincidan. Las investigaciones se añadirán cuando estén disponibles.')})()}</>:
 route==='sobre-mi'?<><span className="eyebrow">DOCENCIA E INVESTIGACIÓN</span><h1>{profile?.name||'Sobre mí'}</h1><div className="profile-layout"><div className="profile-photo">{validAsset(profile?.image)?<img src={profile?.image} alt={profile?.name||'Fotografía del docente'}/>:<><UserRound size={80}/><p>Fotografía pendiente</p></>}</div><div><p className="lead">{profile?.description||'La presentación profesional se publicará próximamente.'}</p>{[['Formación académica',profile?.education],['Trayectoria docente e investigativa',profile?.body],['Áreas de interés',profile?.interests],['Proyectos destacados',profile?.projects]].map(([t,v])=><section className="text-section" key={t}><h2>{t}</h2><p className="prose">{v||'Información pendiente de completar.'}</p></section>)}<AcademicProfiles profile={profile}/><div className="social-links"><Social value={profile?.social}/></div></div></div></>:
 route==='contacto'?<><span className="eyebrow">CONVERSEMOS</span><h1>Contacto</h1><div className="contact-layout"><div><p className="lead">¿Tienes una pregunta sobre los materiales o una propuesta académica?</p><a className="text-link" href={'mailto:'+(profile?.email||'juan.betancourt@ucaldas.edu.co')}><Mail size={20}/>{profile?.email||'juan.betancourt@ucaldas.edu.co'}</a><p className="muted">También puedes escribir directamente a este correo desde tu aplicación de correo.</p><div className="social-links"><Social value={profileSocial(profile)}/></div></div><Contact/></div></>:
 item?<><nav className="breadcrumbs" aria-label="Ubicación"><a href="#inicio">Inicio</a>{educationLabel(item,all)==="Pregrado"&&<span><ChevronRight size={13}/><a href="#ramas">Pregrado</a></span>}{ancestry(item,all).map(p=><span key={p.id}><ChevronRight size={13}/><a href={'#'+p.id}>{p.title}</a></span>)}<span><ChevronRight size={13}/>{item.title}</span></nav><span className="eyebrow">{educationLabel(item,all)&&educationLabel(item,all)+' · '}{kinds[item.kind]||'BIBLIOTECA'}</span><h1>{item.title}</h1>{item.example&&<p className="notice">Contenido de ejemplo · Editable y adaptable al plan de estudios de tu institución. No es un currículo oficial.</p>}{item.description&&<p className="lead">{item.description}</p>}{item.id==='realidad-aumentada'&&<Suspense fallback={<p>Cargando aula visual…</p>}><AugmentedClassroom/></Suspense>}{item.id==='quimica-computacional'&&<Suspense fallback={<p>Cargando herramientas…</p>}><ComputationalClassroom/></Suspense>}{['course','branch','subbranch','period','unit'].includes(item.kind)?<Course item={item} all={all}/>:
 item.kind==='topic'?<div className="topic-layout"><article>{[['Explicación teórica',item.body],['Ejemplos y ejercicios resueltos',item.examples],['Talleres y actividades',item.activities],['Bibliografía y enlaces complementarios',item.bibliography]].map(([title,text])=><section className="text-section" key={title}><h2>{title}</h2><p className="prose">{text||'Contenido pendiente de publicar.'}</p></section>)}</article><aside><h2>Recursos del tema</h2>{all.filter(r=>r.kind==='resource'&&(r.links?.includes(item.id)||r.parent===item.id)).length?<Rows items={all.filter(r=>r.kind==='resource'&&(r.links?.includes(item.id)||r.parent===item.id))} all={all}/>:empty('Guías y videos pendientes de publicar.')}</aside></div>:
 item.kind==='resource'?<Resource item={item}/>:
 item.kind==='research'?<article className="publication"><p>{item.authors||'Autores pendientes'} · {item.date||'Fecha pendiente'} · {item.publicationType}</p><Tag>{item.area||'Área sin definir'}</Tag>{validAsset(item.image)&&<img className="publication-image" src={item.image} alt={'Figura: '+item.title}/>}<h2>Resumen</h2><p className="prose">{item.description}</p><p><strong>Palabras clave:</strong> {item.keywords||'Pendientes'}</p><p className="prose">{item.body}</p>{item.file&&<a className="button" href={item.file+'?download=1'}>Descargar documento <Download size={17}/></a>}{safeUrl(item.url)&&<a className="button secondary" href={safeUrl(item.url)} target="_blank" rel="noreferrer">Publicación original / DOI <ArrowUpRight size={16}/></a>}</article>:null}</>:<><h1>Contenido no disponible</h1><p>Puede estar en borrador o haberse cambiado de ubicación.</p><a href="#inicio">Volver al inicio</a></>}
 </>}
 </main><footer><div className="wrap footer-inner"><a href="#inicio" className="brand"><Atom size={25}/> AulaQuímica</a><p>Aprender, explorar y compartir conocimiento.</p><div className="social-links"><Social value={profileSocial(profile)}/><a href="#contacto">Contacto</a><a href="/admin">Administración</a></div></div></footer></>;
}
function validAsset(s?:string){return !!s&&(s==='/perfil-ilustrado.png'||s.startsWith('/api/files/')||!!safeUrl(s));}
function Course({item,all}:{item:Item;all:Item[]}){const periods=all.filter(i=>i.parent===item.id&&i.kind==='period').sort((a,b)=>a.position-b.position);const ds=descendants(item.id,all);const resources=all.filter(i=>i.kind==='resource'&&(i.links?.includes(item.id)||ds.some(d=>i.links?.includes(d.id))||ds.some(d=>d.id===i.id)));return <div className="course-layout"><div><BranchOverview item={item} all={all}/><Bookshelf item={item} all={all}/><AnnualPlan item={item} all={all}/>{item.objectives&&<details className="objectives"><summary>Objetivos de aprendizaje</summary><p className="prose">{item.objectives}</p></details>}{item.kind==='course'&&<div className="plan"><FileText size={19}/>{item.plan?<a href={item.plan} target="_blank" rel="noreferrer">Consultar plan de asignatura</a>:<span>Plan de asignatura pendiente de cargar.</span>}</div>}{item.body&&<p className="prose">{item.body}</p>}{periods.length?<Tabs key={item.id} defaultValue={periods.find(i=>i.current)?.id||periods[0].id}><TabsList className="period-tabs">{periods.map(p=><TabsTrigger key={p.id} value={p.id}>{p.title}{p.current?' · Actual':''}</TabsTrigger>)}</TabsList>{periods.map(p=><TabsContent value={p.id} key={p.id}>{p.description&&<h2 className="period-heading">{p.description}</h2>}<UnitTree parent={p.id} all={all}/></TabsContent>)}</Tabs>:<UnitTree parent={item.id} all={all}/>} {periods.length>0&&all.some(i=>i.parent===item.id&&i.kind==='unit')&&<UnitTree parent={item.id} all={all} excludePeriods/>}</div><aside className="course-aside"><BookOpen size={27}/><h3>A mano para tu clase</h3><p>Consulta el tema y encuentra sus guías, actividades y videos en el mismo lugar.</p>{resources.length?<Rows items={resources} all={all}/>:<p className="muted">Los recursos aparecerán aquí al publicarse.</p>}</aside></div>}
function UnitTree({parent,all,excludePeriods=false}:{parent:string;all:Item[];excludePeriods?:boolean}){const children=all.filter(i=>i.parent===parent&&(!excludePeriods||i.kind!=='period')&&i.kind!=='resource').sort((a,b)=>a.position-b.position);return children.length?<div className="unit-tree">{children.map((i,n)=><div className="unit" key={i.id}><a className="unit-title" href={'#'+i.id}><span>{String(n+1).padStart(2,'0')}</span><strong>{i.title}</strong><ArrowUpRight size={18}/></a>{i.description&&<p>{i.description}</p>}{all.filter(x=>x.parent===i.id).sort((a,b)=>a.position-b.position).map(t=><a className="topic-link" href={'#'+t.id} key={t.id}><BookOpen size={17}/>{t.title}<ChevronRight size={16}/></a>)}</div>)}</div>:empty('Los contenidos de esta sección se publicarán próximamente.')}
function Resource({item}:{item:Item}){const [play,setPlay]=useState(false);let embed='';try{const u=new URL(item.url||'');if(['youtube.com','www.youtube.com','youtu.be','www.youtube-nocookie.com'].includes(u.hostname)){const id=u.hostname==='youtu.be'?u.pathname.slice(1):u.searchParams.get('v')||u.pathname.split('/').pop();if(id&&/^[\w-]{11}$/.test(id))embed='https://www.youtube-nocookie.com/embed/'+id;}if(['vimeo.com','www.vimeo.com'].includes(u.hostname)&&/^\/\d+$/.test(u.pathname))embed='https://player.vimeo.com/video'+u.pathname;}catch{}
return <article className="resource-detail"><Tag>{item.resourceType||'Material'}</Tag><p className="prose">{item.body}</p>{item.file&&<div className="download-panel"><FileText size={35}/><div><h2>{item.filename||'Documento de aprendizaje'}</h2><p>Consulta el documento o guárdalo para estudiar sin conexión.</p></div><a className="button secondary" href={item.file} target="_blank" rel="noreferrer">Consultar</a><a className="button" href={item.file+'?download=1'}>Descargar <Download size={17}/></a></div>}{embed&&(play?<iframe title={item.title} src={embed} allowFullScreen loading="lazy" className="video-frame"/>:<button className="video-placeholder" onClick={()=>setPlay(true)}><Play size={42}/>Cargar video explicativo<small>Se conectará con la plataforma de video.</small></button>)}{safeUrl(item.url)&&<a className="text-link" href={safeUrl(item.url)} target="_blank" rel="noreferrer">Abrir en la plataforma original <ArrowUpRight size={17}/></a>}{item.resourceType==='Video'&&<section className="text-section"><h2>Transcripción del video</h2><p className="prose">{item.transcript||'La transcripción se añadirá cuando esté disponible.'}</p></section>}{item.bibliography&&<p className="prose">{item.bibliography}</p>}</article>}
function Contact(){const [status,setStatus]=useState(''),[busy,setBusy]=useState(false);return <form className="contact-form" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;setBusy(true);setStatus('');try{const r=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(form)))});const d:any=await r.json();if(!r.ok)throw new Error(d.error);setStatus('Mensaje recibido. El docente podrá consultarlo en su panel.');form.reset()}catch(err){setStatus(err instanceof Error?err.message:'No se pudo enviar.')}finally{setBusy(false)}}}><label>Nombre<input name="name" autoComplete="name" required maxLength={150}/></label><label>Correo electrónico<input type="email" name="email" autoComplete="email" required maxLength={250}/></label><label>Mensaje<textarea name="message" rows={6} required maxLength={5000}/></label><input name="website" tabIndex={-1} autoComplete="off" className="honeypot" aria-hidden="true"/><p className="muted">Tu nombre, correo y mensaje se guardan para responder a tu consulta.</p><button className="button" disabled={busy}>{busy?'Enviando…':'Enviar mensaje'}<ArrowRight size={18}/></button><p role="status">{status}</p></form>}








function BranchOverview({item,all}:{item:Item;all:Item[]}){if(item.kind!=='branch')return null;const course=all.find(i=>i.id==='ampliacion-'+item.id);if(!course)return null;const units=all.filter(i=>i.kind==='unit'&&i.parent===course.id).sort((a,b)=>a.position-b.position);return <section className="branch-overview"><span className="eyebrow">EXPLORA ESTA RAMA · PREGRADO</span><h2>¿Qué estudia y cómo empezar?</h2><p>{course.description}</p><details><summary>Preparación y proyecto integrador</summary><p className="prose">{course.body}</p></details><h3>Al terminar podrás</h3><p>{course.objectives}</p><h3>Ruta de aprendizaje</h3><div className="branch-learning-grid">{units.map((u,n)=>{const topic=all.find(t=>t.kind==='topic'&&t.parent===u.id);return <a key={u.id} href={'#'+(topic?.id||u.id)}><span className="eyebrow">ETAPA {n+1}</span><strong>{u.title.replace(/^Unidad \d+ · /,'')}</strong><span>Explicación · ejemplo resuelto · actividad →</span></a>})}</div><a className="button secondary" href={'#'+course.id}>Abrir la ruta completa <ArrowRight size={16}/></a><p className="muted">Material didáctico editable. No constituye un currículo oficial.</p></section>}
