'use client';
import {ArrowUpRight,BookOpen,FileText,Microscope} from 'lucide-react';
import type {Item} from '@/lib/content';
import {safeUrl,descendants} from '@/lib/content';
import {curriculumSources,curriculumNotice} from '@/lib/curriculum';
import {scienceSources,scienceNotice} from '@/lib/natural-curriculum';
export function profileSocial(profile?:Item){return [...new Set([...(profile?.social||'').split('\n'),...([['Google Scholar',profile?.scholar],['ORCID',profile?.orcid],['ResearchGate',profile?.researchgate]] as [string,string|undefined][]).filter(([,url])=>safeUrl(url)).map(([name,url])=>name+' | '+url)])].filter(Boolean).join('\n')}
export function AcademicProfiles({profile}:{profile?:Item}){return <section className="academic-section"><h2>Perfiles académicos</h2><div className="academic-grid">{([['Google Scholar','Publicaciones y citas',profile?.scholar],['ORCID','Identificador de investigador',profile?.orcid],['ResearchGate','Producción y comunidad académica',profile?.researchgate]] as [string,string,string|undefined][]).map(([name,description,url])=>safeUrl(url)?<a key={name} className="academic-card connected" href={safeUrl(url)} target="_blank" rel="noreferrer"><strong>{name}<ArrowUpRight size={17}/></strong><p>{description}</p><span>Ver perfil</span></a>:<div className="academic-card" key={name}><strong>{name}</strong><p>{description}</p><span>Enlace pendiente de proporcionar</span></div>)}</div></section>}
export function AnnualPlan({item,all}:{item:Item;all:Item[]}){const periods=all.filter(i=>i.parent===item.id&&i.kind==='period').sort((a,b)=>a.position-b.position);if(!periods.length)return null;const topics=descendants(item.id,all).filter(i=>i.kind==='topic'&&!i.id.startsWith('saber-'));if(!topics.length)return null;return <section className="annual-plan"><div className="annual-top"><BookOpen size={24}/><div><h2>Plan anual de aprendizaje</h2><p>{periods.length} períodos · {topics.length?topics.length+' temas · Propuesta editable':'Temario pendiente de publicar'}</p></div></div><details><summary>Consultar todos los temas del año</summary><div className="annual-grid">{periods.map(p=><section key={p.id}><span className="eyebrow">{p.title}</span><h3>{p.description||'Unidades y temas'}</h3>{all.filter(i=>i.parent===p.id&&i.kind==='unit').sort((a,b)=>a.position-b.position).map(u=><div key={u.id}><h4><a href={'#'+u.id}>{u.title}</a></h4><ol>{all.filter(i=>i.parent===u.id&&i.kind==='topic').sort((a,b)=>a.position-b.position).map(t=><li key={t.id}><a href={'#'+t.id}>{t.title}</a></li>)}</ol></div>)}</section>)}</div><p className="notice">{["octavo","noveno"].includes(item.id)?scienceNotice:curriculumNotice}</p><p className="muted">Referentes consultados; la secuencia y los temas complementarios son una propuesta de organización del sitio.</p><div className="source-links">{(["octavo","noveno"].includes(item.id)?scienceSources:curriculumSources).map(s=><a href={s.url} key={s.url} target="_blank" rel="noreferrer">{s.title}<ArrowUpRight size={14}/></a>)}</div></details></section>}
export function ResearchOverview({profile,all,setType}:{profile?:Item;all:Item[];setType:(v:string)=>void}){const publications=all.filter(i=>i.kind==='research');return <section className="research-overview"><div className="research-heading"><Microscope size={30}/><div><h2>Mi espacio de investigación</h2><p>{profile?.researchIntro||'Publicaciones, proyectos y trabajos académicos. Los registros se incorporarán con sus autores, resumen, fecha y enlaces verificables.'}</p></div></div><div className="research-types">{['Artículo','Proyecto','Trabajo académico'].map(type=><button type="button" key={type} onClick={()=>setType(type)}><strong>{publications.filter(i=>i.publicationType===type).length}</strong><span>{type==='Artículo'?'Artículos':type==='Proyecto'?'Proyectos':'Trabajos académicos'}</span><ArrowUpRight size={17}/></button>)}</div>{profile?.researchLines&&<div className="research-lines"><h3>Líneas de investigación</h3><ul>{profile.researchLines.split('\n').filter(Boolean).map((line,n)=><li key={n}>{line}</li>)}</ul></div>}<div className="social-links">{([['Google Scholar',profile?.scholar],['ORCID',profile?.orcid],['ResearchGate',profile?.researchgate]] as [string,string|undefined][]).filter(([,url])=>safeUrl(url)).map(([name,url])=><a key={name} href={safeUrl(url)} target="_blank" rel="noreferrer">{name}<ArrowUpRight size={16}/></a>)}</div></section>}
export function ResearchCards({items}:{items:Item[]}){return <div className="research-grid">{items.map(i=><article className="research-card" key={i.id}>{i.image&&(safeUrl(i.image)||i.image.startsWith('/api/files/'))?<img src={i.image} alt={'Figura de '+i.title} loading="lazy"/>:<div className="research-card-symbol"><FileText size={30}/></div>}<div><span className="eyebrow">{i.publicationType||'Publicación'} · {i.date?.slice(0,4)||'Sin fecha'}</span><h2><a href={'#'+i.id}>{i.title}</a></h2><p className="research-authors">{i.authors||'Autores pendientes de completar'}</p><p className="research-abstract">{i.description}</p>{i.area&&<span className="tag">{i.area}</span>}{i.keywords&&<p className="research-keywords">{i.keywords}</p>}<a className="text-link" href={'#'+i.id}>Consultar investigación<ArrowUpRight size={16}/></a></div></article>)}</div>}
export function UniversityCatalog({all}:{all:Item[]}){const courses=all.filter(i=>i.kind==='course'&&!['octavo','noveno','decimo','once'].includes(i.id)&&descendants('rama-0',all).concat(...all.filter(b=>b.kind==='branch'&&b.id!=='rama-0').map(b=>descendants(b.id,all))).some(c=>c.id===i.id));return <section className="university-catalog"><div className="section-heading"><div><span className="eyebrow">FORMACIÓN UNIVERSITARIA</span><h2>Asignaturas de pregrado</h2></div><span className="muted">{courses.length} espacios editables</span></div><p className="lead">Desde los fundamentos hasta las asignaturas avanzadas. Cada espacio organiza unidades, temas y recursos de aprendizaje.</p><div className="branch-grid">{courses.map(c=><a className="branch-card" href={'#'+c.id} key={c.id}><BookOpen size={25}/><h3>{c.title}</h3><p>{c.description}</p><span>{all.filter(i=>i.parent===c.id&&i.kind==='unit').length} unidades · Pregrado <ArrowUpRight size={16}/></span></a>)}</div><p className="notice">Organización propuesta y editable. Los espacios están preparados para incorporar materiales; no representan un programa oficial ni cursos completos ya publicados.</p></section>}



