'use client';
import {lazy,Suspense} from 'react';
import type {Item} from '@/lib/content';
import {volatileWeeks,volatileReadings,volatileCourseId,volatileLabId,topicId} from '@/lib/volatilomics-course';
import './volatilomics-schedule.css';
import TopicPresentations from './topic-presentations';
const GcmsPythonLab=lazy(()=>import('./gcms-python-lab'));
export function VolatileReadingList({ids}:{ids:string[]}){return <div className="volatile-readings">{[...new Set(ids)].map(id=>{const r=volatileReadings[id];return <article key={id}><h4><a href={r.url} target="_blank" rel="noreferrer">{r.title} ↗</a></h4><p>{r.citation}</p><small>{r.language}</small><p><strong>Para esta lectura:</strong> {r.use}</p></article>})}</div>}
export default function VolatilomicsSchedule({all,weekId}:{all:Item[];weekId?:string}){
 const available=volatileWeeks.filter(w=>(!weekId||w.id===weekId)&&all.some(i=>i.id===w.id));
 const legacy=all.filter(i=>i.parent===volatileCourseId&&i.kind==='unit'&&!i.volatileWeek);
 return <section className="volatile-schedule">
 {!weekId&&<><span className="eyebrow">BIOPGR · GICTA · UNIVERSIDAD DE CALDAS</span><h2>Introducción a la Volatilómica</h2><p>Descifrando el lenguaje químico de la naturaleza. Ruta de seis semanas basada en los diez módulos de la propuesta del curso.</p><p className="notice">Distribución didáctica en seis semanas. El documento fuente enumera módulos, pero no fija su calendario semanal. Cada semana incluye temas, lecturas y una actividad; la intensidad horaria se ajusta con el docente.</p><nav className="volatile-week-links" aria-label="Semanas del curso">{available.map((w,i)=><a key={w.id} href={'#'+w.id}>Semana {i+1}</a>)}{all.some(i=>i.id===volatileLabId)&&<a href={'#'+volatileLabId}>Taller final GC-MS · Python</a>}</nav></>}
 {available.map(w=>{const stored=all.find(i=>i.id===w.id)!;const topics=all.filter(i=>i.parent===w.id&&i.kind==='topic').sort((a,b)=>a.position-b.position);return <article className="volatile-week" key={w.id}><header><span className="eyebrow">{w.modules}</span><h3><a href={'#'+w.id}>{stored.title}</a></h3><p><strong>Resultado esperado:</strong> {stored.objectives||w.outcome}</p></header><TopicPresentations topic={w.id} title={stored.title} weekly/><div className="volatile-topic-list">{topics.map(topic=>{const planned=w.topics.find((_,i)=>topicId(w.id,i)===topic.id);return <div key={topic.id}><a className="volatile-topic" href={'#'+topic.id}><strong>{topic.title}</strong><span>Abrir tema · Presentaciones, videos y materiales →</span></a><p>{topic.description}</p>{planned&&<details><summary>Lecturas para este tema ({planned.refs.length})</summary><VolatileReadingList ids={planned.refs}/></details>}</div>})}</div><div className="notice"><strong>Trabajo de la semana:</strong> {stored.body||w.activity}</div><details><summary>Bibliografía reunida de la semana</summary><VolatileReadingList ids={w.topics.flatMap(t=>t.refs)}/></details></article>})}
 {!weekId&&<>{all.some(i=>i.id===volatileLabId)&&<section className="volatile-final"><span className="eyebrow">AL FINAL DEL CURSO</span><h2>Procesamiento de datos GC-MS con Python</h2><p>Guía práctica, archivos de código y criterios para documentar el procesamiento.</p><a className="button" href={'#'+volatileLabId}>Abrir taller y materiales del docente →</a><Suspense fallback={<p>Cargando taller…</p>}><GcmsPythonLab/></Suspense></section>}{legacy.length>0&&<details><summary>Material complementario del plan anterior</summary><p>Se conservan los temas, enlaces y materiales publicados antes de esta organización semanal.</p>{legacy.map(u=><p key={u.id}><a href={'#'+u.id}>{u.title} →</a></p>)}</details>}</>}
 </section>;
}
export function VolatilomicsBibliography({all}:{all:Item[]}){return <section><h2>Bibliografía por semana y tema</h2><p>Lecturas con propósito definido. Los recursos en español se señalan; la literatura especializada conserva su idioma original.</p>{volatileWeeks.filter(w=>all.some(i=>i.id===w.id)).map((w,i)=><details key={w.id}><summary>Semana {i+1} · {w.title}</summary>{w.topics.map(t=><section key={t.title}><h3>{t.title}</h3><VolatileReadingList ids={t.refs}/></section>)}</details>)}</section>}
