'use client';
import {useEffect,useState} from 'react';
type Student={id:string;email:string;name:string;institution:string;requested:string;approved:string;status:string;created:string};
type Course={id:string;title:string};
const labels:Record<string,string>={pending:'Pendiente',approved:'Aprobada',rejected:'Rechazada',suspended:'Suspendida'};
export default function Students(){const [rows,setRows]=useState<Student[]>([]),[courses,setCourses]=useState<Course[]>([]),[status,setStatus]=useState(''),[query,setQuery]=useState(''),[page,setPage]=useState(0),[total,setTotal]=useState(0),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[selected,setSelected]=useState<Student|null>(null);
 async function load(){setLoading(true);try{const r=await fetch('/api/students?'+new URLSearchParams({status,q:query,page:String(page)}),{cache:'no-store'});const d=await r.json() as {error?:string;students:Student[];courses:Course[];total:number};if(!r.ok)throw Error(d.error);setRows(d.students);setCourses(d.courses);setTotal(d.total);}catch(e){setMessage(e instanceof Error?e.message:'No se pudo cargar.');}finally{setLoading(false);}}
 useEffect(()=>{load();},[status,page]);
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!selected)return;setBusy(true);setMessage('');const fd=new FormData(e.currentTarget);try{const r=await fetch('/api/students',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:selected.id,status:fd.get('status'),courses:fd.getAll('courses')})});const d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error);setSelected(null);setMessage('Permisos actualizados. El cambio se aplica en la siguiente consulta del estudiante.');await load();}catch(e){setMessage(e instanceof Error?e.message:'No se guardó.');}finally{setBusy(false);}}
 return <main className="wrap student-admin"><nav><a href="/admin">← Contenidos</a><a href="/acceso">Mi cuenta</a></nav><span className="eyebrow">SOLO DOCENTE</span><h1>Estudiantes y solicitudes</h1><p>Aprueba únicamente los cursos que recibe cada estudiante. Suspender bloquea el acceso a los contenidos y archivos.</p><form className="filters" onSubmit={e=>{e.preventDefault();if(page)setPage(0);else load();}}><label>Buscar por nombre o correo<input value={query} onChange={e=>setQuery(e.target.value)} maxLength={150}/></label><label>Estado<select value={status} onChange={e=>{setStatus(e.target.value);setPage(0);}}><option value="">Todos</option>{Object.entries(labels).map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label><button className="button" disabled={loading}>Buscar</button></form><p role="status">{message}</p><p>{total} solicitudes · Página {page+1}</p>{loading?<p>Cargando estudiantes…</p>:!rows.length?<div className="empty-state">Todavía no hay solicitudes que coincidan.</div>:<div className="student-list">{rows.map(s=><article key={s.id}><div><h2>{s.name}</h2><p>{s.email}</p><p>{s.institution}</p><p>Solicitud: {new Date(s.created).toLocaleDateString('es-CO')}</p><strong>{labels[s.status]}</strong></div><div><p>Cursos solicitados:</p><ul>{courses.filter(c=>JSON.parse(s.requested).includes(c.id)).map(c=><li key={c.id}>{c.title}</li>)}</ul><button className="button secondary" onClick={()=>setSelected(s)}>Revisar matrícula</button></div></article>)}</div>}<div className="student-pagination"><button disabled={page===0||loading} onClick={()=>setPage(page-1)}>Anterior</button><button disabled={(page+1)*50>=total||loading} onClick={()=>setPage(page+1)}>Siguiente</button></div>{selected&&<section className="student-editor" aria-label="Revisión de matrícula"><h2>Revisar: {selected.name}</h2><form key={selected.id} onSubmit={save}><label>Estado<select name="status" defaultValue={selected.status}>{Object.entries(labels).map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label><fieldset><legend>Cursos autorizados por el docente</legend>{courses.map(c=><label className="access-check" key={selected.id+c.id}><input name="courses" type="checkbox" value={c.id} defaultChecked={JSON.parse(selected.approved).includes(c.id)}/>{c.title}</label>)}</fieldset><p className="muted">Seleccionar cursos no aprueba la matrícula: también debes elegir el estado Aprobada.</p><button className="button" disabled={busy}>{busy?'Guardando…':'Guardar permisos'}</button><button className="button secondary" type="button" disabled={busy} onClick={()=>setSelected(null)}>Cancelar</button></form></section>}</main>;
}
