export const academicBooks = [
 {id:'general', title:'Chemistry 2e', authors:'Paul Flowers, Klaus Theopold, Richard Langley y William R. Robinson', url:'https://openstax.org/details/books/chemistry-2e', access:'Lectura y PDF gratuitos desde OpenStax', scope:'Materia, estructura, estequiometría, soluciones, equilibrio, termodinámica y electroquímica.', branches:['rama-0']},
 {id:'inorganica', title:'Inorganic Chemistry, 8.ª edición', authors:'Mark Weller y colaboradores', url:'https://learninglink.oup.com/access/weller8e', access:'Recursos oficiales; libro mediante compra o biblioteca', scope:'Estructura electrónica, enlace, simetría, coordinación y reactividad inorgánica.', branches:['rama-1']},
 {id:'organica', title:'Organic Chemistry: A Tenth Edition', authors:'John McMurry', url:'https://openstax.org/details/books/organic-chemistry', access:'Lectura y PDF gratuitos desde OpenStax', scope:'Estructura, estereoquímica, mecanismos, grupos funcionales y elucidación espectroscópica.', branches:['rama-2']},
 {id:'analitica', title:'Analytical Chemistry 2.1', authors:'David Harvey', url:'https://sites.google.com/depauw.edu/dth/analytical-curriculum-projects/ac2-1', access:'Texto y PDF gratuitos ofrecidos por el autor', scope:'Medición, estadística, equilibrios, métodos clásicos, instrumentales y separaciones.', branches:['rama-3']},
 {id:'fisica', title:'Atkins’ Physical Chemistry, 12.ª edición', authors:'Peter Atkins, Julio de Paula y James Keeler', url:'https://www.oup.com.au/books/higher-education/chemistry/9780198847816', access:'Ficha editorial; compra o acceso institucional', scope:'Termodinámica, equilibrio, estructura cuántica, espectroscopía, cinética y superficies.', branches:['rama-4']},
 {id:'bioquimica', title:'Lehninger Principles of Biochemistry, 8.ª edición', authors:'David L. Nelson, Michael M. Cox y Aaron A. Hoskins', url:'https://www.macmillanlearning.com/college/us/product/Lehninger-Principles-of-Biochemistry/p/1319228003', access:'Ficha editorial; compra o acceso institucional', scope:'Biomoléculas, enzimas, bioenergética, metabolismo y regulación.', branches:['rama-5']},
 {id:'ambiental', title:'Environmental Organic Chemistry, 3.ª edición', authors:'René P. Schwarzenbach, Philip M. Gschwend y Dieter M. Imboden', url:'https://bcs.wiley.com/he-bcs/Books?action=index&bcsId=10535&itemId=1118767233', access:'Sitio oficial complementario; libro mediante compra o biblioteca', scope:'Partición, transporte, transformación y destino de sustancias orgánicas en el ambiente. Complementar con química de agua, atmósfera y metales.', branches:['rama-6']},
 {id:'quimiometria', title:'Chemometrics: Data Analysis for the Laboratory and Chemical Plant', authors:'Richard G. Brereton', url:'https://onlinelibrary.wiley.com/doi/book/10.1002/0470863242', access:'Ficha editorial y capítulos según licencia institucional', scope:'Diseño experimental, calibración y análisis de datos químicos multivariados.', branches:['sub-quimiometria']},
 {id:'metabolomica', title:'Metabolomics: Methods and Protocols', authors:'Wolfram Weckwerth (editor)', url:'https://link.springer.com/book/10.1007/978-1-59745-244-1', access:'Ficha editorial y capítulos según licencia institucional', scope:'Referencia metodológica fundacional; complementar con literatura reciente sobre control de calidad, identificación, validación y reproducibilidad.', branches:['sub-metabolomica']},
 {id:'volatilomica', title:'Volatile Biomarkers: Non-Invasive Diagnosis in Physiology and Medicine', authors:'Anton Amann y David Smith (editores)', url:'https://www.sciencedirect.com/book/9780444626134/volatile-biomarkers', access:'Ficha editorial y capítulos según licencia institucional', scope:'Muestreo y análisis de volátiles biológicos. Referencia fundacional, complementada con métodos recientes y aplicaciones ambientales y alimentarias.', branches:['sub-volatilomica']},
];
