import type {Item} from './content';
type Lesson=[string,string,string,string];
type Branch={id:string;name:string;scope:string;prior:string;project:string;source:string;lessons:Lesson[]};
const branches:Branch[]=[
{id:'rama-0',name:'Química general',scope:'Relaciona composición, estructura y propiedades de la materia. Integra observaciones macroscópicas, modelos de partículas y representaciones simbólicas para resolver problemas de transformación y cantidad. Es la base de las asignaturas de química del pregrado.',prior:'Álgebra, proporciones, notación científica, unidades y lectura de gráficas.',project:'Comparar dos soluciones mediante balances de masa, concentración y propiedades. Presentar cálculos con unidades, supuestos y explicación molecular.',source:'https://openstax.org/books/chemistry-2e/pages/1-introduction',lessons:[
['Materia, átomo y periodicidad','Un elemento se identifica por su número de protones; sus isótopos difieren en neutrones y sus iones en electrones. La configuración electrónica permite interpretar tendencias de tamaño e ionización, con excepciones que requieren examinar la estructura. La masa atómica tabulada es un promedio isotópico.\n\nDistingue sustancia pura, mezcla y fase. Un cambio de estado conserva la identidad química; una reacción reorganiza los átomos en especies nuevas.','²³Na⁺ tiene 11 protones, 23 − 11 = 12 neutrones y 11 − 1 = 10 electrones. La carga positiva indica pérdida de electrones.','Construye una tabla para ³⁵Cl⁻, ²⁴Mg²⁺ y ¹⁶O. Explica tendencias de Na y Cl mediante capas y carga nuclear efectiva.'],
['Enlace, geometría e interacciones','Lewis contabiliza electrones de valencia; la geometría molecular describe la disposición espacial de los átomos. Los pares libres modifican esa geometría. Deben evaluarse juntos los dipolos de enlace y la geometría para decidir la polaridad molecular.\n\nLas interacciones intermoleculares ayudan a explicar ebullición, solubilidad y viscosidad. No son los enlaces que mantienen unidos los átomos dentro de cada molécula.','CO₂ tiene enlaces polares pero es lineal y sus dipolos se cancelan. H₂O es angular y posee dipolo neto. Hervir agua vence interacciones entre moléculas; no rompe normalmente sus enlaces O–H.','Dibuja Lewis y geometría de NH₃ y CH₄. Justifica por qué contar enlaces polares no basta para predecir el dipolo total.'],
['Estequiometría y soluciones','Una ecuación balanceada conserva átomos y expresa relaciones entre moles. El reactivo limitante se determina comparando moles divididos por sus coeficientes. El rendimiento experimental se compara con la cantidad teórica, no con la masa inicial de cualquier reactivo.\n\nLa molaridad c = n/V utiliza volumen final de solución. En una dilución sin reacción ni pérdida, c₁V₁ = c₂V₂.','En 2H₂ + O₂ → 2H₂O, con 3 mol H₂ y 2 mol O₂: 3/2 < 2/1, limita H₂ y se forman 3 mol H₂O. Diluir 10,0 mL de 0,500 mol/L hasta 100,0 mL da 0,0500 mol/L.','Repite el balance con 4 mol H₂ y 1 mol O₂. Explica por qué añadir 100 mL de agua no equivale a preparar 100 mL de solución.'],
['Equilibrio, energía y velocidad','En equilibrio las velocidades directa e inversa son iguales; las concentraciones son constantes, no necesariamente iguales. Comparar Q con K permite predecir el sentido de evolución desde una composición.\n\nLa termodinámica describe dirección y equilibrio bajo condiciones definidas. La cinética estudia velocidad: una reacción favorable puede ser lenta. Un catalizador acelera la aproximación al equilibrio sin cambiar K a temperatura fija.','Si Q = 0,2 y K = 5, se favorece la formación neta de productos en el sentido escrito. Estos números no indican cuánto tarda el proceso.','Compara los efectos de cambiar temperatura, composición y cantidad de catalizador. Explica qué medición distingue equilibrio de un proceso detenido por lentitud.']
]},
{id:'rama-1',name:'Química inorgánica',scope:'Estudia estructura, enlace y reactividad de elementos, sólidos y complejos metálicos. Relaciona periodicidad y estructura electrónica con propiedades ópticas, magnéticas y catalíticas, incluyendo materiales y sistemas bioinorgánicos.',prior:'Configuración electrónica, enlace, equilibrio y oxidación-reducción.',project:'Comparar dos complejos de un metal: ligandos, geometría, oxidación, propiedades y evidencia necesaria para comprobar la estructura.',source:'https://openstax.org/books/chemistry-2e/pages/19-introduction',lessons:[
['Periodicidad y estados de oxidación','El estudio de bloques s, p, d y f utiliza tendencias periódicas sin convertirlas en reglas absolutas. El estado de oxidación es una asignación formal para balances y nomenclatura; no representa siempre la carga física de un átomo.\n\nLa estabilidad de un estado depende de ligandos y condiciones. Acidez, polarización y coordinación permiten comparar óxidos, hidróxidos y otras familias inorgánicas.','En MnO₄⁻: x + 4(−2) = −1, por tanto Mn es +7. En MnO₂ es +4. Son cuentas electrónicas formales.','Asigna oxidación en NH₄⁺, Cr₂O₇²⁻ y Fe₃O₄. Explica por qué un valor promedio no implica átomos equivalentes.'],
['Coordinación y campo de ligandos','Un ligando dona un par electrónico al centro metálico en la descripción de Lewis. Denticidad cuenta donadores de un ligando; número de coordinación cuenta átomos coordinados al metal.\n\nLa geometría y los ligandos modifican el desdoblamiento de orbitales d. Campo cristalino y campo de ligandos son modelos de distinta complejidad que permiten interpretar color y magnetismo.','En [Co(NH₃)₆]³⁺, NH₃ es neutro: Co es +3, coordinación 6 y cuenta formal d⁶. Para distribuir esos electrones se necesita conocer desdoblamiento y energía de apareamiento.','Compara tres ligandos bidentados con seis monodentados. Indica qué evidencia magnética ayudaría a evaluar la ocupación electrónica.'],
['Sólidos, redes y materiales','La celda unidad describe repetición espacial. Coordinación, empaquetamiento y defectos afectan densidad, difusión y propiedades mecánicas. Los sólidos reales no son redes perfectas e infinitas.\n\nLa conducción se interpreta mediante estructura electrónica y bandas. Una clasificación de enlaces no basta para predecir todas las propiedades eléctricas de un material.','Una celda cúbica centrada en las caras monoatómica contiene 8×1/8 + 6×1/2 = 4 átomos. Los átomos compartidos no se cuentan completos.','Calcula los átomos de una celda centrada en el cuerpo. Propón cómo las vacancias influyen en la difusión.'],
['Reactividad y catálisis metálica','Sustitución de ligandos y transferencia electrónica son procesos centrales. Estabilidad termodinámica y rapidez de intercambio son propiedades distintas: estable no significa necesariamente inerte.\n\nUn ciclo catalítico regenera la especie activa. En sistemas biológicos, la coordinación permite transporte, transferencia electrónica o activación de sustratos.','Si se forman 0,020 mol de producto con 0,00010 mol de centros catalíticos, TON = 200. Este cociente no informa por sí solo sobre velocidad o selectividad.','Dibuja unión, transformación y liberación de un sustrato en un ciclo conceptual. Distingue desactivación del catalizador y agotamiento del reactivo.']
]},
{id:'rama-2',name:'Química orgánica',scope:'Relaciona estructura de compuestos de carbono con propiedades, mecanismos y síntesis. Incluye estereoquímica, transformaciones de grupos funcionales y evidencia espectroscópica, con aplicaciones en materiales, productos naturales y biomoléculas.',prior:'Enlace, geometría molecular, equilibrio ácido-base y energía.',project:'Proponer documentalmente una transformación, justificar su mecanismo y comparar rutas según selectividad, etapas y residuos.',source:'https://openstax.org/books/organic-chemistry/pages/1-why-this-chapter',lessons:[
['Estructura, resonancia y acidez','Las fórmulas esqueléticas simplifican la representación sin eliminar la necesidad de contar valencias. Las formas de resonancia describen una misma especie; no son moléculas en equilibrio. La deslocalización puede estabilizar cargas.\n\nLa acidez depende de la estabilidad relativa de la base conjugada y del medio. Comparar pKₐ requiere considerar disolvente y escala, no aplicar aisladamente una regla de electronegatividad.','En el acetato, la carga se distribuye entre dos oxígenos equivalentes en su representación por resonancia. Esto contribuye a explicar la mayor acidez del ácido acético frente a un alcohol simple.','Dibuja las formas resonantes del acetato conservando posiciones nucleares y carga. Explica por qué mover un H no produce otra forma resonante.'],
['Estereoquímica y conformaciones','Los isómeros constitucionales difieren en conectividad; los estereoisómeros, en disposición espacial. Un carbono tetraédrico con cuatro sustituyentes diferentes puede ser estereogénico; debe revisarse también la simetría global.\n\nR/S no determina el signo de rotación óptica. Las conformaciones se interconvierten por rotación y pueden tener energías distintas sin cambiar la conectividad.','Para un carbono unido a Br, Cl, F y H, las prioridades empiezan Br > Cl > F > H. Sin orientación espacial no puede asignarse R o S.','Dibuja conformaciones alternada y eclipsada del etano y su energía relativa. Explica cuándo una fórmula plana resulta insuficiente.'],
['Mecanismos de sustitución y eliminación','Las flechas curvas parten de electrones y terminan donde estos se redistribuyen. Nucleofilia y basicidad describen comportamiento cinético y de equilibrio, respectivamente.\n\nSustrato, disolvente, base, nucleófilo y temperatura controlan la competencia entre mecanismos. SN2 es concertada; SN1 incluye un carbocatión en su modelo idealizado. No debe asignarse mecanismo solo por el nombre de un reactivo.','En el modelo SN2, v = k[sustrato][nucleófilo]. Duplicar ambas concentraciones cuadruplica v a temperatura fija. Esto es compatible con la ley ideal, pero no demuestra por sí solo el mecanismo.','Compara SN1 y SN2 mediante cinética, estereoquímica y reorganizaciones. Argumenta el efecto del impedimento estérico.'],
['Grupos funcionales y elucidación','Alcoholes, carbonilos, ácidos y aminas tienen reactividad asociada a distribución electrónica y grupos salientes. La síntesis combina transformaciones manteniendo seguimiento de átomos y selectividad.\n\nIR, RMN y espectrometría de masas aportan evidencia complementaria. Una estructura debe explicar fórmula, señales e integraciones; un pico aislado rara vez identifica inequívocamente una molécula.','Para C₃H₆O, insaturación = (2×3 + 2 − 6)/2 = 1. Puede ser anillo o doble enlace. La fórmula no distingue propanal de propanona.','Propón señales de RMN de ¹H que distingan propanal y propanona. Explica por qué compartir masa molecular no implica igual estructura.']
]},
{id:'rama-3',name:'Química analítica',scope:'Convierte una pregunta de composición en una medición defendible. Integra muestreo, preparación, métodos clásicos e instrumentales, calibración e incertidumbre. La calidad comienza antes de introducir la muestra en el instrumento.',prior:'Estequiometría, equilibrios, unidades y estadística descriptiva.',project:'Diseñar un plan de determinación con muestreo, blancos, calibración, recuperaciones y criterios de aceptación justificados.',source:'https://scholarship.depauw.edu/chem_facpubs/8/',lessons:[
['Muestreo, precisión y sesgo','Definir analito, matriz, finalidad e intervalo esperado permite elegir el procedimiento. Repetir lecturas de una misma solución no reproduce el muestreo.\n\nPrecisión describe dispersión bajo condiciones especificadas; sesgo, desviación sistemática respecto de una referencia. Blancos, materiales de referencia y fortificaciones responden preguntas diferentes y deben planearse antes de medir.','9,98; 10,00 y 10,02 mg/L son poco dispersos. Si el valor de referencia es 12,00 mg/L, su promedio presenta sesgo de −2,00 mg/L. Buena precisión no garantiza concordancia.','Distingue réplicas de campo, preparación y lectura en un plan de muestreo de agua de tres puntos.'],
['Valoraciones y equilibrios','Una valoración relaciona analito y reactivo mediante una estequiometría. Equivalencia es una condición química; punto final, una señal experimental. Su diferencia puede introducir error.\n\nValoraciones ácido-base, redox, de precipitación y complejométricas requieren considerar constantes, interferencias y medio. El titulante debe tener una concentración conocida y adecuadamente establecida.','25,00 mL de ácido monoprótico consumen 20,00 mL de NaOH 0,1000 mol/L. n = 0,002000 mol y c del ácido = 0,002000/0,02500 = 0,08000 mol/L, suponiendo reacción completa sin interferentes.','Repite para un ácido diprótico totalmente neutralizado. Identifica el punto de equivalencia que utiliza tu cálculo.'],
['Calibración y selección instrumental','La calibración relaciona respuesta y cantidad bajo condiciones definidas. Deben examinarse residuos, intervalo y efecto de matriz; un R² alto no basta.\n\nEspectroscopía, electroquímica y separaciones responden a principios diferentes. La selección considera analito, matriz, desempeño requerido y recursos, no únicamente sensibilidad nominal.','Para A = 0,020 + 0,150c, con c en mg/L, A = 0,620 da c = 4,00 mg/L. Una dilución previa de factor 5 implica 20,0 mg/L en la muestra original.','Resuelve A = 0,320 y dilución de factor 2. Explica qué hacer si la respuesta está fuera del rango calibrado.'],
['Validación e incertidumbre','Validar significa demostrar adecuación al uso previsto. Se estudian selectividad, rango, precisión, sesgo, recuperación y límites según corresponda. Detectar no implica poder cuantificar con desempeño aceptable.\n\nLa incertidumbre reúne contribuciones del procedimiento. El informe conserva unidades, diluciones, controles y condiciones; ausencia de señal no prueba ausencia absoluta.','Una muestra de 2,0 mg/L fortificada con 5,0 mg/L adicionales da 6,5 mg/L. Recuperación = (6,5 − 2,0)/5,0 × 100 = 90 %. La aceptación depende del propósito y criterios previos.','Enumera contribuciones de balanza, volumen, calibración y repetibilidad. Diseña una tabla de datos crudos, controles y resultado final.']
]},
{id:'rama-4',name:'Fisicoquímica',scope:'Construye modelos cuantitativos de energía, equilibrio, velocidad y estructura molecular. Conecta termodinámica, cuántica y espectroscopía con observaciones y reconoce los límites de cada aproximación.',prior:'Química general, álgebra, logaritmos, derivadas, integrales y física básica.',project:'Comparar modelos cinéticos con datos simulados y residuos. Explicar por qué el mejor ajuste no demuestra un mecanismo único.',source:'https://openstax.org/books/chemistry-2e/pages/16-introduction',lessons:[
['Termodinámica y potenciales','La energía interna es función de estado; calor y trabajo son transferencias dependientes de trayectoria. Con convención química, ΔU = q + w. Las condiciones de expansión deben especificarse.\n\nA temperatura y presión constantes, ΔG permite evaluar dirección termodinámica. Espontaneidad no significa rapidez ni ausencia de barrera de activación.','A 298 K, con ΔH = −40,0 kJ/mol y ΔS = −0,100 kJ/(mol·K), ΔG = −40,0 + 29,8 = −10,2 kJ/mol. Es imprescindible compatibilizar unidades.','Calcula ΔG a 500 K suponiendo ΔH y ΔS constantes. Discute cuándo esa aproximación deja de ser razonable.'],
['Potencial químico y equilibrio','El potencial químico describe cómo cambia Gibbs con la cantidad de un componente. En equilibrio entre fases, el potencial de cada componente que intercambia materia es igual en ambas.\n\nLas constantes termodinámicas utilizan actividades adimensionales. Reemplazarlas por concentraciones o presiones reducidas exige declarar estado estándar y aproximación de idealidad.','Con K = 10 a 298 K, ΔG° = −RT ln K ≈ −5,70 kJ/mol. Se usa logaritmo natural y K adimensional.','Distingue ΔG y ΔG°. Explica por qué una solución concentrada puede requerir coeficientes de actividad.'],
['Cinética y mecanismos','La ley de velocidad es experimental; sus exponentes no se deducen automáticamente de la reacción global. Para primer orden, ln(c/c₀) = −kt y t₁/₂ = ln2/k.\n\nEl ajuste necesita evaluar residuos y condiciones. Preequilibrio y estado estacionario son aproximaciones distintas; su uso exige justificar escalas de tiempo o concentraciones.','Con k = 0,0200 min⁻¹, t₁/₂ = 34,7 min. A 50,0 min, c/c₀ = exp(−1) = 0,368. Las unidades de k cambian con el orden.','Compara semividas sucesivas de primer y segundo orden. Explica por qué una recta transformada no basta para demostrar mecanismo.'],
['Cuántica y espectroscopía','La descripción cuántica relaciona estados con funciones de onda y observables con operadores. El cuadrado del módulo de la función de onda se relaciona con probabilidad, no con trayectoria clásica.\n\nAbsorber radiación requiere diferencia energética compatible y transición permitida. Partícula en caja, rotor y oscilador son modelos útiles con límites moleculares concretos.','Un fotón de 500 nm tiene E = hc/λ ≈ 3,97×10⁻¹⁹ J, o aproximadamente 239 kJ por mol de fotones. Menor longitud de onda implica mayor energía.','Compara 400 y 800 nm. Explica por qué una diferencia energética no garantiza una transición intensa.']
]},
{id:'rama-5',name:'Bioquímica',scope:'Explica organización y transformación de la materia en sistemas vivos. Relaciona biomoléculas, enzimas, membranas y regulación con bioenergética y metabolismo, preparando la interpretación de ensayos y datos biológicos.',prior:'Química general, grupos funcionales, equilibrio ácido-base y biología celular.',project:'Mapear una ruta central con compartimentos, balances y regulación. Proponer un ensayo con controles para contrastar una hipótesis.',source:'https://www.ncbi.nlm.nih.gov/books/NBK26911/',lessons:[
['Agua, amortiguadores y biomoléculas','Ionización, pH y pKₐ modifican interacciones, solubilidad y actividad. Proteínas, lípidos, carbohidratos y ácidos nucleicos tienen funciones dependientes de estructura y organización.\n\nUn amortiguador resiste cambios de pH dentro de un intervalo y capacidad finitos. Tener el pH adecuado no demuestra suficiente capacidad amortiguadora.','Para pKₐ = 6,8 y [A⁻] = [HA], Henderson–Hasselbalch da pH ≈ 6,8. La concentración total influye en capacidad, aunque la relación base/ácido sea igual.','Compara amortiguadores de 1 y 100 mmol/L con igual relación base/ácido. Explica por qué no responden igual a una adición de ácido.'],
['Enzimas y regulación','Una enzima acelera una reacción sin cambiar su equilibrio termodinámico. Michaelis–Menten representa mecanismos y condiciones concretas, no todas las enzimas.\n\nKₘ corresponde a la concentración que produce mitad de Vmáx dentro del modelo; interpretarlo como afinidad requiere supuestos adicionales. Cooperatividad e inhibición pueden necesitar modelos diferentes.','Si Vmáx = 100 µmol/min y Kₘ = 2 mmol/L, a [S] = 2 mmol/L la velocidad es 50 µmol/min; a 8 mmol/L es 80 µmol/min.','Grafica v frente a sustrato. Explica por qué duplicar sustrato no duplica siempre velocidad y diseña un blanco sin enzima.'],
['Bioenergética y metabolismo central','Catabolismo y anabolismo intercambian intermediarios, energía y equivalentes reductores. Glucólisis, ciclo de ácidos tricarboxílicos y cadena respiratoria cumplen funciones distintas y conectadas.\n\nLa integración depende de organismo y compartimento. Mayor concentración de un metabolito puede reflejar mayor producción o menor consumo; no demuestra mayor flujo de una ruta.','Glucólisis clásica: una glucosa produce dos piruvatos, 2 ATP netos y 2 NADH. No es el rendimiento total de oxidar glucosa e incluye solo esta ruta.','Sigue los seis carbonos hasta piruvato. Explica la necesidad de regenerar NAD⁺ y diferencia fermentación de respiración.'],
['Membranas y ensayos bioquímicos','Las membranas delimitan compartimentos y gradientes mediante lípidos y proteínas. El gradiente electroquímico combina concentración y potencial; el transporte puede ser pasivo o acoplado a energía.\n\nAbundancia de ARN, proteína y actividad no son equivalentes. Los ensayos requieren controles y normalización que respondan a una pregunta concreta.','Señal de muestra 0,80 menos blanco 0,10 produce 0,70. Si otra muestra contiene doble proteína total, comparar señales crudas no demuestra mayor actividad específica.','Define controles positivo, negativo y de matriz. Indica cómo expresarías actividad total y por unidad de proteína.']
]},
{id:'rama-6',name:'Química ambiental',scope:'Estudia composición y transformaciones en agua, aire, suelo y sedimentos. Integra especiación, transporte, degradación y medición para interpretar contaminación y evaluar prevención y tratamiento.',prior:'Equilibrios, redox, química orgánica básica, balances y estadística elemental.',project:'Construir un balance entre agua, suelo y aire. Proponer monitoreo y comparar prevención y tratamiento incluyendo subproductos y consumo de recursos.',source:'https://www.epa.gov/greenchemistry/basics-green-chemistry',lessons:[
['Agua, pH y especiación','La concentración total suma especies con comportamientos diferentes. pH, potencial redox y ligandos modifican distribución y movilidad. Deben respetarse balances de masa y carga junto con equilibrios.\n\nLa alcalinidad expresa capacidad de neutralización de ácido bajo una definición operacional; no equivale a pH. Aguas de igual pH pueden responder de forma distinta a una entrada ácida.','Para HA con pKₐ = 5 y pH = 6, [A⁻]/[HA] ≈ 10. En el modelo de dos especies, fracción A⁻ = 10/11 ≈ 0,909. El cambio de proporción no requiere cambiar concentración total.','Calcula fracciones a pH 4 y 5. Explica por qué variar pH puede modificar movilidad sin agregar contaminante.'],
['Atmósfera y fotoquímica','Las especies primarias se emiten; las secundarias se forman por reacción. Radiación, radicales, humedad y transporte condicionan la evolución atmosférica.\n\nOzono estratosférico y troposférico son la misma molécula en contextos diferentes. Efecto invernadero, pérdida de ozono y smog requieren mecanismos específicos y no son procesos intercambiables.','En decaimiento de primer orden con k = 0,10 h⁻¹, tiempo característico 1/k = 10 h y semivida ln2/k = 6,93 h. Ambos cálculos suponen ausencia de fuentes adicionales.','Esquematiza emisión, transformación y transporte de un contaminante secundario. Explica por qué concentración local no depende solo de emisión local.'],
['Suelo, partición y destino','Sorción redistribuye sustancias entre fases y puede retardar transporte. Los coeficientes dependen del medio y las condiciones; no se transfieren entre sistemas sin evaluar validez.\n\nDisminuir una concentración en agua puede reflejar sorción, volatilización o transformación. Solo la última cambia identidad, y no toda transformación implica mineralización o menor peligrosidad.','Csuelo = 10 mg/kg y Cagua = 2 mg/L dan Kd = 5 L/kg para esas condiciones. No demuestra degradación ni representa una constante universal del compuesto.','Construye un balance de entrada, salida, almacenamiento y transformación. Propón muestreos si baja concentración acuosa y aumenta en sedimento.'],
['Monitoreo y prevención','El monitoreo define pregunta, variación temporal, puntos, preservación y controles. Evaluar una intervención requiere comparar cantidades y condiciones, no únicamente porcentajes.\n\nLa química verde considera prevención desde el diseño. Seleccionar tratamiento exige valorar energía, reactivos, residuos y subproductos además de remover el compuesto original.','Pasar de 100 a 20 mg/L significa 80 % de remoción aparente. A 2 L/s constantes, la carga baja de 200 a 40 mg/s. Falta establecer destino de los 160 mg/s restantes.','Compara adsorción y degradación con balances. Propón indicadores de energía, residuos y efluente; no deduzcas potabilidad de un único analito.']
]},
{id:'sub-quimiometria',name:'Quimiometría',scope:'Diseña experimentos y extrae información de mediciones químicas con estadística y modelos multivariados. Relaciona pregunta química, estructura de datos, incertidumbre y validación, distinguiendo ajuste de capacidad predictiva.',prior:'Estadística descriptiva, matrices básicas, química analítica y datos tabulares.',project:'Organizar una matriz didáctica, documentar preprocesamiento, explorar PCA y evaluar predicción con muestras independientes y un flujo reproducible.',source:'https://www.itl.nist.gov/div898/handbook/pri/pri.htm',lessons:[
['Datos y preprocesamiento','Una matriz suele organizar muestras en filas y variables en columnas, con metadatos de lote, grupo y sujeto. No detectado no equivale automáticamente a cero. Las transformaciones deben corresponder a escala y origen de los datos.\n\nCentrar resta medias y escalar divide por dispersión. Para predicción, imputación, medias y escalas se aprenden en entrenamiento y se aplican sin reajuste a evaluación.','Media de entrenamiento 10, desviación 2 y valor 14 dan z = (14 − 10)/2 = 2. No se recalculan esos parámetros con el conjunto de prueba.','Crea un diccionario de variables y unidades. Explica cómo tratar una variable constante antes de autoescalar.'],
['Diseño experimental','Aleatorización reparte perturbaciones no controladas; bloqueo representa fuentes conocidas de variación. Repetir lecturas no crea unidades experimentales independientes.\n\nUn factorial estudia factores conjuntamente y permite estimar interacción: el efecto de uno depende del nivel de otro. Cambiar un factor cada vez puede omitir esa relación.','Dos factores a dos niveles dan 2² = 4 combinaciones. Tres réplicas independientes dan 12 unidades. Tres lecturas por unidad dan 36 lecturas, pero siguen siendo 12 unidades.','Diseña un estudio conceptual de extracción con tiempo y temperatura. Define respuesta, unidades, aleatorización y bloqueo por día.'],
['PCA y exploración multivariada','PCA encuentra direcciones ortogonales que resumen variación de la matriz preprocesada. Puntuaciones describen muestras; cargas relacionan variables con componentes. Escalar cambia qué variación domina.\n\nUna separación visual no demuestra causalidad o predicción. El agrupamiento depende de distancia y algoritmo. Deben investigarse lotes, atípicos y estabilidad.','Varianzas de componentes 4, 2, 1 y 1 suman 8: PC1 explica 50 % y PC1+PC2 explican 75 %. El 25 % restante puede contener información relevante.','Compara puntuaciones coloreadas por grupo y por lote. Explica por qué una separación coincidente con lote puede indicar confusión.'],
['Modelos y validación','Regresión y clasificación tienen objetivos distintos. PLS aprovecha variables correlacionadas, pero su complejidad requiere validación. Ningún algoritmo elimina por sí solo sesgo de muestreo.\n\nLas particiones deben respetar independencia de sujetos o lotes. Selección de variables e hiperparámetros quedan dentro de entrenamiento; se reserva la prueba externa para evaluación final.','Errores 1, −1, 2 y −2 mg/L producen RMSE = √[(1+1+4+4)/4] ≈ 1,58 mg/L. Debe acompañarse de rango, sesgo y procedencia de muestras.','Dibuja entrenamiento, ajuste interno y evaluación reservada. Ubica imputación, escalado y selección y explica por qué no se ajustan sobre todos los datos.']
]}
];
export const branchLearningContent:Item[]=[];
for(const b of branches){
 const course='ampliacion-'+b.id, common={status:'published',example:true};
 branchLearningContent.push({id:course,kind:'course',title:'Fundamentos y aplicaciones · '+b.name,parent:b.id,position:-1,...common,description:b.scope,objectives:'Explicar los modelos de las cuatro unidades. Resolver e interpretar cálculos con unidades y supuestos. Relacionar los conceptos con aplicaciones y reconocer límites de la evidencia.',body:'Conocimientos previos\n'+b.prior+'\n\nRuta de estudio\nCuatro unidades con explicación, ejemplo resuelto y actividad. Propuesta editable de pregrado; no sustituye el plan institucional.\n\nProyecto integrador\n'+b.project});
 b.lessons.forEach(([title,body,examples,activities],n)=>{
 const unit=course+'-u'+(n+1),topic=unit+'-tema';
 branchLearningContent.push({id:unit,kind:'unit',title:'Unidad '+(n+1)+' · '+title,parent:course,position:n,...common,description:'Comprende el modelo, revisa el ejemplo y argumenta su aplicación.'});
 branchLearningContent.push({id:topic,kind:'topic',title,parent:unit,position:0,...common,description:'Desarrollo conceptual y práctica de '+b.name.toLowerCase()+'.',body,examples:'Ejemplo didáctico; valores ilustrativos.\n\n'+examples,activities:activities+'\n\nEntrega sugerida: procedimiento, unidades, supuestos y conclusión. Comprueba el resultado por una segunda vía cuando sea posible.',bibliography:'Consulta la bibliografía base de la rama y la lectura complementaria en Recursos del tema. Estas explicaciones son material didáctico de apoyo, no extractos textuales del libro.'});
 });
 branchLearningContent.push({id:course+'-lectura',kind:'resource',title:'Lectura complementaria · '+b.name,parent:course,position:10,...common,resourceType:'Enlace',description:'Fuente académica o institucional complementaria. La bibliografía base de la rama reúne textos para el conjunto del programa.',url:b.source,links:b.lessons.map((_,n)=>course+'-u'+(n+1)+'-tema')});
}
