export type Item = {id:string; kind:string; title:string; status:string; position:number; parent?:string; links?:string[]; description?:string; objectives?:string; body?:string; examples?:string; activities?:string; bibliography?:string; url?:string; file?:string; filename?:string; resourceType?:string; transcript?:string; authors?:string; date?:string; keywords?:string; area?:string; publicationType?:string; image?:string; featured?:boolean; current?:boolean; example?:boolean; name?:string; email?:string; education?:string; interests?:string; projects?:string; social?:string; plan?:string; [key:string]:unknown};
export const branches=['Química general','Química inorgánica','Química orgánica','Química analítica','Fisicoquímica','Bioquímica','Química ambiental'];
const make=(id:string,kind:string,title:string,extra:Partial<Item>={}):Item=>({id,kind,title,status:'published',position:0,...extra});
export const seed:Item[]=[
 ...branches.map((title,i)=>make('rama-'+i,'branch',title,{position:i,description:['Materia, estructura atómica y transformaciones.','Elementos, compuestos y sus propiedades.','El carbono y sus múltiples posibilidades.','Métodos para conocer la composición de la materia.','Energía, equilibrio y cambio.','La química de los seres vivos.','Procesos químicos y cuidado del entorno.'][i]})),
 make('decimo','course','Química de Décimo',{parent:'rama-0',description:'Un espacio para comprender la materia y aprender a interpretar sus transformaciones.',objectives:'Relacionar propiedades de la materia con su estructura.\nInterpretar representaciones químicas.\nResolver problemas utilizando unidades y evidencias.',example:true}),
 make('once','course','Química de Once',{parent:'rama-0',description:'Conecta conceptos, interpreta fenómenos y aplica lo aprendido a nuevas situaciones.',objectives:'Analizar relaciones entre estructura y propiedades.\nArgumentar respuestas a partir de datos.\nAplicar conceptos químicos en situaciones cotidianas.',example:true}),
 ...['decimo','once'].flatMap(g=>[1,2,3,4].map(n=>make(g+'-p'+n,'period','Período '+n,{parent:g,position:n,current:n===1,example:true}))),
 make('unidad-materia','unit','Materia y medición',{parent:'decimo-p1',example:true}),
 make('unidad-soluciones','unit','Soluciones y concentración',{parent:'once-p1',example:true}),
 make('materia','topic','Propiedades de la materia',{parent:'unidad-materia',example:true,featured:true,description:'Distingue propiedades físicas y químicas a partir de situaciones cotidianas.',body:'La materia tiene masa y ocupa un volumen. Una propiedad física se puede observar o medir sin cambiar la identidad química de la sustancia. La densidad, por ejemplo, relaciona masa y volumen: ρ = m/V.\n\nUna propiedad química describe la capacidad de una sustancia para transformarse en otras. La combustibilidad es una propiedad química. Derretir hielo es un cambio físico; la formación de óxido es un cambio químico.',examples:'Una muestra tiene una masa de 54 g y un volumen de 20 mL.\nρ = 54 g / 20 mL = 2,7 g/mL.\nLa densidad expresa cuánta masa hay por unidad de volumen.',activities:'1. Clasifica como física o química: color, combustibilidad, punto de ebullición. Justifica.\n2. Calcula la densidad de una muestra de 80 g y 40 mL.\n3. Explica por qué la evaporación del agua conserva su identidad química.',bibliography:'Añade aquí la bibliografía utilizada en tu asignatura.'}),
 make('concentracion','topic','Concentración de soluciones',{parent:'unidad-soluciones',example:true,featured:true,description:'Relaciona la cantidad de soluto con el volumen de una solución.',body:'Una solución es una mezcla homogénea. La concentración indica cuánto soluto contiene una cantidad de solución.\n\nLa concentración molar se calcula como c = n/V: cantidad de sustancia en moles dividida entre el volumen de la solución en litros.\n\nFórmulas de uso frecuente: H₂O, NaCl, CO₂. La carga de un ion se representa como Na⁺ o Ca²⁺.',examples:'Si se disuelven 0,50 mol de NaCl y se completa un volumen final de 2,0 L, la concentración es:\nc = 0,50 mol / 2,0 L = 0,25 mol/L.',activities:'1. Calcula la concentración de 0,20 mol de soluto en 0,50 L de solución.\n2. Explica qué ocurre con la concentración al añadir agua sin agregar soluto.'}),
 make('saber','unit','Repaso y preparación Saber 11',{parent:'once',example:true,description:'Ejercicios de aplicación ilustrativos. No son preguntas oficiales del ICFES.'}),
 make('saber-dilucion','topic','Interpreta una dilución',{parent:'saber',example:true,body:'A una solución se le añade agua sin pérdida de soluto. ¿Qué sucede con la concentración?\n\nA. Aumenta.\nB. Disminuye.\nC. Permanece igual.\nD. Se duplica.',examples:'Respuesta explicada: B. La cantidad de soluto se mantiene y el volumen aumenta. Como c = n/V, la concentración disminuye.\n\nEjercicio de aplicación: si el volumen final es el doble del inicial, la concentración final es la mitad. Este es un ejemplo didáctico, no una pregunta oficial.'}),
 make('perfil','profile','Sobre mí',{name:'',description:'',education:'',interests:'',projects:'',email:'',social:''}),
];
export const kinds:Record<string,string>={branch:'Rama',course:'Asignatura',period:'Período',unit:'Unidad',topic:'Tema',resource:'Recurso',research:'Investigación',profile:'Perfil'};
export function ancestry(item:Item, all:Item[]):Item[]{const out:Item[]=[];const visited=new Set([item.id]);let p=item.parent||(item.kind==='resource'?item.links?.[0]:undefined);while(p&&!visited.has(p)){visited.add(p);const x=all.find(i=>i.id===p);if(!x)break;out.unshift(x);p=x.parent;}return out;}
export function descendants(id:string,all:Item[]):Item[]{return all.filter(i=>ancestry(i,all).some(p=>p.id===id));}
export function safeUrl(url:unknown){if(typeof url!=='string')return '';try{const u=new URL(url);return ['https:','http:'].includes(u.protocol)?u.href:''}catch{return ''}}


