import 'server-only';
import type {Item} from './content';

// Transcripción editorial del CV_juan_pablo_2026.pdf entregado por el autor.
// No se publica el documento completo ni los datos de contacto de sus referencias.
export const cvProfile:Partial<Item>={
 name:'Juan Pablo Betancourt Arango',
 description:'Magíster en Química y Licenciado en Biología y Química por la Universidad de Caldas. Docente e investigador con experiencia en Ciencias Naturales, química analítica, cromatografía y ciencias ómicas, y en la enseñanza de Biología y Química en educación básica, media y universitaria.',
 education:'Magíster en Química · Universidad de Caldas, Manizales · febrero de 2022 a junio de 2024.\n\nLicenciado en Biología y Química · Universidad de Caldas, Manizales · febrero de 2015 a enero de 2021.\n\nFormación complementaria: Diplomado en Fundamentos y Aplicaciones de las Técnicas Cromatográficas en Investigación Científica (Universidad de Caldas, 2019); Diplomado en Internet de las Cosas IoT (Universidad de Caldas y Centro de Ciencia Francisco José de Caldas, 2018–2019); Aceites Esenciales: Extracción, Usos y Aplicaciones (SENA, 40 horas, 2020); formación en inglés A1 y A2 (PRELEX, Universidad de Caldas, 2022).',
 body:'Docencia escolar y preparación de pruebas\nColegio Nuestra Señora del Rosario: Biología y Química (enero–diciembre de 2020). Colegio Integración Moderna, Bogotá: Ciencias Naturales, Química e Investigación (julio–noviembre de 2021 y enero–mayo de 2022). Pre-ICFES Fabio Andrés Pardo Reyes: Ciencias Naturales y Química (marzo–mayo de 2022).\n\nDocencia universitaria\nDepartamento de Química de la Universidad de Caldas: Laboratorio de Química Orgánica (agosto–diciembre de 2022); laboratorios de Química I, Química II y Química General (febrero–junio de 2023); Química General teórica y laboratorios de Química I y Química General (agosto–diciembre de 2023).\n\nInvestigación y análisis instrumental\nParticipación como estudiante líder del Semillero de Investigación en Cromatografía y Técnicas Afines (SICTA), Universidad de Caldas, desde agosto de 2018, según la hoja de vida. Joven investigador de la convocatoria 907 de Minciencias (junio de 2022 a junio de 2023). Analista de laboratorio en la Industria Licorera de Caldas (agosto–diciembre de 2023 y febrero–mayo de 2024), aplicando GC–MS, GC–FID y olfatometría a rones, tafias y aguardientes. Analista del proyecto ARTVOC (ref. 101131151), sobre compuestos orgánicos volátiles en tecnologías de reproducción asistida, en Estonian University of Life Sciences, Tartu, Estonia; la hoja de vida no especifica fechas.\n\nParticipación científica\nPonencias en LASEAC / ENQAmb (Brasil, 2024), IV LAMPS Meeting (Cartagena, 2022), XVIII Congreso Colombiano de Química (Popayán, 2019) y III Congreso Internacional de Investigación / Encuentro de Semilleros (Bucaramanga, 2019).',
 interests:'Líneas identificadas en los proyectos y publicaciones de la hoja de vida:\n• Cromatografía de gases, espectrometría de masas y olfatometría.\n• Metabolómica, volatilómica, xenovolatilómica y lipidómica.\n• Biomarcadores de toxicidad y análisis de residuos de plaguicidas.\n• Caracterización química de alimentos, bebidas y productos naturales.\n• Sensores electroquímicos y control de calidad.\n• Didáctica de Biología y Química, relación teoría–práctica y formación docente.\n• Química computacional, realidad aumentada y educación STEM/STEAM.',
 projects:'Transformación digital 4.0 en la Industria Licorera de Caldas (2022–2025): trazabilidad, control de calidad y productividad.\n\nBiodiversidad de hongos macromicetos del Jardín Botánico de la Universidad de Caldas mediante herramientas metabolómicas con fines de bioprospección (desde julio de 2023; en curso según la hoja de vida).\n\nSensor electroquímico para detectar aflatoxina B1 en arroz (2022–2023).\n\nAnálisis multirresiduo de plaguicidas organoclorados y organofosforados en aguacate Hass de la subregión norte de Caldas (2022–2023), precedido por el proyecto de análisis residual en aguacate (2019–2021).\n\nRelación entre teoría y práctica en estudiantes de Biología y Química de Colombia: revisión sistemática (2019–2020).\n\nParticipación como analista en ARTVOC, proyecto HORIZON-MSCA-2022-SE-01-01 sobre compuestos orgánicos volátiles en reproducción asistida, en Estonia (sin fechas indicadas en el CV).',
 email:'juan.betancourt@ucaldas.edu.co',
 scholar:'https://scholar.google.com/citations?user=h-mLw2sAAAAJ&hl=es',
 orcid:'https://orcid.org/0000-0003-0409-5900',
 researchgate:'https://www.researchgate.net/profile/Juan-Betancourt-Arango-2',
 researchIntro:'Artículos y proyectos consignados en mi hoja de vida de 2026. Cada artículo enlaza a su DOI; las descripciones son síntesis orientativas del título, no resúmenes originales de los artículos.',
 researchLines:'Cromatografía y análisis de plaguicidas\nMetabolómica y volatilómica de alimentos\nBiomarcadores de toxicidad\nBioprospección y productos naturales\nDidáctica de las ciencias y tecnologías educativas'
};

const articles:[string,string,string,string,string,string][]=[
 ['2021','Extracción de plaguicidas en el aguacate Hass (Persea americana Mill. cv.) mediante el uso de C18 y arcillas funcionales como fase adsorbente en la metodología QuEChERS','Betancourt-Arango, J. P.; Ossa-Jaramillo, C. A.; Taborda-Ocampo, G.','10.18257/raccefyn.1235','Química analítica','Extracción y análisis de plaguicidas en aguacate Hass mediante QuEChERS.'],
 ['2022','Revisión sistemática de literatura sobre la relación entre la teoría y la práctica en estudiantes de biología y química de Colombia','Betancourt-Arango, J. P.; Suárez-Millán, M. del C.; Álvarez-Márquez, D. Y.','10.17151/luaz.2022.54.7','Química general','Relación entre teoría y práctica en la formación en Biología y Química.'],
 ['2023','La química computacional como mediación pedagógica para el aprendizaje de conceptos fundamentales de química general','Suárez-Millán, M. C.; Betancourt-Arango, J. P.','10.22201/fq.18708404e.2023.1.77684','Química general','Uso pedagógico de la química computacional en conceptos de química general.'],
 ['2024','Aplicabilidad de la realidad aumentada y las ciencias computacionales en el aula de clase','Betancourt-Arango, J.; Suárez-Millán, M.; Franco, Y.','10.22201/fq.18708404e.2024.2.86812','Química general','Aplicaciones educativas de la realidad aumentada y las ciencias computacionales.'],
 ['2024','Volatilomics: An emerging discipline within Omics Sciences - A systematic review','Betancourt-Arango, J. P.; Villaroel-Solis, E. E.; Fiscal-Ladino, J. A.; Taborda-Ocampo, G.','10.12688/f1000research.149773.1','Volatilómica','Revisión sistemática sobre la volatilómica como disciplina de las ciencias ómicas.'],
 ['2025','Aplicaciones de la xenometabolómica para la identificación de biomarcadores de toxicidad: una revisión del tema','Betancourt-Arango, J. P.; Patiño-Ospina, A.; Taborda-Ocampo, G.; Fiscal-Ladino, J. A.','10.17151/biosa.2020.19.1.1','Metabolómica','Xenometabolómica e identificación de biomarcadores de toxicidad.'],
 ['2025','Volatilomic Analysis in Peel, Pulp and Seed of Hass Avocado (Persea americana Mill.) From the Northern Subregion of Caldas by Gas Chromatography with Mass Spectrometry','Betancourt-Arango, J. P.; Patiño-Ospina, A.; Taborda-Ocampo, G.; Fiscal-Ladino, J. A.','10.1002/fsn3.70489','Volatilómica','Análisis volatilómico de cáscara, pulpa y semilla de aguacate Hass mediante GC–MS.'],
 ['2025','Xenovolatilomic profiling of Hass avocado (Persea americana Mill.) tissues exposed to endosulfan: identification of potential toxicity biomarkers','Betancourt-Arango, J. P.; Patiño-Ospina, A.; Fiscal-Ladino, J. A.; Taborda-Ocampo, G.','10.1039/D5FB00163C','Volatilómica','Perfiles xenovolatilómicos de tejidos de aguacate expuestos a endosulfán.'],
 ['2025','Bibliometric analysis on the STEM/STEAM approach in the training of natural sciences teachers in Colombia','Millán, M. D. C. S.; Arango, J. P. B.','10.1007/s44217-025-00735-9','Química general','Análisis bibliométrico de STEM/STEAM en la formación de docentes de Ciencias Naturales.'],
 ['2026','In silico evaluation of pharmacokinetic properties and molecular docking for the identification of potential anticancer compounds','Arango, J. P. B.; Rodríguez, D. Y. M.; Cruz, S. L.; Ocampo, G. T.','10.1016/j.compbiolchem.2025.108626','Bioquímica','Evaluación computacional de propiedades farmacocinéticas y acoplamiento molecular de posibles compuestos anticancerígenos.'],
 ['2025','Lipidomic approach to the analysis of Persea americana Mill. cv. from the northern subregion of the department of Caldas','Betancourt-Arango, J. P.; Patiño-Ospina, A.; Tabares-Sepúlveda, J. E.; Vélez-Naranjo, E. A.; Fiscal-Ladino, J. A.; Taborda-Ocampo, G.','10.37349/eff.2025.1010100','Metabolómica','Aproximación lipidómica al análisis de aguacate de la subregión norte de Caldas.'],
 ['2025','Didáctica de las ciencias ómicas: hacia la enseñanza y el aprendizaje de la metabolómica en la educación superior','Betancourt-Arango, J. P.; Suárez-Millán, M. del C.; Taborda-Ocampo, G.','10.22201/fq.18708404e.2025.4.90704','Metabolómica','Enseñanza y aprendizaje de metabolómica en educación superior.'],
 ['2025','Cannabinomics in the flower of Cannabis sativa: a systematic review of extraction, analytical identification, and micro/nanoencapsulation methods for bioactive metabolites','Castaño-Acosta, M.; Betancourt-Arango, J. P.; Castellanos-Galeano, F.; Taborda-Ocampo, G.','10.1186/s42238-025-00350-3','Metabolómica','Revisión de extracción, identificación y micro/nanoencapsulación de metabolitos bioactivos de Cannabis sativa.'],
 ['2025','Optimization of the methodology for the extraction of organophosphate pesticides by HS–SPME–GC–NPD','Fiscal-Ladino, J. A.; Taborda-Ocampo, G.; Betancourt-Arango, J. P.','10.18257/raccefyn.3173','Química analítica','Optimización de extracción de plaguicidas organofosforados mediante HS–SPME–GC–NPD.']
];
const projects:[string,string,string,string][]=[
 ['2022','Transformación digital 4.0 para mejorar la trazabilidad, el control de calidad y la productividad en la Industria Licorera de Caldas','Enero de 2022 a diciembre de 2025.','Química analítica'],
 ['2023','Estudio de la biodiversidad de hongos macromicetos silvestres del Jardín Botánico de la Universidad de Caldas mediante herramientas metabolómicas con fines de bioprospección','Desde julio de 2023; en curso según el CV de 2026.','Metabolómica'],
 ['2022','Desarrollo de un sensor electroquímico para la detección de aflatoxina B1 en arroz','Junio de 2022 a julio de 2023.','Química analítica'],
 ['2022','Método multiresiduo para el análisis de plaguicidas organoclorados y organofosforados en aguacate Hass (Persea americana Mill. cv.) de la subregión norte de Caldas','Junio de 2022 a junio de 2023.','Química analítica'],
 ['2019','Análisis residual de plaguicidas organoclorados y organofosforados en aguacate (Persea americana Mill.) cv.','Marzo de 2019 a enero de 2021.','Química analítica'],
 ['2019','Revisión sistemática de literatura sobre la relación entre la teoría y la práctica en estudiantes de Biología y Química de Colombia','Febrero de 2019 a febrero de 2020.','Química general']
];
export const cvResearch:Item[]=[
 ...articles.map(([date,title,authors,doi,area,description],n)=>({id:'cv-articulo-'+(n+1),kind:'research',status:'published',position:100+n,title,date,authors,area,description,publicationType:'Artículo',url:'https://doi.org/'+doi,keywords:area,body:'Referencia transcrita de la hoja de vida proporcionada por el autor (2026). Descripción orientativa basada en el título; consulta el resumen y el texto original en el DOI. Año y autoría conservados según el CV.'+(n===5?' El CV indica 2025; el DOI contiene 2020. Fecha bibliográfica pendiente de cotejo con la revista.':'')})),
 ...projects.map(([date,title,period,area],n)=>({id:'cv-proyecto-'+(n+1),kind:'research',status:'published',position:120+n,title,date,area,publicationType:'Proyecto',authors:'Participación de Juan Pablo Betancourt Arango; equipo completo no especificado en el CV.',description:period,body:'Proyecto consignado en la hoja de vida de 2026. El año de clasificación corresponde al inicio del proyecto. El documento no especifica el equipo completo, los resultados ni un enlace público.',keywords:area}))
];

export function completeCvProfile(item:Item):Item{
 if(item.kind!=='profile')return item;
 const result={...item};
 for(const [key,value] of Object.entries(cvProfile)){
  if(!result[key]||(typeof result[key]==='string'&&(/pendiente|se actualizará con la trayectoria/i.test(result[key] as string)))) result[key]=value;
 }
 return result;
}
