import type {Item} from './content';
import {academicBooks} from './academic-books';
// Original, editable teaching proposals. Existing IDs are kept to preserve resource links.
const additions:Record<string,string[]>={
 'general-i':['Herramientas de trabajo|Unidades y análisis dimensional|Incertidumbre y cifras significativas|Seguridad, residuos y cuaderno de laboratorio|Formulación y nomenclatura inorgánica','Composición y transformaciones|Mol y composición porcentual|Fórmulas empíricas y moleculares|Balance de ecuaciones y rendimiento|Reacciones en disolución y ecuaciones iónicas','Laboratorio integrador|Preparación de disoluciones|Medición de densidad y concentración|Análisis de datos experimentales|Informe con resultados e incertidumbre'],
 'general-ii':['Disoluciones reales|Propiedades coligativas|Diagramas de fase|Actividad e idealidad|Fuerzas intermoleculares y solvatación','Análisis de equilibrios|Balances de masa y carga|Soluciones amortiguadoras|Curvas de titulación|Equilibrios acoplados y aproximaciones','Integración experimental|Determinación de constantes de equilibrio|Ajuste de datos cinéticos|Potenciales y ecuación de Nernst|Diseño y comunicación de una indagación'],
 'inorganica-avanzada':['Estructura y simetría|Repaso de orbitales atómicos y periodicidad|Operaciones y grupos puntuales|Representaciones y tablas de caracteres|Orbitales moleculares de moléculas pequeñas','Química de elementos y sólidos|Reactividad del bloque principal|Estructuras cristalinas y defectos|Energía reticular y enlace en sólidos|Materiales funcionales y caracterización','Métodos y evidencia|Espectros electrónicos y magnetismo|Conteo electrónico y regla de 18 electrones|Síntesis y caracterización de complejos|Crítica de un mecanismo catalítico'],
 'organica-avanzada':['Estructura y elucidación|Conformación y configuración absoluta|Aromaticidad y heteroaromaticidad|Interpretación combinada de IR y MS|RMN 1D y correlaciones 2D introductorias','Reacciones para construir moléculas|Química de enoles y enolatos|Formación de enlaces carbono-carbono|Acoplamientos catalizados por metales|Reacciones pericíclicas y orbitales frontera','Proyecto de síntesis|Oxidaciones y reducciones selectivas|Síntesis de heterociclos|Economía atómica y seguridad|Comparación argumentada de rutas multietapa'],
 'analitica-cuantitativa':['Equilibrio y métodos|Balances de masa y carga|Titulaciones ácido-base|Titulaciones redox y complejométricas|Precipitación y curvas de valoración','Estadística aplicada|Distribuciones e intervalos de confianza|Contraste de hipótesis y errores|Regresión y residuos|Propagación de incertidumbre','Proyecto cuantitativo|Selección de método según matriz|Diseño de controles y blancos|Recuperación, precisión y sesgo|Informe de validación y límites de uso'],
 'instrumental':['Señal y medición|Señal, ruido y relación señal-ruido|Componentes ópticos y detectores|Sensibilidad y rango dinámico|Procesamiento y adquisición de señales','Técnicas complementarias|FTIR y Raman|Fundamentos de RMN|Potenciometría y voltametría|Técnicas térmicas y análisis de superficies','Comparación de plataformas|Interferencias espectrales y químicas|Límites de detección y cuantificación|Selección multicriterio de instrumentación|Informe crítico de un método instrumental'],
 'cromatografia':['Muestra y mecanismos|Extracción líquido-líquido y SPE|Adsorción y partición|Intercambio iónico y exclusión por tamaño|Derivatización y estabilidad del analito','Instrumentación y operación|Inyección, columnas y detectores|Fase móvil, gradientes y presión|Acoplamiento MS y compatibilidad|Diagnóstico de fallos y mantenimiento conceptual','Validación de separaciones|Selectividad frente a coelución|Curvas, patrones internos y recuperaciones|Robustez y transferencia de métodos|Comparación cuantitativa de cromatogramas'],
 'termodinamica':['Herramientas y modelos|Diferenciales y derivadas parciales|Ecuaciones de estado reales|Calor, trabajo y capacidades caloríficas|Integración de datos calorimétricos','Relaciones termodinámicas|Relaciones de Maxwell|Ecuación de Gibbs-Duhem|Fugacidad y coeficientes de actividad|Modelos de exceso y mezclas no ideales','Aplicaciones y límites|Clapeyron y Clausius-Clapeyron|Equilibrio electroquímico|Introducción a funciones de partición|Resolución y contraste de un problema de equilibrio'],
 'cinetica-catalisis':['Medición cinética|Métodos diferenciales e integrales|Técnicas rápidas y tiempos de respuesta|Estimación de parámetros e incertidumbre|Residuos y selección de modelos','Bases moleculares|Teoría de colisiones|Teoría del estado de transición|Reacciones en solución y difusión|Fotoquímica y reacciones en cadena','Sistemas catalíticos|Adsorción e isotermas|Modelos de Langmuir-Hinshelwood|Transferencia de masa y reacción|Selectividad, desactivación y diseño de ensayo'],
 'cuantica-computacional':['Herramientas matemáticas|Álgebra lineal y autovalores|Probabilidad y normalización|Conmutadores y observables|Método variacional y perturbación','Modelos y espectros|Partícula en caja|Oscilador armónico y rotor rígido|Átomo de hidrógeno y espín|Reglas de selección e interpretación espectral','Práctica computacional|Conjuntos de base y convergencia|Correlación electrónica y error de método|Solvente, conformaciones y estados de transición|Cuaderno reproducible y comparación con experimento'],
 'bioquimica-avanzada':['Biomoléculas y métodos|Estructura y plegamiento de proteínas|Carbohidratos, lípidos y membranas|Purificación y caracterización de biomoléculas|Termodinámica de unión y cooperatividad','Regulación y comunicación|Señalización celular y segundos mensajeros|Metabolismo de nitrógeno y nucleótidos|Compartimentalización y transporte|Regulación transcripcional y postraduccional','Integración experimental|Cinética, inhibición y ensayos acoplados|Balances energéticos y flujo metabólico|Diseño de controles biológicos|Lectura crítica de un estudio bioquímico'],
 'ambiental-avanzada':['Compartimentos ambientales|Química acuática y sistema carbonato|Química atmosférica y fotooxidación|Suelos, sedimentos y sorción|Metales y especiación redox','Destino y exposición|Balances de masa y modelos de cajas|Partición aire-agua-sólido|Cinética de degradación y persistencia|Exposición, riesgo e incertidumbre','Proyecto ambiental|Muestreo representativo y conservación|Indicadores de calidad y trazabilidad|Comparación de tecnologías de tratamiento|Informe de monitoreo con límites de interpretación'],
 'quimiometria':['Fundamentos estadísticos|Matrices y descomposición en valores singulares|Distribuciones y estimación|Regresión, diagnóstico y residuos|Programación y trazabilidad de datos','Diseño y calibración|Diseños factoriales y fraccionados|Superficies de respuesta|Calibración multivariante y selección de variables|Transferencia de calibración','Modelos responsables|Clasificación y métricas desbalanceadas|Validación anidada y permutaciones|Interpretabilidad y dominio de aplicación|Proyecto reproducible con conjunto de prueba independiente'],
 'metabolomica':['Pregunta y protocolo de investigación|Hipótesis, estimandos y factores de confusión|Potencia estadística y tamaño muestral|Diseños longitudinales y medidas repetidas|Ética, consentimiento y preregistro','Química preanalítica|Apagado metabólico y extracción|Estabilidad, transporte y almacenamiento|Estándares isotópicos y recuperación|Efectos de matriz y supresión iónica','Plataformas avanzadas|LC-HRMS y adquisición DDA/DIA|GC-MS y derivatización|RMN cuantitativa y bidimensional|Cobertura, sensibilidad y complementariedad','Aseguramiento de calidad|Blancos, mezclas QC y diluciones|Aleatorización y control entre lotes|Deriva instrumental y criterios de exclusión|Materiales de referencia y trazabilidad','Procesamiento reproducible|Detección y deconvolución de señales|Alineamiento, aductos e isótopos|Datos faltantes y mecanismos de ausencia|Normalización y corrección de lote sin fuga','Identificación estructural|Masa exacta y fórmula elemental|Fragmentación MS/MS y bibliotecas|Estándares auténticos y tiempo de retención|Niveles de confianza y anotación de desconocidos','Inferencia y validación|Modelos mixtos y pruebas múltiples|PCA, PLS y límites de interpretación|Validación anidada, permutaciones y cohorte externa|Confusión, causalidad y reproducibilidad','Biología de sistemas|Enriquecimiento de rutas y sesgos de cobertura|Trazadores isotópicos y análisis de flujo|Integración multi-ómica|Redes metabólicas y validación funcional','Proyecto de investigación|Plan de gestión de datos y metadatos|Repositorio, código y entornos reproducibles|Revisión por pares del protocolo|Defensa de resultados con incertidumbre y limitaciones'],
 'volatilomica':['Fundamentos del volatiloma|Presión de vapor y coeficientes de partición|Transferencia de masa y cinética de emisión|Fuentes biológicas, exógenas y microbianas|Diferencia entre concentración y tasa de emisión','Diseño y muestreo avanzado|Diseños longitudinales y factores de confusión|Cámaras, bolsas, tubos y materiales|Muestreo de aliento y fracción alveolar|Humedad, temperatura, flujo y conservación','Preconcentración y extracción|Equilibrio y cinética en HS-SPME|Selección de recubrimientos y competencia|Desorción térmica y ruptura del adsorbente|SPME Arrow, extracción dinámica y validación','Plataformas de separación|GC-MS y GC-HRMS|GC×GC, modulación y análisis bidimensional|GC-IMS y movilidad iónica|GC-olfatometría y diseño sensorial','Medición en tiempo real|PTR-MS y química de ionización|SIFT-MS y cinética de iones|Interferencias, humedad y fragmentación|Comparación entre métodos directos y cromatográficos','Identidad y cuantificación|Índices de retención y series de referencia|Deconvolución y coincidencia espectral|Estándares auténticos e isotópicos|Calibración de gases y trazabilidad','Control de calidad|Blancos de campo, transporte y laboratorio|Contaminación por materiales y arrastre|Estabilidad, recuperación y límites de detección|Comparabilidad interlaboratorio e incertidumbre','Inferencia de perfiles|Alineamiento, censura y valores faltantes|Normalización y corrección de deriva|Modelos predictivos con validación externa|Confusión ambiental y límites de biomarcadores','Investigación integradora|Volátiles en alimentos, plantas y ambiente|Protocolo ético de estudio biológico|Datos, metadatos y código reproducible|Defensa de proyecto y evaluación crítica de aplicaciones'],
};
const prerequisites:Record<string,string>={
 'general-i':'Álgebra, proporciones y química escolar.', 'general-ii':'Química general I.', 'inorganica-avanzada':'Química general I–II y enlace químico.', 'organica-avanzada':'Química orgánica básica, grupos funcionales y mecanismos fundamentales.', 'analitica-cuantitativa':'Química general II y estadística básica.', instrumental:'Analítica cuantitativa y fundamentos de física.', cromatografia:'Química analítica e instrumental.', termodinamica:'Cálculo diferencial e integral y física básica.', 'cinetica-catalisis':'Termodinámica, cálculo y ajuste de datos.', 'cuantica-computacional':'Álgebra lineal, cálculo, física y programación inicial.', 'bioquimica-avanzada':'Química orgánica y bioquímica básica.', 'ambiental-avanzada':'Química general, analítica y termodinámica.', quimiometria:'Estadística, álgebra lineal y programación inicial en R o Python.', metabolomica:'Bioquímica, análisis instrumental, quimiometría y programación en R o Python.', volatilomica:'Cromatografía, espectrometría de masas, termodinámica de partición, estadística y programación.',
};
export function expandDegreePlan(initial:Item[]):Item[]{
 const out=initial.map(i=>({...i}));
 for(const [slug,modules] of Object.entries(additions)){
  const id='pregrado-'+slug, course=out.find(i=>i.id===id);if(!course)continue;
  const graduate=['metabolomica','volatilomica'].includes(slug);
  course.body=(graduate?'Propuesta de posgrado: dos semestres de 16 semanas, con seminario y proyecto de investigación.':'Propuesta de pregrado: semestre de 16 semanas, adaptable a créditos y horas institucionales.')+'\n\nPrerrequisitos sugeridos: '+prerequisites[slug]+'\n\nEvaluación propuesta: '+(graduate?'protocolo 20%; análisis reproducible 30%; seminarios críticos 20%; informe y defensa 30%.':'problemas argumentados 30%; prácticas o análisis de datos 30%; evaluación integradora 25%; proyecto y comunicación 15%.')+'\n\nLa secuencia es editable, no un programa oficial. Los temas describen el alcance previsto; no equivalen a clases o guías completas.';
  course.example=true;
  modules.forEach((row,n)=>{const [title,...topics]=row.split('|');const uid=id+'-extension-'+(n+1);out.push({id:uid,kind:'unit',title,status:'published',position:n+3,parent:id,example:true,description:graduate?'Seminario, revisión crítica y aplicación reproducible.':'Conceptos, problemas y aplicación guiada.'});topics.forEach((title,t)=>out.push({id:uid+'-t'+(t+1),kind:'topic',title,status:'published',position:t,parent:uid,example:true,description:'Alcance propuesto: '+title+'.',objectives:graduate?'Evaluar críticamente '+title.toLowerCase()+'; justificar decisiones metodológicas y contrastarlas con datos y literatura.':'Explicar y aplicar '+title.toLowerCase()+' a problemas de la asignatura, justificando el procedimiento y sus límites.',body:'Tema del plan de '+(graduate?'posgrado':'pregrado')+'. La explicación desarrollada y los recursos de clase están pendientes de publicación.',activities:graduate?'Preparar un análisis reproducible o una revisión crítica sobre este tema. Explicitar supuestos, controles, incertidumbre, alternativas y limitaciones.':'Resolver un problema o analizar datos sobre este tema; entregar procedimiento, unidades, interpretación y conclusiones.'}));});
  const unitOrder:Record<string,string[]>={
   'general-i':['extension-1','u1','u2','extension-2','u3','extension-3'],
   'general-ii':['extension-1','u1','u2','extension-2','u3','extension-3'],
   'inorganica-avanzada':['extension-1','u1','u2','extension-2','u3','extension-3'],
   'organica-avanzada':['extension-1','u1','u2','extension-2','u3','extension-3'],
   'termodinamica':['extension-1','u1','extension-2','u2','u3','extension-3'],
   'cuantica-computacional':['extension-1','u1','extension-2','u2','u3','extension-3'],
   'bioquimica-avanzada':['extension-1','u1','u2','extension-2','u3','extension-3'],
   'quimiometria':['extension-1','u1','extension-2','u2','u3','extension-3'],
   'metabolomica':['u1','extension-1','extension-2','extension-3','extension-4','u2','extension-5','extension-6','u3','extension-7','extension-8','extension-9'],
   'volatilomica':['extension-1','u1','extension-2','extension-3','u2','extension-4','extension-5','extension-6','extension-7','u3','extension-8','extension-9'],
  };
  if(unitOrder[slug])out.filter(i=>i.parent===id&&i.kind==='unit').forEach(u=>{u.position=unitOrder[slug].indexOf(u.id.slice(id.length+1))});
  const units=out.filter(i=>i.parent===id&&i.kind==='unit').sort((a,b)=>a.position-b.position);
  units.forEach((u,n)=>{const length=graduate?32:16;const start=Math.floor(n*length/units.length)+1,end=Math.floor((n+1)*length/units.length);u.description='Semanas '+start+'–'+end+' · '+(u.description||'Desarrollo conceptual, aplicación y evaluación.');});
 }
 // A book is one reusable resource linked to many topics, never an unauthorized upload.
 const path=(item:Item):string[]=>{const seen=new Set<string>();let p:Item|undefined=item;while(p&&!seen.has(p.id)){seen.add(p.id);p=out.find(i=>i.id===p!.parent)}return [...seen]};
 for(const b of academicBooks){const links=out.filter(i=>i.kind==='topic'&&path(i).some(id=>b.branches.includes(id))).map(i=>i.id);out.push({id:'libro-'+b.id,kind:'resource',title:b.title,status:'published',position:90,resourceType:'Bibliografía',description:b.authors+' · '+b.access,url:b.url,links,body:b.scope+'\n\nAcceso: '+b.access+'. Consulta la edición y las condiciones en el sitio original. Referencia externa; no es una publicación del docente.'});}
 for(const [id,title,url,branch] of [
  ['ebi-metabolomics','Introducción y diseño de estudios metabolómicos · EMBL-EBI','https://www.ebi.ac.uk/training/online/courses/metabolomics-introduction/','sub-metabolomica'],
  ['metabolomics-reporting','Buenas prácticas y estándares de reporte en metabolómica','https://www.nature.com/articles/s41467-019-10900-y','sub-metabolomica'],
  ['nist-retention','Datos de retención cromatográfica · NIST Chemistry WebBook','https://webbook.nist.gov/chemistry/gc-ri/','sub-volatilomica'],
 ])out.push({id,kind:'resource',title,url,status:'published',position:91,resourceType:'Bibliografía',description:'Referencia externa para lectura crítica y aplicación metodológica.',links:out.filter(i=>i.kind==='topic'&&path(i).includes(branch)).map(i=>i.id),body:'Complemento a la bibliografía base. Consultar condiciones de uso, alcance y limitaciones en la fuente original.'});
 return out;
}
