import type {Item} from './content';
export const scienceNotice='Propuesta editable para Ciencias Naturales de básica secundaria en Colombia. Los EBC abarcan conjuntamente 8.º–9.º y los DBA se presentan por grado. La distribución en cuatro períodos es una propuesta pedagógica, no una secuencia oficial del MEN. Ajustar al PEI, la intensidad horaria y los aprendizajes previos.';
export const scienceSources=[{title:'MEN · DBA Ciencias Naturales V.1 · Octavo: pp. 27–29; Noveno: pp. 30–33',url:'https://www.colombiaaprende.edu.co/sites/default/files/files_public/2022-06/DBA_C.Naturales-min.pdf'},{title:'MEN · EBC, Guía 7 · Grados 8.º–9.º: pp. 20–21',url:'https://www.mineducacion.gov.co/1621/articles-81033_archivo.pdf'}];
export const scienceTransversal='En todos los períodos: formular preguntas e hipótesis, identificar variables, medir con unidades, interpretar datos, contrastar fuentes y comunicar conclusiones y limitaciones. Integrar trabajo colaborativo, autocuidado y responsabilidad ambiental.';
type Block={grade:string;period:number;title:string;reference:string;units:[string,string,string[]][]};
export const sciencePlan:Block[]=[
{grade:'octavo',period:1,title:'Regulación de los seres vivos y salud',reference:'DBA 8.º n.º 4. EBC: entorno vivo, salud e indagación.',units:[
['Coordinación y equilibrio interno','Explicar mediante modelos cómo los sistemas mantienen condiciones internas estables.',['Homeostasis y retroalimentación','Neuronas, sinapsis y sistema nervioso','Hormonas y sistema endocrino','Excreción y equilibrio de agua y sales']],
['Defensa, movimiento y autocuidado','Relacionar sistemas corporales y hábitos con bienestar y prevención.',['Sistema inmunitario y respuesta de defensa','Sistemas óseo y muscular','Regulación comparada en diferentes organismos','Hábitos, ejercicio y efectos de sustancias sobre el organismo']]]},
{grade:'octavo',period:2,title:'Reproducción y transformaciones de la materia',reference:'DBA 8.º n.º 5 y 2. EBC: reproducción, sexualidad responsable y cambios químicos.',units:[
['Continuidad de la vida','Comparar estrategias reproductivas y sus efectos en la descendencia.',['Mitosis y meiosis: bases de la reproducción','Reproducción sexual y asexual en plantas y animales','Reproducción humana, pubertad y ciclo menstrual','Salud sexual, prevención de ITS y embarazo adolescente']],
['Átomos, enlaces y reacciones','Representar partículas para distinguir mezclas y transformaciones.',['Electrones de valencia y electronegatividad','Enlace iónico y covalente y propiedades de compuestos','Cambios físicos, mezclas y evidencias de reacción','Reactivos, productos y conservación de átomos']]]},
{grade:'octavo',period:3,title:'Gases, calor y máquinas térmicas',reference:'DBA 8.º n.º 3 y 1. EBC: sistemas termodinámicos y aplicaciones de la energía.',units:[
['Modelo de gases','Interpretar datos y relaciones entre las variables de un gas.',['Modelo cinético: difusión y compresión','Presión, volumen, temperatura absoluta y cantidad de gas','Relaciones de Boyle, Charles y Gay-Lussac','Ley combinada, PV = nRT y límites del gas ideal']],
['Energía y procesos térmicos','Explicar intercambios energéticos y límites del aprovechamiento del calor.',['Temperatura, calor y energía interna','Trabajo y primera ley de la termodinámica','Segunda ley y eficiencia de máquinas térmicas','Motores, refrigeración y transferencia térmica en la atmósfera']]]},
{grade:'octavo',period:4,title:'Ondas, ambiente e integración científica',reference:'EBC: ondas mecánicas, tecnología, ambiente e indagación. Integración de DBA 8.º n.º 1–5. Las ondas amplían los DBA desde los EBC.',units:[
['Ondas y sonido','Relacionar representaciones de ondas con fenómenos observables.',['Oscilaciones y ondas mecánicas','Amplitud, frecuencia, período y longitud de onda','Rapidez, reflexión y transmisión de ondas','Sonido, resonancia, instrumentos y cuidado auditivo']],
['Ciencia y entorno','Sustentar explicaciones ambientales mediante evidencia.',['Procesos físicos y químicos de contaminación del aire','Estrategias de defensa en plantas y animales','Aplicaciones industriales de microorganismos','Proyecto integrador: pregunta, variables, datos y conclusiones']]]},
{grade:'noveno',period:1,title:'Herencia e información genética',reference:'DBA 9.º n.º 4 y 5. EBC: ADN, genes, proteínas y aplicaciones genéticas.',units:[
['Patrones de herencia','Interpretar cruces y explicar variación entre descendientes.',['Cromosomas, genes, alelos, genotipo y fenotipo','Meiosis, segregación y distribución independiente','Leyes de Mendel, probabilidades y cuadros de Punnett','Dominancia incompleta, codominancia y herencia ligada al sexo']],
['Expresión y variabilidad','Relacionar información genética, proteínas y cambios heredables.',['Estructura y replicación del ADN','ARN, transcripción, código genético y traducción','Mutaciones, proteínas y variación del fenotipo','Aplicaciones del análisis genético y debate bioético']]]},
{grade:'noveno',period:2,title:'Evolución, clasificación y biodiversidad',reference:'DBA 9.º n.º 6, articulado con n.º 5. EBC: taxonomía, adaptación y conservación.',units:[
['Explicaciones evolutivas','Contrastar modelos de cambio biológico con evidencia.',['Historia de las explicaciones del origen de las especies','Ancestro común: fósiles, homologías, biogeografía y ADN','Selección natural, variación y adaptación','Tiempo geológico, clima y transformación de la vida']],
['Diversidad y clasificación','Construir clasificaciones justificadas y discutir su utilidad.',['Criterios de especie y categorías taxonómicas','Características celulares y clasificación de organismos','Parentesco y lectura de árboles filogenéticos','Biodiversidad colombiana, conservación y proyecto de indagación']]]},
{grade:'noveno',period:3,title:'Soluciones, acidez y basicidad',reference:'DBA 9.º n.º 3 y 2. EBC: soluciones, modelos ácido-base y aplicaciones cotidianas.',units:[
['Composición de soluciones','Resolver relaciones cuantitativas y explicar condiciones de preparación.',['Soluto, disolvente, saturación y solubilidad','Interacciones intermoleculares y propiedades de líquidos','Concentración: porcentajes, molaridad y molalidad','Preparación, dilución y lectura crítica de etiquetas']],
['Sistemas ácido-base','Comparar modelos e interpretar mediciones de acidez.',['Modelos de Arrhenius, Brønsted–Lowry y Lewis','pH, pOH e indicadores','Neutralización y aplicaciones cotidianas e industriales','Acidez en sistemas biológicos y ambientales']]]},
{grade:'noveno',period:4,title:'Movimiento, luz y proyecto de cierre',reference:'DBA 9.º n.º 1. EBC: ondas, luz, tecnología e indagación. La óptica complementa los DBA desde los EBC.',units:[
['Descripción del movimiento','Interpretar gráficas y predecir movimientos desde un marco de referencia.',['Referencia, posición, desplazamiento, rapidez y velocidad','Movimiento rectilíneo uniforme y gráficas','Aceleración, movimiento uniformemente acelerado y caída libre','Movimiento circular uniforme y parabólico']],
['Luz y comunicación científica','Comparar modelos de luz y comunicar resultados con evidencia.',['Modelos de la luz y espectro electromagnético','Reflexión, refracción y formación de imágenes','Óptica y tecnologías de comunicación','Proyecto de cierre: medición, incertidumbre y argumentación']]]},
];
const make=(id:string,kind:string,title:string,extra:Partial<Item>={}):Item=>({id,kind,title,status:'published',position:0,...extra});
export const scienceCurriculum:Item[]=[];
for(const b of sciencePlan){scienceCurriculum.push(make(b.grade+'-p'+b.period,'period','Período '+b.period,{parent:b.grade,position:b.period,current:b.period===1,description:b.title,body:'Referentes: '+b.reference+'\n\n'+scienceTransversal,example:true}));b.units.forEach(([title,objectives,topics],n)=>{const id=b.grade+'-p'+b.period+'-u'+(n+1);scienceCurriculum.push(make(id,'unit',title,{parent:b.grade+'-p'+b.period,position:n,description:objectives,objectives,body:'Referentes: '+b.reference+'\n\nEvidencia propuesta: explicar un caso con modelos, datos y argumentos. Ajustar instrumentos de evaluación al plan institucional.',example:true}));topics.forEach((title,t)=>scienceCurriculum.push(make(id+'-t'+(t+1),'topic',title,{parent:id,position:t,description:'Ciencias Naturales · '+b.grade+' · Período '+b.period,body:'Alcance de la unidad: '+objectives+'\n\nReferentes del bloque: '+b.reference+'\n\nApartado del temario propuesto. Las explicaciones completas, ejemplos, guías y videos se incorporarán posteriormente.',bibliography:scienceSources.map(s=>s.title+'\n'+s.url).join('\n\n'),example:true})));});}
