export const techniques:Record<string,{title:string;input:string;steps:string[];checks:string;tools:string[]}>={
 'LC-MS':{title:'LC-MS · metabolómica',input:'Archivos nativos completos y mzML compatible; anotar MS1/MS2, perfil/centroide, DDA/DIA, polaridad y unidades de RT.',steps:['Diseñar secuencia con blancos de extracción, estándares internos y QC agrupados; conservar orden de inyección y lotes.','Exportar una copia a mzML con ProteoWizard o lector validado. Centroidar solo si lo requiere el flujo; no centroidar de nuevo datos centroidados.','Detectar trazas y picos con xcms, OpenMS, MZmine o MS-DIAL. Estimar ppm, ruido y anchura en QC, no copiarlos entre equipos.','Alinear RT, agrupar señales homólogas e integrar faltantes revisando los cromatogramas. Separar polaridades, isótopos y aductos sin contarlos automáticamente como metabolitos distintos.','Evaluar blancos, deriva de estándares, RSD y faltantes. Anotar con MS/MS, RT y estándares cuando existan. Exportar matriz, definiciones y parámetros.'],checks:'Comprobar carga, aducto, error de masa y alineamiento. Un match de biblioteca es una anotación, no identificación inequívoca.',tools:['xcms / MsExperiment / Spectra (R)','pyOpenMS (Python)','MZmine o MS-DIAL (interfaz gráfica)','MATLAB: señales o tablas exportadas; no lector universal de raw']},
 'GC-MS':{title:'GC-MS · metabolómica y volatilómica',input:'EI/CI, full-scan/SIM, programa de horno, columna, extracción, derivatización cuando corresponda, n-alcanos y blancos.',steps:['Registrar extracción y derivatización, si se usó, junto con estándares internos, columna y secuencia. Guardar los directorios nativos completos.','Importar en MS-DIAL, MZmine GC-EI, AMDIS o software del fabricante; confirmar compatibilidad con EI/CI y full-scan/SIM.','Corregir fondo, detectar picos y deconvolucionar espectros EI coeluyentes. Integrar iones cuantificadores/confirmadores validados. No integrar el TIC como si cada pico fuera un compuesto puro.','Calcular índices de retención con n-alcanos del mismo método; alinear usando RI y espectros. Comparar biblioteca con la energía de ionización apropiada.','Revisar blancos, arrastre, artefactos de derivatización y variación de extracción. Exportar áreas por componente y muestra, RI, RT, iones y nivel de confianza.'],checks:'El índice lineal de retención para temperatura programada no es la fórmula logarítmica de Kováts isotérmica. No identificar solo por nombre o similitud.',tools:['MS-DIAL / MZmine GC-EI / AMDIS','R y Python: control, integración dirigida de exportaciones y estadística','MATLAB: señales exportadas y estadística']},
 'LC-RMN':{title:'LC-RMN · LC-NMR',input:'FID y parámetros espectrales, núcleo, campo, solvente, referencia, modo de flujo/parada o fracciones y correspondencia RT/fracción.',steps:['Conservar cada FID con sus parámetros y vínculo a la fracción o ventana cromatográfica. LC-RMN no es un archivo de espectrometría de masas.','En TopSpin, Mnova, Delta o un lector compatible: corregir filtro digital cuando aplique, apodizar, transformar Fourier y corregir fase. Elegir parámetros según la secuencia de pulsos.','Corregir línea base y referenciar ppm; revisar solvente, agua y señales de referencia. Nunca interpretar un FID con la plantilla para espectros ya procesados.','Alinear espectros compatibles, excluir regiones justificadas e integrar regiones o realizar binning documentado. Mantener separadas muestras, fracciones y dimensiones 2D.','Exportar ppm e intensidad, o tabla de integrales por región; normalizar según referencia/dilución y documentar condiciones de adquisición para cuantificación.'],checks:'Las plantillas de señal trabajan sobre regiones de espectros 1D ya fasados y referenciados. No reconstruyen experimentos 2D ni corrigen por sí solas LC-NMR en flujo.',tools:['TopSpin / Mnova / Delta (según licencia y formato)','nmrglue (Python, formatos compatibles)','R/MATLAB: exportaciones ppm-intensidad; lectores adicionales dependen del formato']},
 'LC-IMS':{title:'LC-IMS / LC-IMS-MS',input:'Conservar RT, intensidad y eje de movilidad (tiempo de llegada o 1/K₀); m/z y MS/MS solo si existe acoplamiento MS.',steps:['Identificar el tipo de movilidad: DTIMS, TWIMS, TIMS u otro. Guardar gas, calibrantes, temperatura/presión cuando corresponda, carga y método.','Importar datos nativos con MZmine/MS-DIAL o software autorizado compatible; comprobar que la exportación conserve frames y movilidad.','Detectar y agrupar features en RT × m/z × movilidad para LC-IMS-MS; no colapsar la dimensión de movilidad inadvertidamente. Para LC-IMS sin MS, usar el eje del detector disponible.','Calibrar CCS únicamente con el procedimiento apropiado al instrumento y estándares. No convertir 1/K₀, ms y CCS con una constante universal.','Alinear las dimensiones y exportar matriz de abundancias más una tabla de feature_id, RT, m/z si aplica, movilidad, unidades, carga y CCS calibrada si procede.'],checks:'FAIMS/DMS usa voltaje de compensación; no equivale directamente a tiempo de deriva o CCS. Las plantillas de señal requieren una ventana de movilidad previamente seleccionada.',tools:['MZmine: workflow de movilidad compatible','MS-DIAL / lector del fabricante según adquisición','R, Python y MATLAB: tablas y señales exportadas con unidades explícitas']},
 'GC-O':{title:'GC-O · olfatometría',input:'Registro de evaluadores codificados, sesión, muestra, RT de inicio/fin, descriptor, intensidad, detección y dilución si se usa AEDA.',steps:['Sincronizar registro sensorial y GC; medir el retardo hasta el puerto olfativo con una referencia. Registrar split, flujo, temperatura y protocolo del panel.','Conservar eventos crudos; corregir el retardo medido y asignar RI con n-alcanos del mismo método. No emparejar olores con compuestos solo por cercanía temporal.','Armonizar vocabulario con un diccionario documentado y definir ventanas antes de comparar. Mantener por separado evaluador, sesión y réplica.','Registrar también evaluaciones negativas y distinguirlas de sesiones no realizadas/datos perdidos. Calcular frecuencia usando únicamente evaluaciones completadas.','Resumir intensidad, duración y frecuencia. En AEDA conservar la serie de diluciones y reportar el mayor factor con detección conforme al protocolo; no convertir FD en concentración.'],checks:'GC-O combina percepción y señal instrumental. Intensidad sensorial no equivale a abundancia MS ni a concentración. La inferencia debe considerar medidas repetidas por evaluador y sesión.',tools:['Puerto olfativo + software de eventos del fabricante','R: stats; lme4 para modelos mixtos opcionales','Python: pandas / statsmodels','MATLAB: tablas; Statistics Toolbox para modelos mixtos']}
};
export const omicsTools=[
 ['ProteoWizard / MSConvert','Conversión MS','Gratuito y abierto; lectura de formatos nativos puede requerir bibliotecas del fabricante y Windows.','https://proteowizard.sourceforge.io/download.html','Instalar el paquete con lectores compatibles; abrir MSConvert, seleccionar un archivo de prueba, elegir mzML y exportar sin filtros no justificados. Verificar número de espectros, polaridad, RT, MS/MS y movilidad.'],
 ['MZmine','LC-MS, GC-EI, IMS','Núcleo abierto; comprobar las condiciones de funciones/ediciones adicionales.','https://mzmine.github.io/mzmine_documentation/latest/getting_started.html','Descargar instalador de plataforma; asignar RAM según equipo; abrir un archivo QC y usar el asistente de adquisición. Guardar el batch y parámetros; exportar matriz alineada y lista de features.'],
 ['MS-DIAL','LC-MS, GC-MS, IMS','Consultar licencia y compatibilidad de la distribución y bibliotecas.','https://systemsomicslab.github.io/compms/msdial/main.html','Descargar la versión oficial; crear proyecto con ionización y adquisición correctas; importar archivos y bibliotecas compatibles; ejecutar detección, deconvolución y alineamiento; revisar QC antes de exportar.'],
 ['AMDIS','GC-EI-MS','Software de NIST; las bibliotecas espectrales pueden requerir licencia aparte.','https://chemdata.nist.gov/mass-spc/amdis/','Instalar desde NIST, abrir un archivo compatible, ajustar resolución/anchura/ruido con QC y revisar componentes deconvolucionados. Seleccionar biblioteca autorizada; exportar resultados.'],
 ['MetaboAnalyst / MetaboAnalystR','Estadística e interpretación','Revisar términos del servicio y licencia del paquete.','https://www.metaboanalyst.ca/docs/RTutorial.xhtml','Seguir la instalación oficial de MetaboAnalystR y sus dependencias. Importar matriz ya revisada, declarar orientación y metadatos, guardar script e historial. Usar ejecución local si los datos no se pueden compartir.'],
 ['TopSpin','RMN','Licencias de adquisición y procesamiento con condiciones distintas.','https://www.bruker.com/de/products-and-solutions/mr/nmr-software/topspin.html','Descargar desde la cuenta Bruker, seleccionar licencia adecuada e instalar para procesamiento offline; abrir un FID de prueba con parámetros completos. Verificar Fourier, fase y referencia.'],
 ['Mnova','RMN','Comercial; licencia por módulos y posibles pruebas.','https://mestrelab.com/','Obtener instalador y licencia institucional/de prueba desde Mestrelab. Activar el módulo NMR, abrir FID compatible, procesar y exportar espectro numérico, no solo imagen.'],
 ['Delta','RMN','Licencia y limitaciones según modalidad de JEOL.','https://nmrsupport.jeol.com/','Registrar cuenta, descargar kit de procesamiento compatible y activar su licencia; el control de espectrómetro es una instalación diferente. Abrir un ejemplo y verificar exportación.'],
 ['nmrglue','RMN con Python','Código abierto.','https://nmrglue.readthedocs.io/en/latest/tutorial.html','Instalar con python -m pip install nmrglue en el entorno elegido. Seleccionar lector según fabricante; verificar dimensiones y parámetros antes de Fourier y fase.'],
 ['R / Bioconductor','Preprocesamiento y estadística','Código abierto; paquetes con licencias individuales.','https://bioconductor.org/install/','Instalar R estable compatible con Bioconductor; instalar xcms, MsExperiment y Spectra con BiocManager, validar y registrar versiones.'],
 ['Python / pyOpenMS','Preprocesamiento y estadística','Código abierto; comprobar versiones binarias compatibles.','https://pyopenms.readthedocs.io/en/latest/','Instalar Python estable soportado, crear entorno, instalar pyopenms y probar importación. No forzar la última versión de Python si aún no hay rueda compatible.'],
 ['MATLAB','Señales exportadas y estadística','De pago; toolboxes requieren licencia.','https://www.mathworks.com/help/install/ug/install-products-with-internet-connection.html','Iniciar sesión institucional en MathWorks e instalar MATLAB estable y Statistics and Machine Learning Toolbox. Bioinformatics y Signal Processing son opcionales según funciones utilizadas; comprobar con ver.']
];
export const vendors=[
 ['Agilent','GC-MS / LC-MS','MassHunter Acquisition; Qualitative/Quantitative y Explorer según equipo y licencia.','Conservar carpeta .D completa. Exportar mzML con lector compatible o señales/tablas numéricas desde el programa.','https://www.agilent.com/en/product/software-informatics/mass-spectrometry-software/data-acquisition/acquisition-for-gc-ms'],
 ['Agilent','LC-IMS-MS','MassHunter e IM-MS Browser para plataformas de movilidad compatibles.','Guardar calibrantes y método; comprobar la dimensión de movilidad después de exportar.','https://www.agilent.com/Library/usermanuals/Public/G3335-90195_IMMSBrowser_QuickStart.pdf'],
 ['Shimadzu','GC-MS / LC-MS','LabSolutions GCMS/LCMS y módulos de análisis compatibles con el equipo.','Conservar proyecto y archivos nativos; formatos y exportación dependen del modelo/versión. Verificar soporte del lector antes de convertir.','https://www.shimadzu.com/an/products/software-informatics/labsolutions-series/labsolutionsgcms/index.html'],
 ['Thermo Fisher','GC-MS / LC-MS','Xcalibur o Chromeleon según plataforma; FreeStyle y Compound Discoverer para tareas de procesamiento compatibles.','Conservar .raw y método. Exportar con lector autorizado y revisar MS1/MS2, polaridad y RT.','https://www.thermofisher.com/order/catalog/product/OPTON-30965'],
 ['Thermo Fisher','Movilidad diferencial','Si el equipo usa FAIMS, registrar voltaje de compensación y condiciones.','No convertir voltaje FAIMS directamente a CCS ni asumir compatibilidad de un flujo DTIMS/TIMS.','https://docs.thermofisher.com/r/FreeStyle-User-guide-1.8-SP3-QF1/enGUID-6F917EE5-AA45-44D3-BC90-2F77F6F4C837'],
 ['Bruker / JEOL','LC-RMN / RMN','TopSpin / Delta, según espectrómetro; el control de LC y fracciones depende del acoplamiento.','Guardar FID, parámetros, secuencia, fracción/RT y espectros procesados. Los tres fabricantes priorizados no determinan por sí solos el lector de RMN.','https://www.jeol.com/products/scientific/nmr_software/Delta5.php'],
 ['GERSTEL','GC-O acoplado a GC','ODP y registro de eventos sensoriales compatible con la configuración.','Guardar eventos, evaluador, retardo, intensidad y dilución; la compatibilidad física/software debe confirmarse con el proveedor.','https://www.gerstel.com/en/products/gco/odp4']
];
