import {ancestry, type Item} from './content';
type Lesson = [string, string];
export function enrichSchoolLessons(items: Item[]): Item[] {
 const notes=new Map<string,Lesson>();
 const review:Record<string,Lesson>={
 'lectura-datos':['Interpretar una gráfica exige leer ejes, unidades, escala y condiciones del experimento. Una tendencia puede ser creciente sin ser proporcional; proporcionalidad directa requiere razón constante. Compara valores y dispersión antes de explicar diferencias. Una gráfica describe datos, pero la explicación causal necesita evidencia adicional.','Compara dos curvas de solubilidad: identifica cuál tiene mayor valor a una temperatura y cuál cambia más en el intervalo. Son preguntas diferentes.'],
 'evidencia':['Una conclusión científica debe estar respaldada por resultados relevantes y un razonamiento explícito. Distingue observación de interpretación, y considera explicaciones alternativas. Una evidencia aislada puede ser insuficiente; reproducibilidad y controles fortalecen la conclusión. Seleccionar solo datos favorables introduce sesgo.','Si una planta tratada crece más que otra, identifica qué información falta sobre luz, agua y variación entre plantas antes de atribuir el efecto al tratamiento.'],
 'diseno-experimental':['Diseñar un experimento implica formular una pregunta medible, definir variables y establecer controles. Las réplicas permiten estimar variabilidad; un grupo de comparación ayuda a interpretar efectos. Los instrumentos deben tener resolución adecuada. Seguridad y registro fiel de resultados son parte del diseño, incluso cuando no se confirma la hipótesis.','Diseña sobre papel una comparación de disolución a dos temperaturas manteniendo masa, volumen y agitación constantes. Explica por qué repetirías cada condición.'],
 'calculos-integrados':['Resolver un problema químico requiere traducir información a magnitudes, identificar la relación pertinente y comprobar unidades. No todas las cifras del enunciado son necesarias. En estequiometría se balancea primero; en soluciones se distingue cantidad de soluto de volumen total. La plausibilidad del resultado se revisa al final.','Calcula la masa correspondiente a 0,5 mol de NaCl usando 58,44 g/mol: 29,22 g. Explica por qué multiplicas y verifica la cancelación de unidades.'],
 'estructura-propiedad':['La estructura de partículas ayuda a explicar propiedades macroscópicas, pero deben considerarse enlace, geometría e interacciones. Una sola característica no siempre determina solubilidad o punto de ebullición. Construye explicaciones que conecten modelo microscópico con una observación concreta y reconoce las condiciones de comparación.','Compara agua y un hidrocarburo: explica su mezcla limitada mediante polaridad e interacciones, sin afirmar que toda sustancia con carbono es apolar.'],
 'repaso-acumulativo':['Un repaso eficaz conecta conceptos y recupera explicaciones sin mirar apuntes. Clasificar errores ayuda a distinguir fallos de unidades, modelos o lectura. Alterna problemas de materia, soluciones, reacciones y energía, justificando la elección de cada procedimiento. Revisa después la respuesta y explica cómo corregirías tu razonamiento.','Elabora una tabla con problema, concepto, error cometido y corrección. Repite un problema equivalente días después para comprobar comprensión.']};
 for(const [slug,lesson] of Object.entries(review))notes.set('saber-'+slug,lesson);
 for(const [grade,lessons] of Object.entries(scienceLessons)) lessons.forEach((lesson,n)=>notes.set(`${grade}-p${Math.floor(n/8)+1}-u${Math.floor(n%8/4)+1}-t${n%4+1}`,lesson));
 for(const [grade,lessons] of Object.entries(chemistryLessons)) for(const [slug,lesson] of Object.entries(lessons)) notes.set(['materia','concentracion'].includes(slug)?slug:`${grade}-${slug}`,lesson);
 return items.map(topic=>{
  const lesson=notes.get(topic.id);
  if(topic.kind!=='topic'||!lesson||topic.updatedAt) return topic;
  const grade=ancestry(topic,items).find(p=>['octavo','noveno','decimo','once'].includes(p.id));
  if(!grade)return topic;
  const readings=['Ministerio de Educación Nacional · Derechos Básicos de Aprendizaje de Ciencias Naturales\nhttps://www.colombiaaprende.edu.co/sites/default/files/files_public/2022-06/DBA_C.Naturales-min.pdf'];
  if(['decimo','once'].includes(grade.id)||/quím|enlace|gas|soluci|concentraci|ácido/i.test(topic.title)) readings.push('OpenStax · Química 2ed (español)\nhttps://openstax.org/books/qu%C3%ADmica-2ed/pages/1-introduccion');
  if(/gen|ADN|herencia|mutaci|meiosis/i.test(topic.title))readings.push('Instituto Nacional de Investigación del Genoma Humano · Glosario de genética en español\nhttps://www.genome.gov/es/genetics-glossary');
  return {...topic,example:false,body:'Resumen del tema\n\n'+lesson[0],examples:lesson[1],activities:'1. Explica el ejemplo con tus propias palabras e identifica los conceptos que lo sustentan.\n\n2. Representa la situación mediante un esquema, una tabla o un cálculo con unidades, según corresponda. Distingue datos, supuestos y conclusiones.\n\n3. Propón un caso diferente donde se aplique el concepto y explica una limitación del modelo utilizado.',bibliography:'Lecturas de apoyo en español. El resumen es una explicación didáctica original; consulta el capítulo o término correspondiente.\n\n'+readings.join('\n\n')};
 });
}
export const chemistryLessons: Record<string, Record<string, Lesson>> = {
 decimo: {
 'metodo-cientifico':['Una pregunta investigable debe relacionarse con observaciones o mediciones posibles. La hipótesis propone una explicación contrastable, no una respuesta que deba confirmarse. Variable independiente es la que se modifica, dependiente la que se mide y controles las condiciones que se mantienen comparables. Una correlación no demuestra por sí sola causalidad.','Para estudiar disolución de azúcar a diferentes temperaturas, define cantidad, agitación y tamaño del sólido como condiciones a controlar. No confundas rapidez de disolución con solubilidad de equilibrio.'],
 'seguridad-laboratorio':['Los instrumentos tienen funciones y resoluciones distintas: una probeta no reemplaza siempre un material volumétrico de mayor precisión. La seguridad comienza antes de experimentar con identificación de peligros, protección y gestión de residuos. Las etiquetas y fichas de seguridad deben consultarse; no se prueban sustancias con gusto ni se mezclan productos desconocidos.','Elige entre balanza, termómetro y material volumétrico para cada magnitud. Justifica la elección y el registro de unidad y resolución.'],
 'medicion':['Medir es comparar con una referencia y expresar resultado con unidad. Análisis dimensional permite convertir y comprobar ecuaciones cancelando unidades. Las cifras comunicadas deben ser coherentes con resolución e incertidumbre; conservar muchos decimales de una calculadora no mejora una medición.','Convierte 250 mL en 0,250 L y 2,5 g/cm³ en 2500 kg/m³. Escribe factores y verifica cancelación.'],
 'materia':['Las propiedades físicas se observan sin cambiar necesariamente identidad química; las químicas describen capacidad de transformarse. Las extensivas dependen de cantidad, como masa, y las intensivas, como densidad a condiciones dadas, no. Una propiedad aislada puede ayudar a caracterizar, pero no siempre identifica inequívocamente una sustancia.','Una muestra de 54 g y 20 mL tiene ρ=2,7 g/mL. Explica qué ocurre con masa, volumen y densidad al dividir una muestra homogénea.'],
 'mezclas':['Los elementos contienen un tipo de átomo y los compuestos tienen composición química definida. Las mezclas admiten proporciones variables y pueden ser homogéneas o heterogéneas. Filtrar, destilar o decantar aprovecha propiedades diferentes; elegir técnica requiere conocer tamaño de partículas, miscibilidad o volatilidad.','Una mezcla de arena y sal en agua puede requerir filtración y recuperación del soluto por otra operación. Explica por qué el filtro no retiene la sal disuelta.'],
 'estados':['En sólidos, líquidos y gases cambian organización y movilidad de partículas. Los cambios de estado implican intercambios de energía y no necesariamente cambian composición. Durante una transición de una sustancia pura a presión fija, la temperatura puede mantenerse aunque se siga aportando calor.','Compara fusión de hielo y combustión de papel. Identifica cuál cambia identidad química y qué evidencias usarías.'],
 'modelos-atomicos':['Los modelos atómicos se construyeron para explicar evidencias como electricidad, dispersión y espectros. Rutherford introdujo un núcleo pequeño y Bohr describió niveles en un modelo limitado. El modelo cuántico representa probabilidades de encontrar electrones, no órbitas planetarias definidas. Cada modelo tiene utilidad y límites.','Relaciona dispersión de partículas con la idea de núcleo y líneas espectrales con niveles de energía. Explica por qué un modelo se modifica con nueva evidencia.'],
 'particulas':['El número atómico Z cuenta protones; el número másico A suma protones y neutrones. Los isótopos tienen igual Z y distinto número de neutrones. Los iones resultan de distinto número de electrones respecto a protones; ionizar no cambia el elemento en una transformación química ordinaria.','Para ²³Na⁺, cuenta 11 protones, 12 neutrones y 10 electrones. Distingue la carga del número másico.'],
 'masa-atomica':['La masa atómica tabulada refleja un promedio ponderado de masas isotópicas y abundancias de referencia. Por eso no tiene que ser un número entero ni coincide con el número másico de cada átomo. Las abundancias deben expresarse como fracciones y sumar uno en el modelo.','Para isótopos hipotéticos de masas 10 y 11 con abundancias 20 % y 80 %, el promedio es 10,8 unidades de masa atómica.'],
 'configuracion':['La configuración electrónica organiza ocupación de orbitales respetando límites y reglas del modelo. Pauli permite dos electrones de espín opuesto por orbital; Hund orienta ocupación de orbitales de igual energía. Los electrones de valencia ayudan a relacionar estructura y reactividad, aunque existen excepciones al llenado sencillo.','Representa oxígeno como 1s²2s²2p⁴ y cuenta seis electrones de valencia. Dibuja ocupación p sin superar dos por orbital.'],
 'tabla-periodica':['La tabla se ordena por número atómico. Períodos relacionan niveles ocupados y grupos reúnen patrones de valencia y propiedades, especialmente en elementos representativos. Los bloques se asocian a subniveles electrónicos. La posición ayuda a predecir comportamiento, pero no reemplaza datos de cada elemento.','Ubica Na y Cl por período y grupo y relaciona sus tendencias de formación de iones con electrones de valencia.'],
 'familias':['Los metales suelen conducir y presentar maleabilidad, mientras los no metales tienen propiedades diversas. Familias como alcalinos, halógenos y gases nobles muestran patrones relacionados con valencia. Estas categorías incluyen excepciones y propiedades dependientes de condiciones; no toda sustancia brillante es necesariamente un metal puro.','Compara un alcalino y un gas noble por configuración externa. Explica por qué pertenecer a un grupo no implica idéntica reactividad en todos sus elementos.'],
 'tendencias':['Radio, ionización y electronegatividad dependen de carga nuclear, apantallamiento y distribución electrónica. A lo largo de un período la atracción efectiva suele aumentar, y al bajar aparecen capas más extensas. Las tendencias son generales y pueden presentar excepciones por subniveles y apareamiento.','Compara cualitativamente radios de Na y Cl y de Li y Na. Justifica con capas y atracción, no solo con flechas memorizadas.'],
 'iones':['Un ion tiene carga neta por diferencia entre protones y electrones. El número de oxidación es una asignación formal que ayuda a seguir cambios químicos y no siempre es una carga física real. La suma de números de oxidación debe igualar la carga total de la especie.','En SO₄²⁻, usando O=−2, el azufre tiene +6. Explica por qué esto no significa que exista un ion S⁶⁺ aislado dentro del sulfato.'],
 'enlace-ionico':['El enlace iónico describe atracción entre iones en una estructura colectiva. Las sales sólidas forman redes, no necesariamente moléculas separadas. La movilidad de iones explica conducción al fundir o disolver cuando hay disociación suficiente. Energía de red y tamaño influyen en propiedades.','Representa NaCl como una red alternante. Explica por qué romper un cristal no equivale a separar una única molécula de NaCl.'],
 'enlace-covalente':['Los enlaces covalentes comparten densidad electrónica entre átomos. Lewis representa pares enlazantes y libres y permite contar electrones y cargas formales. La regla del octeto orienta muchos casos, pero no es universal y no describe por sí sola geometría ni todas las propiedades.','Dibuja H₂O con dos enlaces y dos pares libres sobre oxígeno. Verifica el total de electrones de valencia.'],
 'enlace-metalico':['El modelo metálico describe electrones deslocalizados asociados a un conjunto de centros atómicos. Ayuda a explicar conducción y deformación sin destruir inmediatamente la cohesión. Aleaciones y defectos modifican propiedades, por lo que composición y microestructura importan además del tipo de enlace.','Relaciona movilidad electrónica con conducción y compara un metal puro con una aleación sin asumir que ambos tienen igual dureza.'],
 'geometria':['Las regiones electrónicas alrededor de un átomo ayudan a predecir geometría aproximada. Pares libres también ocupan espacio. La polaridad molecular depende de geometría y suma de dipolos, no únicamente de que existan enlaces polares. Representaciones planas pueden ocultar la disposición espacial.','CO₂ tiene enlaces polares y forma lineal con compensación; H₂O angular conserva dipolo. Dibuja flechas y explica la diferencia.'],
 'intermoleculares':['Las interacciones entre partículas contribuyen a ebullición, viscosidad y solubilidad. Dispersión aparece en todas las moléculas; dipolos y puentes de hidrógeno añaden contribuciones específicas. Comparar sustancias exige considerar tamaño y forma, no solo la presencia de un grupo.','Compara dos sustancias de tamaño parecido, una capaz de donar puentes de hidrógeno y otra no. Formula una predicción cualitativa de ebullición.'],
 'formulas':['Los símbolos identifican elementos, los subíndices cuentan átomos dentro de una fórmula y los coeficientes cuentan unidades de la especie. Para compuestos iónicos se combinan cargas en proporciones neutras. La nomenclatura debe permitir recuperar composición sin cambiar identidades arbitrariamente.','Ca²⁺ y Cl⁻ forman CaCl₂. Distingue 2 CaCl₂ de CaCl₄ y explica por qué no expresan lo mismo.'],
 'oxidos':['Los óxidos son compuestos binarios con oxígeno; los peróxidos contienen el grupo O₂²⁻ en su descripción habitual. El estado de oxidación del oxígeno difiere en ambos casos. Nombrar requiere reconocer la especie y un sistema de nomenclatura coherente, no aplicar mecánicamente O=−2 a todo.','En Na₂O el oxígeno se asigna −2; en Na₂O₂ cada O se asigna −1. Comprueba neutralidad en ambas fórmulas.'],
 'hidruros-hidroxidos':['Los hidruros y los hidróxidos son familias distintas. En hidruros iónicos el hidrógeno puede asignarse −1; en hidróxidos aparece OH⁻. Los paréntesis indican grupos repetidos y no se omiten cuando hay varios. La formulación combina carga y composición de cada especie.','Ca(OH)₂ contiene dos O y dos H por unidad fórmula. Compara con CaH₂ y explica por qué sus nombres y propiedades difieren.'],
 'acidos':['Los hidrácidos escolares no contienen oxígeno y los oxoácidos sí. Las fórmulas muestran composición, pero acidez depende también de estructura y medio. Una sustancia concentrada no es necesariamente un ácido fuerte. Los nombres pueden variar entre compuesto puro y disolución acuosa.','Compara HCl(aq) y H₂SO₄ en composición. Distingue número de hidrógenos de fuerza de cada etapa de disociación.'],
 'sales':['Las sales combinan cationes y aniones; las binarias y oxisales se distinguen por composición de los aniones. Formular requiere neutralidad y reconocer grupos poliatómicos. La nomenclatura de Stock indica estados de oxidación cuando hace falta distinguirlos.','Combina Al³⁺ y SO₄²⁻ para obtener Al₂(SO₄)₃. Cuenta átomos y verifica carga total nula.'],
 'ecuaciones':['Una ecuación incluye reactivos, productos, coeficientes y, cuando corresponde, estados y condiciones. Color, precipitado o gas pueden sugerir reacción, pero necesitan contexto. El modelo debe representar sustancias identificadas; observar un cambio no basta para inventar productos.','Distingue disolver un sólido de formar un precipitado nuevo. Indica qué evidencia permitiría proponer una ecuación.'],
 'clasificacion':['Las familias de reacción describen patrones útiles como combinación, descomposición, intercambio o combustión. Una transformación puede pertenecer a más de una clasificación. El patrón no revela todos los pasos del mecanismo ni garantiza que cualquier pareja de reactivos reaccione.','La combustión de metano también es redox. Explica por qué dos clasificaciones pueden ser correctas para la misma ecuación.'],
 'balanceo':['Balancear busca coeficientes que conserven cada elemento y carga cuando corresponde. Cambiar subíndices alteraría sustancias y resolvería otro problema. El método algebraico representa cantidades con variables y establece una ecuación de conservación por elemento.','Ajusta Fe + O₂ → Fe₂O₃ como 4 Fe + 3 O₂ → 2 Fe₂O₃ y comprueba ambos elementos.'],
 'redox':['Oxidación implica aumento del número de oxidación y reducción su disminución. El oxidante se reduce y el reductor se oxida. Las semirreacciones permiten conservar electrones, masa y carga; el medio ácido o básico condiciona qué especies se emplean al ajustar.','En Zn + Cu²⁺ → Zn²⁺ + Cu, identifica transferencia de dos electrones, oxidante y reductor.'],
 'mol':['El mol mide cantidad de sustancia y se relaciona con número de entidades mediante la constante de Avogadro. Masa molar convierte gramos en moles. Debe nombrarse la entidad: átomos, moléculas o iones, pues un mol de moléculas puede contener varios moles de átomos.','18 g de agua corresponden aproximadamente a 1 mol de H₂O y 2 mol de átomos H. Distingue las entidades contadas.'],
 'composicion':['El porcentaje en masa compara aporte de cada elemento con masa total. La fórmula empírica expresa proporciones mínimas y la molecular el múltiplo correspondiente a una molécula. Para deducirlas se convierten masas a moles; usar directamente porcentajes como subíndices es incorrecto.','CH₂O tiene masa fórmula aproximada 30; una molécula con masa molar 180 g/mol y esa proporción es C₆H₁₂O₆.'],
 'calculos':['La ecuación ajustada relaciona moles y permite convertir cantidades mediante coeficientes. Para relaciones masa-masa, primero usa masa molar del reactivo, después proporción estequiométrica y finalmente masa molar del producto. El cálculo supone la reacción indicada y debe revisar pérdidas o reacciones competidoras.','2 mol de H₂ producen como máximo 2 mol de H₂O si hay oxígeno suficiente. Explica por qué no significa igual masa de hidrógeno y agua.'],
 'limitante':['El reactivo limitante se agota primero según las proporciones de la reacción y fija el máximo teórico. Comparar solo masas no sirve porque coeficientes y masas molares difieren. Divide moles disponibles por coeficiente y compara; después calcula el consumo del reactivo en exceso.','Con 3 mol de H₂ y 2 mol de O₂, limita H₂ y sobran 0,5 mol de O₂ al formar 3 mol de agua en el modelo.'],
 'rendimiento':['Pureza indica qué fracción del reactivo corresponde a la especie útil; rendimiento compara producto real y teórico. Pérdidas, reacción incompleta y productos secundarios reducen rendimiento. Un producto húmedo puede aparentar una masa excesiva; debe evaluarse pureza antes de concluir eficiencia extraordinaria.','10 g de reactivo al 80 % contienen 8 g de especie útil. Si producto teórico es 5 g y se obtienen 4 g puros, rendimiento=80 %.'],
 'modelo-gases':['Las partículas gaseosas se mueven y chocan, generando presión en paredes. El modelo ideal desprecia su volumen propio y fuerzas salvo choques. Temperatura absoluta se relaciona con energía cinética media; el comportamiento real se aparta del modelo en condiciones extremas.','A igual cantidad y volumen, calentar un gas ideal aumenta presión. Describe el cambio microscópico sin afirmar que sus partículas aumentan de tamaño.'],
 'leyes-gases':['Cada ley simplifica una relación entre variables manteniendo otras constantes. Boyle usa P y V a T fija; Charles, V y T a P fija; Gay-Lussac, P y T a V fijo. Las temperaturas deben ser absolutas y las condiciones realmente comparables.','Un gas pasa de 300 K a 600 K a presión y cantidad constantes: el volumen ideal se duplica. Contrasta con un recipiente rígido.'],
 'gas-ideal':['PV=nRT relaciona estado y cantidad y exige elegir R coherente con unidades. En una mezcla ideal, presión total suma presiones parciales y cada componente contribuye según su fracción molar. Las fracciones deben sumar uno; el modelo puede fallar a alta presión o cerca de condensación.','Si un gas representa 20 % molar de una mezcla a 100 kPa, su presión parcial ideal es 20 kPa.'],
 'proyecto':['El proyecto integra pregunta, modelo, medición y comunicación. Debe prever controles, unidades, seguridad y tratamiento de residuos, y registrar decisiones. La conclusión responde al problema y explica límites, en lugar de presentar un resultado aislado o borrar datos que no coinciden con lo esperado.','Plantea una comparación de densidades con datos suministrados. Define cómo presentarás tabla, cálculo, incertidumbre y conclusión sin identificar sustancias desconocidas por una sola propiedad.']
 },
 once: {
 'solubilidad':['Solubilidad es un límite bajo condiciones definidas; concentración es la composición de una muestra concreta. Temperatura puede afectar sólidos de distintas maneras y presión influye especialmente en gases. Las curvas deben leerse con atención al denominador, por ejemplo gramos de soluto por masa de agua.','Una curva indica 30 g por 100 g de agua. Explica por qué no equivale a 30 % en masa de solución, cuya masa sería 130 g.'],
 'concentracion':['Las unidades de concentración comparan cantidad de soluto y una base definida. Molaridad usa volumen de solución, molalidad masa de disolvente y porcentajes requieren aclarar magnitudes. ppm expresa una proporción; su equivalencia con mg/L requiere supuestos de densidad y medio.','0,50 mol en 2,0 L de solución dan 0,25 mol/L. Explica qué dato falta para obtener molalidad.'],
 'dilucion':['Diluir conserva soluto si no hay reacción, precipitación ni pérdidas. La igualdad c₁V₁=c₂V₂ usa volúmenes de solución en condiciones compatibles. Mezclar soluciones requiere sumar cantidades de soluto y conocer volumen final; no todas las mezclas presentan volúmenes exactamente aditivos.','De 0,20 L de 1,0 M aforados a 1,0 L se obtienen 0,20 M. Diferencia completar hasta un volumen y añadir ese volumen de agua.'],
 'coligativas':['Las propiedades coligativas dependen del número efectivo de partículas disueltas en modelos diluidos. Incluyen descenso de congelación y presión osmótica. La ósmosis ocurre a través de una membrana selectiva; electrolitos y no idealidad modifican la respuesta respecto de una molécula neutra.','Compara glucosa y NaCl muy diluidos a igual cantidad formal. Explica por qué disociación cambia número de partículas y por qué el modelo tiene límites.'],
 'termoquimica':['Un proceso exotérmico cede calor y uno endotérmico lo absorbe según las condiciones. Romper enlaces requiere energía y formarlos la libera; el balance determina el cambio global. Energía de activación y entalpía de reacción son conceptos diferentes y se leen en regiones distintas de un diagrama.','Una reacción exotérmica puede necesitar encendido. Explica por qué liberar energía globalmente no elimina la barrera inicial.'],
 'cinetica':['La rapidez depende de mecanismo y condiciones como concentración y temperatura. La superficie importa cuando la reacción ocurre en interfaces. Un catalizador ofrece otra ruta y acelera aproximación al equilibrio sin cambiar la constante para la misma reacción y temperatura.','Compara un perfil con y sin catalizador: cambian barreras, pero no diferencia energética entre estados inicial y final.'],
 'equilibrio':['En equilibrio dinámico continúan procesos directo e inverso a igual velocidad. Las concentraciones permanecen constantes, pero no tienen que ser iguales. La constante relaciona actividades; en modelos escolares se aproximan con concentraciones o presiones y se incluyen exponentes estequiométricos.','Para A⇌B, K≈[B]/[A] en condiciones apropiadas. Si K=4, equilibrio no significa que [A] y [B] sean iguales.'],
 'le-chatelier':['Una perturbación puede modificar composición de equilibrio, pero su efecto depende de restricciones. Cambiar temperatura puede cambiar K; variar concentración a T fija cambia el cociente de reacción. Un catalizador no desplaza equilibrio y un gas inerte puede tener efectos distintos según volumen o presión constantes.','Para una reacción gaseosa con menos moles de productos, analiza compresión a T fija. Declara qué variables se mantienen antes de predecir.'],
 'acido-base':['Fuerza describe tendencia de disociación y concentración cuánto ácido o base hay. pH es logarítmico y depende de actividad de H⁺. Neutralización requiere balance estequiométrico y el pH final depende también de especies formadas; equivalencia no implica siempre pH 7.','Compara ácido fuerte muy diluido y ácido débil concentrado sin concluir cuál tiene menor pH solo por la palabra fuerte.'],
 'titulacion':['Una titulación estima cantidad mediante titulante conocido y reacción definida. Punto final es señal observada; equivalencia es relación estequiométrica. Un tampón contiene especies conjugadas que limitan cambios pequeños de pH, con capacidad finita que depende de cantidades, no solo de su razón.','Dos tampones tienen igual pH y distinta concentración total. Explica cuál resiste mejor la misma adición pequeña y por qué.'],
 'carbono':['El carbono forma diversidad de estructuras por su capacidad de enlace. Los modelos sp³, sp² y sp se relacionan con geometrías locales tetraédrica, trigonal plana y lineal. Un doble enlace contiene componentes σ y π; la hibridación es un modelo, no un movimiento observado de orbitales.','Compara CH₄, eteno y etino por geometría alrededor de cada carbono y número de componentes σ y π.'],
 'representaciones':['Las fórmulas moleculares cuentan átomos y las estructurales muestran conectividad con distinto detalle. En fórmulas esqueléticas, vértices y extremos suelen representar carbonos y muchos hidrógenos se omiten por convenio. Deben comprobarse valencias para reconstruir una estructura y distinguir ramificación de un cambio de dibujo.','Dibuja una misma molécula de tres carbonos en forma desarrollada, condensada y esquelética. Verifica que mantenga conectividad y fórmula.'],
 'grupos-funcionales':['Un grupo funcional es un conjunto estructural asociado a patrones de propiedades y reactividad. Una molécula puede contener varios y su entorno modifica comportamiento. En una serie homóloga, miembros comparten patrón y difieren por unidades repetidas, sin tener propiedades físicas idénticas.','Identifica hidroxilo y carboxilo en una estructura que contiene ambos. Explica por qué no basta llamarla solo alcohol.'],
 'isomeria':['Isómeros comparten fórmula molecular y difieren en conectividad o disposición espacial. Los constitucionales incluyen cadena, posición y función; estereoisómeros conservan conectividad. No toda rotación de un dibujo genera un isómero distinto; hay que distinguir conformación y configuración.','Etanol y dimetil éter comparten C₂H₆O y tienen funciones diferentes. Explica por qué masa molecular no basta para identificarlos.'],
 'alcanos':['Alcanos presentan enlaces simples C–C y C–H en estructuras saturadas. La nomenclatura identifica cadena principal, sustituyentes y posiciones; cicloalcanos incorporan anillos. Tamaño, ramificación y forma afectan propiedades, por lo que una fórmula global no determina todas las características físicas.','Dibuja los dos isómeros constitucionales de C₄H₁₀ y explica cómo difieren en conectividad sin cambiar composición.'],
 'alquenos':['Los alquenos contienen enlaces dobles que restringen rotación y ofrecen reactividad de adición. Nombrar requiere localizar el doble enlace y sustituyentes. La isomería geométrica necesita sustituyentes apropiados en ambos carbonos; no aparece en todos los alquenos.','Representa adición conceptual de H₂ al eteno para formar etano y cuenta enlaces antes y después.'],
 'alquinos':['El triple enlace de un alquino incluye un componente σ y dos π y se asocia a geometría local lineal. Los alquinos pueden sufrir adiciones, pero productos dependen de condiciones y cantidad de reactivo. No se predice toda reactividad solo contando insaturaciones.','Compara C₂H₂ y C₂H₄ en geometría, hidrógenos y enlaces π. Indica qué debe cambiar para obtener el alcano correspondiente.'],
 'aromaticos':['La aromaticidad describe estabilización electrónica en sistemas cíclicos conjugados apropiados. El benceno no se interpreta como alternancia temporal de dos estructuras distintas: las formas de resonancia representan deslocalización. El término no significa que una sustancia tenga olor ni que todo anillo sea aromático.','Compara benceno y ciclohexano por tipo de enlace y estructura electrónica, no por apariencia u olor.'],
 'combustibles':['El petróleo es una mezcla que se separa y transforma para obtener fracciones y productos. La combustión completa de hidrocarburos produce principalmente CO₂ y agua en un modelo ideal; combustión incompleta puede generar CO y partículas. Energía útil e impactos requieren considerar extracción, uso y emisiones.','Ajusta CH₄ + 2 O₂ → CO₂ + 2 H₂O. Explica por qué esta ecuación ideal no describe todos los productos de una combustión real.'],
 'alcoholes':['Alcoholes tienen hidroxilo unido a carbono saturado y fenoles a un anillo aromático. El entorno modifica acidez y reactividad. Puentes de hidrógeno influyen en ebullición y solubilidad, mientras el tamaño de la parte hidrocarbonada también importa. No se deducen seguridad o uso alimentario por pertenecer a esta familia.','Compara etanol y un alcohol de cadena larga respecto a interacción con agua. Señala los dos efectos estructurales que compiten.'],
 'eteres':['Los éteres presentan un oxígeno entre dos grupos carbonados. Pueden aceptar puentes de hidrógeno, pero no donarlos mediante un O–H que no poseen. Sus propiedades difieren de alcoholes isómeros y dependen del tamaño y forma de grupos. Las semejanzas de fórmula no implican igual uso o riesgo.','Compara etanol y dimetil éter identificando qué enlace está presente solo en el alcohol y cómo afecta interacciones.'],
 'carbonilos':['El grupo carbonilo tiene enlace C=O polarizado. En aldehídos, el carbono carbonílico está unido al menos a un H; en cetonas, a dos grupos carbonados. Esa diferencia influye en reactividad y oxidación. Un oxígeno en una fórmula no demuestra por sí solo presencia de carbonilo.','Dibuja propanal y propanona, ambos C₃H₆O, y localiza el grupo que permite distinguirlos.'],
 'carboxilicos':['Los ácidos carboxílicos contienen –COOH y los ésteres –COOR. Sus propiedades dependen de estructura, interacciones y posibles equilibrios. La formación de un éster reorganiza enlaces y no consiste solo en mezclar nombres; olor no identifica de forma fiable una sustancia.','Representa conceptualmente ácido acético y etanol formando acetato de etilo y agua. Comprueba conservación de átomos.'],
 'nitrogenados':['Aminas, amidas y nitrilos contienen nitrógeno en entornos distintos. Las aminas se relacionan estructuralmente con amoniaco; las amidas incluyen un carbonilo adyacente y los nitrilos un enlace C≡N. El entorno electrónico cambia basicidad y reactividad, por lo que no se clasifican solo por tener N.','Identifica una amida en un enlace peptídico y explica por qué no se comporta igual que una amina aislada.'],
 'ruptura':['Homólisis reparte electrones de un enlace entre los fragmentos y puede formar radicales. Heterólisis asigna el par a un fragmento y puede formar iones. Nucleófilos aportan electrones y electrófilos los aceptan; estos papeles dependen de estructura y condiciones.','Dibuja ruptura homolítica y heterolítica de un enlace sencillo con símbolos de electrones y verifica carga total.'],
 'sustitucion':['Adición incorpora grupos a una estructura, sustitución reemplaza uno y eliminación suele formar una insaturación perdiendo grupos. Estas categorías describen cambios globales y no siempre un mecanismo único. Seguir átomos permite identificar qué enlaces se rompen y forman.','Compara adición a eteno y eliminación desde un derivado saturado. Señala el cambio en enlaces π sin inventar condiciones experimentales.'],
 'oxidacion':['En moléculas orgánicas, mayor enlace a elementos electronegativos y menor a H suele corresponder a oxidación del carbono. Alcoholes primarios y secundarios presentan rutas distintas; productos dependen de condiciones. Oxidación no significa necesariamente combustión y reducción no se limita a eliminar oxígeno.','Ordena conceptualmente alcohol primario, aldehído y ácido carboxílico según oxidación del carbono funcional.'],
 'esterificacion':['Esterificación forma ésteres y su reacción inversa por agua es hidrólisis en condiciones apropiadas. Saponificación describe hidrólisis básica de ésteres como grasas, formando carboxilatos. Las moléculas de jabón combinan regiones afines al agua y a materiales apolares.','Explica con un dibujo cómo un agregado de moléculas anfipáticas puede ayudar a dispersar grasa en agua, sin preparar mezclas corrosivas.'],
 'polimerizacion':['Los polímeros contienen unidades enlazadas repetidamente y pueden formarse por mecanismos diferentes. Estructura del monómero y proceso determinan cadena, ramificación y propiedades. Una transformación concertada reorganiza enlaces en una etapa del modelo; no toda polimerización o reacción orgánica es concertada.','Representa eteno y un fragmento de polietileno. Distingue la unidad repetitiva del número variable de unidades de una cadena.'],
 'carbohidratos':['Los carbohidratos incluyen moléculas simples y cadenas con funciones energéticas y estructurales. Los enlaces y la organización cambian propiedades y digestibilidad. Compartir unidades de glucosa no hace idénticos almidón y celulosa; la conexión entre unidades también importa.','Compara almidón y celulosa por función y tipo de organización, sin concluir que todo carbohidrato tiene sabor dulce.'],
 'lipidos':['Los lípidos son un conjunto diverso de sustancias con propiedades de interacción con agua características. Grasas, aceites y fosfolípidos tienen estructuras y funciones diferentes. Saturación, longitud y geometría de cadenas influyen en comportamiento; una membrana es una organización dinámica, no una pared rígida de grasa.','Dibuja un fosfolípido con región polar y colas apolares y explica su organización en una bicapa acuosa.'],
 'proteinas':['Las proteínas son cadenas de aminoácidos unidos por enlaces peptídicos. Secuencia, plegamiento y asociación determinan función. Desnaturalización altera estructuras superiores sin implicar necesariamente ruptura de todos los enlaces peptídicos; su reversibilidad depende del sistema y condiciones.','Compara romper una cadena y cambiar su plegamiento. Explica por qué ambas situaciones pueden afectar función mediante mecanismos distintos.'],
 'enzimas':['Las enzimas catalizan reacciones mediante estructuras y condiciones apropiadas y no cambian el equilibrio global. Actividad depende de sustrato, temperatura, pH y regulación. Las rutas metabólicas conectan transformaciones y balances de materia y energía; la abundancia de una sustancia no mide directamente rapidez de su producción.','Una enzima pierde actividad al calentarse demasiado. Diferencia aumento inicial de velocidad y pérdida de estructura a condiciones extremas.'],
 'acidos-nucleicos':['ADN y ARN son polímeros de nucleótidos con funciones de información, expresión y regulación. Un nucleótido contiene azúcar, fosfato y base. Complementariedad permite reconocimiento y copia; secuencias de bases importan más que contar únicamente nucleótidos. No todo ARN codifica una proteína.','Compara azúcar y bases habituales de ADN y ARN y conecta esas diferencias con sus representaciones escolares.'],
 'electroquimica':['Las pilas convierten una reacción espontánea en energía eléctrica y la electrólisis usa energía para impulsar una transformación. Oxidación ocurre en ánodo y reducción en cátodo, aunque signos eléctricos dependen del sistema. Corrosión implica procesos redox y puede controlarse mediante estrategias apropiadas.','Sigue electrones desde oxidación de Zn hacia reducción de Cu²⁺ en un modelo de pila. Distingue flujo electrónico y movimiento de iones.'],
 'materiales':['Las propiedades de un material dependen de estructura, aditivos y procesamiento. Renovable describe origen, biodegradable transformación bajo condiciones y reciclable posibilidad dentro de un sistema. Estas etiquetas no son equivalentes. El ciclo de vida incluye producción, uso y destino final.','Un plástico de origen vegetal no es necesariamente biodegradable en el mar. Explica qué condiciones y evidencias habría que conocer.'],
 'agua':['Evaluar agua requiere indicadores físicos, químicos y biológicos según el uso. Claridad no demuestra potabilidad y una sola medición de pH no identifica todos los contaminantes. Tratamientos separan o transforman diferentes componentes y pueden generar residuos que deben gestionarse.','Compara filtración de partículas y eliminación de sustancias disueltas. Explica por qué agua transparente puede requerir otras comprobaciones.'],
 'atmosfera':['Efecto invernadero, contaminación del aire y pérdida de ozono estratosférico son procesos distintos que pueden relacionarse. Gases de efecto invernadero interactúan con radiación térmica; el ozono tiene papeles diferentes según altura. Evaluar causas e impactos exige distinguir mecanismo y escala temporal.','Compara CO₂ y partículas contaminantes: identifica efectos que no son equivalentes y evita explicar cambio climático como un agujero por donde entra calor.'],
 'sostenibilidad':['La química verde busca prevenir peligros y residuos desde el diseño. Comparar alternativas exige considerar materiales, energía, rendimiento y destino de productos, no una única etiqueta. Una propuesta escolar debe explicitar datos, supuestos y límites y no presentar cualquier sustitución como automáticamente segura.','Compara dos opciones de empaque con una tabla de masa, reutilización, transporte y gestión local. Explica qué información falta para decidir.']
 }
};
// Original school-level explanations and worked prompts; stable IDs preserve uploaded resources.
export const scienceLessons: Record<string, Lesson[]> = {
 octavo: [
 ['La homeostasis mantiene variables internas dentro de intervalos compatibles con la vida. Un receptor detecta cambios, un centro integra información y un efector responde. En retroalimentación negativa, la respuesta reduce la desviación; no significa detener toda actividad. El equilibrio interno es dinámico porque el organismo intercambia materia y energía continuamente.','Al aumentar la temperatura corporal, sudoración y cambios circulatorios favorecen pérdida de calor. Dibuja estímulo, receptor, respuesta y retorno hacia el intervalo habitual.'],
 ['Las neuronas transmiten señales eléctricas a lo largo de su membrana y se comunican mediante sinapsis, muchas de ellas químicas. El sistema nervioso central integra información y los nervios conectan órganos y tejidos. Un reflejo puede producir una respuesta rápida sin una decisión consciente previa, aunque la información también llegue al encéfalo.','Retirar la mano de una superficie caliente ilustra un circuito reflejo. Ordena receptor, neurona sensitiva, integración y respuesta muscular sin realizar una prueba de exposición al calor.'],
 ['Las hormonas son mensajeros químicos liberados por células y glándulas. Viajan hasta células con receptores adecuados, de modo que no todas responden igual. El sistema endocrino participa en crecimiento, metabolismo y reproducción, y trabaja junto al nervioso. Sus mecanismos de regulación incluyen retroalimentación que ajusta secreción a las necesidades del organismo.','Insulina y glucagón participan en regulación de glucosa. Usa un esquema de aumento y disminución de señales sin convertirlo en indicaciones de tratamiento.'],
 ['La excreción elimina productos del metabolismo y ayuda a regular agua, sales y pH. Los riñones filtran y luego reabsorben o secretan sustancias, por lo que la orina no es simplemente sangre sin células. Pulmones y otros órganos también eliminan productos. Excreción se distingue de expulsar alimentos no digeridos.','Compara eliminación de CO₂ por pulmones con formación de orina. Explica por qué ambas se relacionan con metabolismo y la defecación tiene otro papel principal.'],
 ['La defensa incluye barreras como piel y mucosas y respuestas celulares que reconocen amenazas. La inmunidad innata actúa de forma amplia y la adaptativa desarrolla respuestas específicas y memoria. Inflamación no significa siempre infección. Las vacunas entrenan respuestas protectoras; los antibióticos no actúan contra los virus.','Clasifica piel, anticuerpos y células fagocíticas según su función. Explica por qué lavarse las manos y vacunarse contribuyen mediante mecanismos diferentes.'],
 ['Huesos, articulaciones y músculos trabajan juntos para sostener y mover el cuerpo. Los músculos generan tensión al contraerse y suelen actuar en conjuntos antagonistas. El hueso es tejido vivo que se remodela; también protege órganos y participa en reserva mineral y producción de células sanguíneas.','Al flexionar el codo cambia la acción de músculos antagonistas. Representa huesos como palancas y señala articulación y fuerza muscular.'],
 ['Los organismos regulan intercambio de agua, gases y sustancias con estructuras adaptadas a su ambiente. Plantas controlan pérdida de agua mediante estomas; animales emplean mecanismos variados de osmorregulación. Compartir una función no exige órganos idénticos. Comparar requiere relacionar estructura, necesidad y condiciones de vida.','Compara una planta terrestre y un pez de agua dulce respecto al agua. Describe un desafío de regulación para cada uno y evita atribuirles mecanismos idénticos.'],
 ['Sueño, alimentación, movimiento y entorno influyen en sistemas corporales que actúan conjuntamente. Sustancias como alcohol y nicotina alteran comunicación y funcionamiento del organismo; sus efectos dependen de múltiples factores. El autocuidado incluye buscar información fiable y apoyo de adultos o profesionales cuando existe una preocupación de salud.','Analiza un anuncio que promete rendimiento inmediato por una sustancia. Distingue afirmación publicitaria, evidencia y riesgos sin experimentar con su consumo.'],
 ['La mitosis distribuye cromosomas duplicados y contribuye al crecimiento y reparación. La meiosis reduce el número cromosómico y genera diversidad mediante recombinación y distribución de cromosomas. La duplicación del ADN ocurre antes de las divisiones correspondientes; número de cromosomas y cantidad de ADN no significan lo mismo.','Si una especie tiene 2n=8, los gametos normalmente tienen n=4. Compara ese resultado con células hijas de mitosis.'],
 ['La reproducción asexual puede generar descendencia a partir de un progenitor sin fusión de gametos. La sexual combina material genético y suele aumentar variación entre descendientes. Ambas estrategias tienen ventajas y límites según el ambiente; asexual no significa ausencia absoluta de variación porque pueden ocurrir mutaciones.','Compara un esqueje y una semilla de una planta. Explica qué diferencias de origen y variabilidad esperas.'],
 ['Durante la pubertad cambian sistemas corporales por regulación hormonal, con ritmos individuales variables. La reproducción humana implica gametos y fecundación. El ciclo menstrual incluye cambios ováricos y uterinos; su duración puede variar y una representación de 28 días es un modelo, no una regla para todas las personas.','Elabora un esquema conceptual de ciclo ovárico y uterino. Evita usar un calendario escolar simplificado para predecir días sin posibilidad de embarazo.'],
 ['La salud sexual incluye información, respeto, consentimiento y acceso a atención. Algunas ITS pueden no producir síntomas. El preservativo usado correcta y consistentemente reduce riesgo de muchas ITS y de embarazo; otros anticonceptivos no protegen contra ITS. Las decisiones y dudas personales requieren orientación profesional y servicios apropiados para adolescentes.','Compara protección frente a embarazo y frente a ITS como preguntas diferentes. Identifica fuentes oficiales y recursos de apoyo sin pedir experiencias personales a compañeros.'],
 ['Los electrones de valencia participan de forma importante en enlaces y reactividad. La electronegatividad describe tendencia relativa a atraer electrones de un enlace. Estos conceptos ayudan a comparar sustancias, pero no permiten explicar toda propiedad con una sola cifra ni asignan cargas reales completas a cada átomo.','Compara cómo se comparten electrones en H₂ y HCl. Señala por qué compartir no siempre significa repartir por igual.'],
 ['En sólidos iónicos, cationes y aniones forman redes; en enlaces covalentes se comparten electrones. La estructura explica diferencias de fusión y conducción. Los iones necesitan movilidad para conducir: una sal sólida y su disolución pueden comportarse de forma diferente. No todos los compuestos covalentes son moléculas pequeñas.','Contrasta sal sólida, sal disuelta y azúcar disuelta mediante modelos de partículas. Predice qué disolución conduce mejor y justifica sin probar electricidad doméstica.'],
 ['Los cambios físicos modifican estado o distribución sin cambiar necesariamente identidad química. Una reacción forma especies nuevas. Gas, color o temperatura son indicios que deben interpretarse: burbujas también aparecen al hervir. Una mezcla conserva componentes que pueden separarse por propiedades apropiadas.','Compara burbujas por ebullición y por reacción. Indica qué información adicional permite distinguirlas sin asumir que toda burbuja demuestra reacción.'],
 ['Una ecuación química representa reorganización de átomos de reactivos hacia productos. En reacciones ordinarias se conserva cada elemento; ajustar coeficientes respeta esa conservación. Las fórmulas no se alteran para balancear porque cambiarían las sustancias. En un sistema cerrado también se conserva masa total.','2 H₂ + O₂ → 2 H₂O conserva cuatro H y dos O. Dibuja partículas y explica qué ocurre si se escapa un producto gaseoso de un recipiente abierto.'],
 ['El modelo cinético describe partículas gaseosas en movimiento continuo. Difusión ocurre por dispersión de partículas; compresión reduce separación media, no necesariamente tamaño de cada partícula. La presión se relaciona con choques contra paredes y el modelo ideal simplifica fuerzas y volumen molecular.','Representa con puntos el mismo gas antes y después de comprimirlo. Conserva número y tamaño de puntos y cambia el espacio disponible.'],
 ['Presión, volumen, temperatura y cantidad describen un estado gaseoso. La temperatura absoluta se expresa en kelvin y se relaciona con energía cinética media en el modelo. Para interpretar una variación debe señalarse qué otras variables permanecen constantes; no toda expansión es efecto exclusivo del calentamiento.','Convierte 27 °C a aproximadamente 300 K. Explica por qué duplicar grados Celsius no equivale a duplicar temperatura absoluta.'],
 ['Boyle relaciona presión y volumen a temperatura y cantidad constantes. Charles relaciona volumen y temperatura absoluta a presión constante; Gay-Lussac, presión y temperatura a volumen constante. Son modelos útiles en condiciones apropiadas y deben comprobarse mediante tablas y gráficas.','Si el volumen se reduce de 2 L a 1 L manteniendo temperatura y cantidad, la presión ideal se duplica. Identifica las condiciones indispensables.'],
 ['La ley combinada compara dos estados de una cantidad fija de gas. PV=nRT incorpora cantidad de sustancia y exige unidades coherentes con R. A presiones altas o cerca de condensación, las interacciones hacen menos adecuado el modelo ideal; una fórmula no elimina esos límites.','Antes de usar P₁V₁/T₁=P₂V₂/T₂, revisa que no haya entrada o salida de gas. Explica cómo una fuga invalidaría el cálculo.'],
 ['Temperatura y calor no son sinónimos: temperatura caracteriza estado térmico y calor es energía transferida por diferencia de temperatura. Energía interna incluye contribuciones microscópicas del sistema. Dos cuerpos a igual temperatura pueden tener distintas energías por masa y composición.','Una taza y una piscina a la misma temperatura no contienen la misma cantidad de materia. Explica por qué el termómetro no mide toda su energía interna.'],
 ['La primera ley expresa conservación de energía. Con trabajo sobre el sistema positivo, ΔU=Q+W. Calentar y comprimir pueden aumentar energía interna; expandirse haciendo trabajo puede disminuirla. Siempre deben declararse sistema y signos antes de sustituir valores.','Un sistema recibe 100 J de calor y realiza 30 J de trabajo sobre el entorno: su energía interna aumenta 70 J con esa convención.'],
 ['Una máquina térmica transforma parte del calor recibido en trabajo y cede otra parte al entorno. La segunda ley limita esa conversión en ciclos; no se obtiene eficiencia del 100 % con una única fuente térmica. La eficiencia se calcula como trabajo útil dividido por calor de entrada.','Si recibe 500 J y produce 150 J de trabajo, su eficiencia es 30 %. Calcula el calor restante en un ciclo idealizado con balance energético.'],
 ['Motores y refrigeradores intercambian energía de formas diferentes. Un refrigerador requiere trabajo para transferir calor desde una región fría a otra más caliente. Conducción, convección y radiación también intervienen en ambiente y atmósfera, y pueden actuar simultáneamente.','La parte posterior de una nevera puede liberar calor mientras enfría el interior. Explica de dónde proviene la energía cedida al ambiente.'],
 ['Una oscilación es un cambio repetido alrededor de una posición de equilibrio. Una onda mecánica transmite una perturbación y energía mediante un medio; las partículas no viajan necesariamente con la onda a lo largo de toda la distancia. Se distinguen oscilaciones transversales y longitudinales.','En una cuerda ondulante, un punto puede subir y bajar mientras la perturbación avanza. Distingue movimiento local y propagación.'],
 ['Amplitud describe máxima separación respecto al equilibrio; período, duración de un ciclo; frecuencia, ciclos por segundo; longitud de onda, separación espacial entre puntos equivalentes. Frecuencia y período se relacionan por f=1/T. No debe confundirse amplitud con rapidez.','Una oscilación de período 0,5 s tiene frecuencia 2 Hz. Dibuja dos ondas con igual frecuencia y distinta amplitud.'],
 ['La rapidez de propagación depende del medio y tipo de onda y cumple v=λf para una onda periódica. En una frontera puede haber reflexión y transmisión. Al pasar a otro medio suele conservarse frecuencia impuesta por la fuente, mientras cambian rapidez y longitud de onda.','Si v=10 m/s y f=5 Hz, λ=2 m. Explica qué pasaría con λ si la rapidez se reduce a la mitad con la misma fuente.'],
 ['El sonido es una onda mecánica y necesita un medio. Frecuencia se relaciona con tono e intensidad con transferencia de energía; timbre depende de componentes del sonido. Resonancia aumenta respuesta cerca de frecuencias propias. El cuidado auditivo considera intensidad y duración, sin realizar pruebas con sonidos dañinos.','Compara dos instrumentos que emiten la misma nota. Explica por qué pueden reconocerse aunque compartan frecuencia fundamental.'],
 ['La contaminación del aire incluye partículas y gases emitidos o formados por reacciones. Transporte y transformación modifican concentraciones lejos de la fuente. Un contaminante invisible puede ser importante; olor o aspecto no bastan para evaluar calidad. La prevención requiere identificar fuentes y usar datos adecuados.','Compara una emisión directa de humo con formación de un contaminante secundario. Distingue fuente, transporte y reacción.'],
 ['Las defensas de seres vivos incluyen barreras físicas, sustancias y respuestas de comportamiento. Su eficacia depende del entorno y de otros organismos. Plantas también detectan daños y activan respuestas; no tienen un sistema nervioso animal. Una adaptación tiene beneficios y costes, no perfección universal.','Compara espinas y compuestos defensivos de una planta con caparazón o escape en animales. Relaciona cada estrategia con su función.'],
 ['Microorganismos participan en fermentaciones, producción de sustancias y tratamiento de residuos. Su actividad depende de condiciones controladas y de la especie utilizada. No todos son patógenos, pero cultivos desconocidos no deben manipularse como práctica doméstica. La industria selecciona procesos y verifica calidad.','Analiza el papel de levaduras en producción de pan mediante un esquema de transformación de azúcares, sin cultivar muestras ambientales desconocidas.'],
 ['Un proyecto científico empieza con una pregunta que puede contrastarse y variables definidas. Los datos se registran con unidades y condiciones; conclusiones distinguen observaciones y explicaciones. Una respuesta que contradice la hipótesis puede ser valiosa si el procedimiento está bien documentado.','Propón investigar cómo cambia tiempo de fusión de hielo con aislamiento, bajo supervisión. Define variable medida, controles y una tabla antes de comenzar.']
 ],
 noveno: [
 ['Los cromosomas contienen ADN y genes; los alelos son variantes de una región genética. Genotipo describe variantes y fenotipo características observables que pueden depender también del ambiente. Un rasgo complejo suele involucrar varios genes, por lo que los ejemplos de un gen son modelos limitados.','Usa Aa para representar dos alelos en un modelo. Explica por qué una letra mayúscula no significa que el alelo sea mejor o más frecuente.'],
 ['Durante meiosis se separan cromosomas homólogos y después cromátidas, produciendo células con una dotación reducida. La distribución independiente se aplica a loci no ligados o suficientemente separados bajo ciertas condiciones. Recombinación genera nuevas combinaciones; no todos los genes se heredan independientemente.','Dibuja dos pares de cromosomas y sus posibles combinaciones en gametos. Indica cómo el ligamiento modifica un modelo simple.'],
 ['Los cuadros de Punnett representan probabilidades de combinaciones, no resultados obligatorios para una familia pequeña. El modelo mendeliano requiere especificar dominancia y segregación. Cada nuevo descendiente no “completa” proporciones previas; las probabilidades no tienen memoria.','En Aa×Aa, las probabilidades genotípicas son 1/4 AA, 1/2 Aa y 1/4 aa. Explica por qué cuatro descendientes no garantizan esa distribución exacta.'],
 ['En dominancia incompleta el heterocigoto muestra un fenotipo intermedio; en codominancia se detectan aportes de ambos alelos. La herencia ligada al sexo depende de ubicación cromosómica. Estas situaciones amplían modelos sencillos y no invalidan la separación de alelos durante meiosis.','Compara una flor de color intermedio con expresión de dos variantes detectables. Explica por qué intermedio no significa que los alelos se mezclen permanentemente.'],
 ['El ADN está formado por nucleótidos y dos cadenas complementarias. La replicación conserva una cadena original en cada molécula hija y sintetiza otra. Complementariedad ayuda a copiar información, aunque existen errores y mecanismos de reparación. Duplicar ADN precede a distribución celular, no crea por sí solo dos células.','Si una secuencia es ACGT, escribe su complemento indicando orientación cuando se represente. Distingue complementariedad de igualdad de secuencias.'],
 ['La transcripción produce ARN a partir de información del ADN. En la traducción, el ribosoma relaciona codones del ARN mensajero con aminoácidos mediante el sistema de traducción. No todo ARN se traduce: también existen ARN con funciones estructurales y reguladoras.','Explica por qué copiar ADN a ARN y construir una proteína son procesos diferentes. Identifica el papel del ribosoma.'],
 ['Las mutaciones cambian secuencias y pueden alterar proteínas o regulación, aunque muchas tienen efectos pequeños o neutros. Su impacto depende de posición y contexto. Mutaciones somáticas y de la línea germinal tienen distinta posibilidad de transmisión a descendencia. La variación no aparece porque el organismo “la necesite”.','Un cambio en un codón puede conservar aminoácido por redundancia del código. Explica por qué no toda mutación modifica visiblemente el fenotipo.'],
 ['El análisis genético aporta información sobre variantes, parentesco o ciertos riesgos, pero no predice de forma absoluta toda característica. Su uso implica privacidad, consentimiento y posibles consecuencias sociales. Los debates deben separar evidencia científica, incertidumbre y valores, sin clasificar personas como genéticamente superiores.','Analiza un caso ficticio de compartir datos genéticos. Identifica beneficios, limitaciones y quién debería autorizar su uso.'],
 ['Las explicaciones evolutivas se evalúan mediante evidencias y predicciones. La selección natural explica cambios poblacionales por diferencias heredables en reproducción, no por esfuerzo individual para adquirir lo necesario. La ciencia revisa modelos cuando nuevos datos permiten contrastarlos mejor.','Compara “la población cambió por selección de variantes” con “cada individuo decidió adaptarse”. Señala qué explicación puede contrastarse genéticamente.'],
 ['Fósiles, anatomía, distribución geográfica y secuencias moleculares aportan evidencias complementarias de parentesco. Homología implica origen evolutivo compartido, aunque la función actual difiera; analogía puede surgir por convergencia. Ninguna evidencia aislada describe toda la historia.','Compara extremidades anteriores de vertebrados y distingue patrón de huesos compartido de similitud por cumplir una misma función.'],
 ['La selección natural actúa sobre variación heredable en un ambiente, produciendo diferencias de éxito reproductivo. Las poblaciones evolucionan a lo largo de generaciones; un individuo puede aclimatarse sin cambiar por ello las frecuencias genéticas poblacionales. Adaptación depende del contexto y no implica perfección.','En una población con variantes de color, cambia el ambiente. Explica cómo puede cambiar frecuencia de variantes sin que el ambiente fabrique directamente el color necesario.'],
 ['La historia de la Tierra abarca escalas mucho mayores que una vida humana. Cambios geológicos y climáticos modifican ambientes y oportunidades, y extinciones alteran diversidad. Las líneas de tiempo ayudan a ordenar acontecimientos, pero correlación temporal no establece una causa única.','Representa una escala de millones de años y ubica eventos con fuentes. Explica por qué no todos los procesos ocurren a la misma velocidad.'],
 ['La especie puede definirse con criterios reproductivos, morfológicos o evolutivos según el caso. Las categorías taxonómicas organizan diversidad y se revisan con evidencia. Un criterio reproductivo no se aplica de igual manera a fósiles o reproducción asexual.','Explica qué información usarías para clasificar un fósil y por qué no puedes probar directamente su compatibilidad reproductiva.'],
 ['La organización celular, metabolismo y parentesco ayudan a clasificar organismos. Procariota no equivale a un único grupo sin diferencias: bacterias y arqueas presentan historias y rasgos distintos. Eucariotas incluyen diversidad mayor que animales y plantas. Las clasificaciones científicas pueden actualizarse.','Compara células bacterianas, vegetales y animales mediante núcleo, pared y otras estructuras, evitando clasificar únicamente por tamaño.'],
 ['Un árbol filogenético representa hipótesis de relaciones evolutivas; los nodos indican ancestros comunes. Cercanía en la página no determina parentesco y girar ramas en un nodo no cambia relaciones. Las puntas no representan necesariamente una escala de progreso.','Compara dos árboles con ramas rotadas y determina si expresan las mismas relaciones. Busca ancestros compartidos, no distancia visual.'],
 ['La biodiversidad incluye variación genética, especies y ecosistemas. Conservación debe considerar hábitat, conectividad, usos y comunidades humanas. El número de especies de una lista depende también del esfuerzo de observación, por lo que comparar lugares exige métodos equivalentes.','Diseña observación de biodiversidad local sin capturar ni dañar organismos. Registra tiempo, área y criterios para comparar resultados.'],
 ['Una solución es una mezcla homogénea en la escala considerada. Solubilidad indica cantidad que puede disolverse bajo condiciones definidas; concentración indica lo que una muestra contiene. Saturación supone equilibrio con la fase pertinente y puede cambiar con temperatura y, para gases, presión.','Compara una solución concentrada de un soluto muy soluble con otra saturada de uno poco soluble. Explica por qué concentrada y saturada no son sinónimos.'],
 ['Las fuerzas entre partículas influyen en viscosidad, tensión superficial, volatilidad y solubilidad. Dispersión existe en todas las partículas y puentes de hidrógeno requieren estructuras apropiadas. “Lo semejante disuelve lo semejante” orienta, pero no sustituye analizar interacciones y condiciones.','Compara agua y un aceite mediante polaridad e interacciones. Distingue inmiscibilidad de ausencia total de cualquier interacción.'],
 ['Los porcentajes deben indicar masa/masa, masa/volumen o volumen/volumen. Molaridad usa litros de solución y molalidad kilogramos de disolvente. Cambiar denominador cambia el significado; las etiquetas deben leerse con unidades antes de hacer conversiones.','5 % m/v significa 5 g por 100 mL de solución. No significa automáticamente 5 g por 100 g.'],
 ['Diluir reduce concentración al añadir disolvente si se conserva cantidad de soluto y no hay reacción. Preparar una solución requiere distinguir volumen final de volumen añadido. Las etiquetas informan composición y riesgos y no deben usarse para mezclar productos domésticos arbitrariamente.','Diluir 20 mL de 1 M hasta 100 mL produce 0,20 M. Indica qué cantidades se conservan y cuáles cambian.'],
 ['Arrhenius describe ácidos y bases en agua mediante especies características; Brønsted–Lowry, transferencia de protones; Lewis, aceptación o donación de pares electrónicos. Cada modelo tiene alcance distinto. Una misma sustancia puede actuar diferente según con qué interactúe.','En NH₃ + H₂O ⇌ NH₄⁺ + OH⁻, identifica donador y receptor de protón y los pares conjugados.'],
 ['El pH se relaciona logarítmicamente con actividad de H⁺ y en soluciones escolares diluidas suele aproximarse mediante concentración. Los indicadores cambian en intervalos, no miden cualquier pH exactamente. pH+pOH≈14 es una relación usual para agua a 25 °C, no una constante universal.','Una diferencia de una unidad de pH corresponde aproximadamente a un factor diez en actividad de H⁺. Compara pH 3 y 4.'],
 ['Neutralización combina comportamiento ácido-base y puede formar sales y agua según reactivos. El pH final depende de proporciones y especies; no siempre es 7. Sus aplicaciones requieren control de cantidades y seguridad, porque neutralizar puede liberar calor.','Representa H⁺ + OH⁻ → H₂O en una idealización acuosa. Explica qué pasa si queda ácido en exceso, sin mezclar productos de limpieza.'],
 ['Los sistemas biológicos regulan pH mediante mecanismos químicos y fisiológicos. En el ambiente, pH afecta solubilidad y disponibilidad de sustancias. Una lectura aislada no describe toda la capacidad amortiguadora ni calidad de agua; hacen falta contexto y otras mediciones.','Dos aguas con igual pH pueden responder distinto a una perturbación. Explica la idea de amortiguación sin probar sustancias desconocidas.'],
 ['Posición se define respecto de un sistema de referencia. Desplazamiento compara posición final e inicial; distancia suma recorrido. Velocidad incluye dirección y rapidez es escalar. Un viaje de ida y vuelta puede tener distancia positiva y desplazamiento nulo.','Caminar 3 m hacia el este y volver al inicio suma 6 m de distancia y cero desplazamiento. Calcula rapidez media si dura 6 s.'],
 ['En MRU la velocidad es constante y posición cambia linealmente con tiempo. La pendiente de x frente a t representa velocidad. Una línea horizontal indica posición constante; una pendiente negativa no significa necesariamente disminuir rapidez, sino movimiento en sentido contrario.','Para x=2+3t en metros y segundos, posición inicial es 2 m y velocidad 3 m/s. Obtén posición a los 4 s.'],
 ['La aceleración es cambio de velocidad por tiempo. En aceleración constante se usan relaciones como v=v₀+at. Caída libre ideal considera gravedad y desprecia resistencia del aire; el signo depende del eje elegido. Aceleración puede existir aunque la rapidez disminuya.','Con v₀=0 y a=2 m/s², después de 3 s la velocidad es 6 m/s. Distingue esa velocidad del desplazamiento.'],
 ['En movimiento circular uniforme cambia dirección de velocidad aunque rapidez sea constante, por lo que existe aceleración centrípeta. En el tiro parabólico ideal se combinan movimientos horizontal uniforme y vertical acelerado. Ambos modelos requieren supuestos y un marco de referencia.','Explica por qué un objeto en una curva puede acelerar sin aumentar rapidez. En un lanzamiento ideal, identifica qué componente cambia por gravedad.'],
 ['La luz presenta comportamientos que se describen con modelos ondulatorios y cuánticos según el fenómeno. El espectro incluye radiaciones de diferentes frecuencias; visible es solo una parte. Las ondas electromagnéticas no necesitan un medio material para propagarse.','Ordena radio, visible y rayos X por frecuencia. Explica por qué invisible no significa inexistente ni todas las radiaciones tienen los mismos efectos.'],
 ['Reflexión devuelve luz desde una superficie y refracción cambia su propagación al entrar en otro medio. Espejos y lentes forman imágenes según geometría y propiedades ópticas. Una imagen virtual puede verse aunque no se proyecte directamente en una pantalla.','Dibuja rayos de un espejo plano y ubica imagen aparente. Explica por qué no hay un objeto real detrás del espejo.'],
 ['La comunicación óptica codifica información en señales luminosas. Las fibras guían luz bajo condiciones apropiadas mediante reflexión interna y diseño del material. Pérdidas, dispersión y detectores limitan transmisión. La tecnología se comprende conectando modelo físico y componentes, no solo su uso cotidiano.','Representa emisor, canal y receptor de un enlace óptico. Identifica dónde podría perderse o deformarse información.'],
 ['Una medición necesita unidad, instrumento y estimación de su limitación. Repetir ayuda a evaluar dispersión, pero no elimina todos los sesgos. Argumentar científicamente conecta afirmación, datos y razonamiento y reconoce lo que el diseño no permite concluir.','Mide conceptualmente un tiempo con resolución limitada y reporta cifras coherentes. Explica por qué muchos decimales no garantizan exactitud.']
 ]
};
