// Fields: name, category, purpose, requirements, official access, license category, license note, license source.
export const additionalSoftware:string[][]=[
 ['AmberTools','Preparación','Preparación de sistemas, parametrización y análisis; incluye herramientas como LEaP y cpptraj.','Conda o compiladores C/C++/Fortran según instalación.','https://ambermd.org/GetAmber.php','Código abierto','Gratuito · GPL y otras licencias abiertas por componente.','https://ambermd.org/GetAmber.php'],
 ['Amber','Dinámica molecular','Simulaciones moleculares aceleradas en CPU/GPU.','Licencia independiente de AmberTools; hardware compatible.','https://ambermd.org/GetAmber.php','De pago','Distribución con licencia y tarifas propias; no confundir con AmberTools.','https://ambermd.org/GetAmber.php'],
 ['GROMACS','Dinámica molecular','Simulaciones de biomoléculas, solventes y membranas.','CPU; GPU opcional y bibliotecas según compilación. Preparar topología y campo de fuerza.','https://manual.gromacs.org/current/download.html','Código abierto','Gratuito · LGPL 2.1.','https://www.gromacs.org/about.html'],
 ['LAMMPS','Dinámica molecular','Dinámica clásica para materiales, polímeros y partículas.','Paquetes opcionales, MPI/GPU según el cálculo y la instalación.','https://www.lammps.org/','Código abierto','Gratuito · GPLv2.','https://doc.lammps.org/stable/Intro_opensource.html'],
 ['OpenMM','Dinámica molecular','Simulación molecular programable desde Python.','Python; plataforma CPU o GPU compatible y campo de fuerza.','https://docs.openmm.org/latest/userguide/','Código abierto','Gratuito · licencias abiertas por componente.','https://github.com/openmm/openmm'],
 ['NAMD','Dinámica molecular','Simulación de grandes sistemas biomoleculares.','Preparación de estructura, topología y parámetros; CPU/GPU según versión.','https://www.ks.uiuc.edu/Research/namd/','Gratuito con condiciones','Licencia propia para usos permitidos; revisar condiciones comerciales y de redistribución.','https://www.ks.uiuc.edu/Research/namd/license.html'],
 ['CP2K','Dinámica molecular','Dinámica ab initio, DFT y simulación de sistemas moleculares y periódicos.','Instalación científica con bibliotecas numéricas; MPI opcional.','https://www.cp2k.org/download','Código abierto','Gratuito · GPL.','https://www.cp2k.org/about'],
 ['Quantum ESPRESSO','Cálculos','Estructura electrónica de materiales con ondas planas y pseudopotenciales.','Bibliotecas numéricas y pseudopotenciales adecuados; MPI opcional.','https://www.quantum-espresso.org/','Código abierto','Gratuito · GPL.','https://www.quantum-espresso.org/'],
 ['NWChem','Cálculos','Química cuántica y simulación molecular, incluidos cálculos paralelos.','Bibliotecas numéricas; compilación o distribución compatible.','https://nwchemgit.github.io/','Código abierto','Gratuito · licencia ECL 2.0.','https://github.com/nwchemgit/nwchem'],
 ['VMD','Visualización','Visualización de biomoléculas y trayectorias de dinámica molecular.','Aplicación de escritorio; los complementos pueden tener requisitos adicionales.','https://www.ks.uiuc.edu/Research/vmd/','Gratuito con condiciones','Sin tarifa para los usos indicados por UIUC; licencia propia y restricciones comerciales.','https://www.ks.uiuc.edu/Research/vmd/current/LICENSE.html'],
 ['UCSF ChimeraX','Visualización','Estructuras moleculares, mapas de densidad y representaciones científicas.','Escritorio y gráficos compatibles; extensiones desde Toolshed.','https://www.rbvi.ucsf.edu/chimerax/','Gratuito con condiciones','Gratuito para usos no comerciales permitidos; uso comercial requiere licencia aparte.','https://www.rbvi.ucsf.edu/chimerax/docs/license.html'],
 ['PyMOL · edición comercial','Visualización','Representación molecular y preparación de figuras con distribución y soporte comercial.','Aplicación de escritorio y suscripción/licencia correspondiente.','https://pymol.org/','De pago','Suscripciones comerciales y académicas; condiciones educativas específicas.','https://www.pymol.org/buy.html'],
 ['PyMOL · código abierto','Visualización','Base abierta del visualizador molecular PyMOL.','Compilación o distribución comunitaria; difiere de la edición comercial.','https://github.com/schrodinger/pymol-open-source','Código abierto','Código con licencia permisiva; revisar dependencias y distribución.','https://pymol.org/'],
 ['Jmol / JSmol','Visualización','Visor molecular de escritorio o integrado en páginas web.','Jmol requiere Java; JSmol funciona en el navegador sin Java.','https://jmol.sourceforge.net/download/','Código abierto','Gratuito · LGPL.','https://jmol.sourceforge.net/'],
 ['3Dmol.js / py3Dmol','Visualización','Visualización molecular en la web y en cuadernos Python.','Navegador con WebGL; py3Dmol para cuadernos.','https://github.com/3dmol/3Dmol.js','Código abierto','Gratuito · BSD.','https://github.com/3dmol/3Dmol.js'],
 ['Mol*','Visualización','Visualización web de macromoléculas, complejos y estructuras biológicas.','Navegador compatible; integración propia requiere herramientas JavaScript.','https://molstar.org/','Código abierto','Gratuito · MIT.','https://github.com/molstar/molstar'],
 ['OVITO Basic','Visualización','Visualización y análisis de simulaciones atomísticas y partículas.','Aplicación de escritorio; revisar formatos de trayectoria.','https://www.ovito.org/','Código abierto','Basic gratuito; licencias MIT/GPL por distribución y componente.','https://www.ovito.org/manual/licenses/index.html'],
 ['OVITO Pro','Visualización','Herramientas avanzadas para análisis y automatización de simulaciones.','Aplicación de escritorio con licencia Pro.','https://www.ovito.org/','De pago','Edición propietaria de pago; distinta de Basic.','https://www.ovito.org/manual/licenses/index.html'],
 ['MDAnalysis','Análisis de trayectorias','Selecciones, distancias, RMSD y análisis de dinámica molecular.','Python; estructura y trayectoria compatibles.','https://www.mdanalysis.org/','Código abierto','Gratuito · LGPL 2.1+.','https://www.mdanalysis.org/about/'],
 ['MDTraj','Análisis de trayectorias','Procesamiento y análisis de trayectorias moleculares desde Python.','Python y archivos de topología/trayectoria.','https://www.mdtraj.org/','Código abierto','Gratuito · LGPL 2.1+.','https://www.mdtraj.org/1.9.6/index.html'],
 ['Gaussian','Cálculos','Estructura electrónica y propiedades moleculares.','Licencia y distribución autorizada para la plataforma.','https://gaussian.com/','De pago','Software propietario; cotización según uso y plataforma.','https://gaussian.com/pricing/'],
 ['GaussView','Visualización','Preparación de entradas y visualización de resultados de Gaussian.','Licencia propia; para calcular se necesita el motor Gaussian.','https://gaussian.com/gaussview6/','De pago','Interfaz comercial; no implica licencia del motor.','https://gaussian.com/pricing/'],
 ['Q-Chem','Cálculos','Métodos de estructura electrónica y propiedades espectroscópicas.','Licencia y entorno compatible con la distribución adquirida.','https://www.q-chem.com/','De pago','Licencia comercial; solicitar cotización académica o empresarial.','https://www.q-chem.com/purchase/'],
 ['AMS · Amsterdam Modeling Suite','Cálculos','Suite de química molecular y materiales, con distintos motores.','Licencia, módulos y plataforma compatibles.','https://www.scm.com/downloads/','De pago','Precio por módulos, núcleos, duración y tipo de institución; prueba disponible.','https://www.scm.com/contact-us/price-quote/'],
 ['BIOVIA Materials Studio','Cálculos','Modelado y simulación de materiales con entorno gráfico.','Licencia institucional/comercial y requisitos de los módulos elegidos.','https://www.3ds.com/products/biovia/materials-studio','De pago','Suite propietaria; consultar licencia y cotización con el proveedor.','https://www.3ds.com/products/biovia/materials-studio']
];
export const existingLicenses:Record<string,[string,string,string]>={
 'ORCA':['Gratuito con condiciones','Gratuito para uso académico/personal; licencia comercial de FACCTs. No es código abierto.','https://www.faccts.de/orca/'],
 'Extensiones de PySCF':['Según componente','Cada extensión declara su propia licencia; comprobar antes de instalar.','https://pyscf.org/user/extensions.html'],
 'Avogadro':['Código abierto','Gratuito · núcleo BSD; revisar licencias de componentes incluidos.','https://avogadro.cc/'],
 'OPI · ORCA Python Interface':['Código abierto','Interfaz abierta; el motor ORCA conserva su licencia independiente.','https://www.faccts.de/orca/']
};
