import 'server-only';
import {env} from 'cloudflare:workers';
import {cookies} from 'next/headers';
import {createClient,type User,type Session} from '@supabase/supabase-js';
export const authEnv=()=>env as unknown as {DB:D1Database;SUPABASE_URL?:string;SUPABASE_PUBLISHABLE_KEY?:string;AUTH_READY?:string;ADMIN_EMAIL?:string;SITE_OWNER_EMAIL?:string;SITE_ORIGIN?:string};
export function authConfigured(){const e=authEnv();return !!(e.SUPABASE_URL&&e.SUPABASE_PUBLISHABLE_KEY&&e.AUTH_READY==='true');}
export function authClient(){const e=authEnv();if(!authConfigured())throw new Error('AUTH_UNAVAILABLE');return createClient(e.SUPABASE_URL!,e.SUPABASE_PUBLISHABLE_KEY!,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});}
export async function digest(value:string){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)))].map(b=>b.toString(16).padStart(2,'0')).join('');}
export async function managedUser():Promise<User|null>{if(!authConfigured())return null;const token=(await cookies()).get('aula_session')?.value;if(!token)return null;const active=await authEnv().DB.prepare('SELECT user FROM login_sessions WHERE hash=? AND expires>?').bind(await digest(token),Math.floor(Date.now()/1000)).first<{user:string}>();if(!active)return null;const {data,error}=await authClient().auth.getUser(token);return !error&&data.user?.email_confirmed_at&&data.user.id===active.user?data.user:null;}
export function isTeacherEmail(email?:string){return !!email&&[authEnv().ADMIN_EMAIL,authEnv().SITE_OWNER_EMAIL].filter(Boolean).some(e=>e!.toLowerCase()===email.toLowerCase());}
export async function establishSession(session:Session,secure:boolean){const expires=Math.min(session.expires_at||0,Math.floor(Date.now()/1000)+3600);if(expires<=Date.now()/1000)throw new Error('INVALID_SESSION');await authEnv().DB.prepare('INSERT INTO login_sessions(hash,user,expires) VALUES(?,?,?) ON CONFLICT(hash) DO UPDATE SET expires=excluded.expires').bind(await digest(session.access_token),session.user.id,expires).run();(await cookies()).set('aula_session',session.access_token,{httpOnly:true,secure,sameSite:'strict',path:'/',maxAge:expires-Math.floor(Date.now()/1000)});}
export async function clearSession(){const jar=await cookies();const token=jar.get('aula_session')?.value;if(token)await authEnv().DB.prepare('DELETE FROM login_sessions WHERE hash=?').bind(await digest(token)).run();jar.delete('aula_session');}
export async function throttle(key:string,max=12){const db=authEnv().DB;const now=Math.floor(Date.now()/1000);await db.batch([db.prepare('DELETE FROM auth_attempts WHERE expires<=?').bind(now),db.prepare('DELETE FROM login_sessions WHERE expires<=?').bind(now)]);const result=await db.prepare('INSERT INTO auth_attempts(key,count,expires) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET count=count+1 RETURNING count').bind(await digest(key),now+900).first<{count:number}>();return !!result&&result.count<=max;}
export type Student={id:string;email:string;name:string;institution:string;requested:string;approved:string;status:string;created:string;updated:string};
export async function studentRecord(user:User){return authEnv().DB.prepare('SELECT * FROM students WHERE id=?').bind(user.id).first<Student>();}
