import type {Item} from './content';
const make=(id:string,kind:string,title:string,extra:Partial<Item>={}):Item=>({id,kind,title,status:'published',position:0,...extra});
// Editable course spaces, not an institutional degree plan or authored teaching materials.
const courses:[string,string,string,string,string[]][]=[
 ['general-i','rama-0','Química general I','Interpretar la estructura de la materia y resolver relaciones cuantitativas.', ['Estructura y periodicidad|Modelos atómicos y orbitales|Tendencias periódicas','Enlace y estructura|Geometría y enlace químico|Interacciones intermoleculares','Cálculos químicos|Estequiometría y reactivo limitante|Gases y soluciones']],
 ['general-ii','rama-0','Química general II','Relacionar energía, equilibrio y reactividad en sistemas químicos.', ['Energía y espontaneidad|Entalpía y calorimetría|Entropía y energía de Gibbs','Equilibrios en solución|Equilibrio ácido-base|Solubilidad y complejación','Transformaciones|Leyes de velocidad|Celdas y potenciales electroquímicos']],
 ['inorganica-avanzada','sub-coordinacion','Química inorgánica avanzada','Relacionar estructura electrónica, coordinación y propiedades de compuestos inorgánicos.', ['Complejos metálicos|Simetría y geometría de coordinación|Campo cristalino y campo de ligandos','Reactividad|Sustitución de ligandos|Transferencia electrónica','Aplicaciones|Catálisis organometálica|Química bioinorgánica']],
 ['organica-avanzada','sub-sintesis-organica','Química orgánica avanzada','Argumentar mecanismos y proponer rutas de síntesis a partir de estructura y reactividad.', ['Mecanismos|Efectos electrónicos y estéricos|Control cinético y termodinámico','Selectividad|Estereoselectividad|Quimioselectividad y grupos protectores','Síntesis|Análisis retrosintético|Evaluación de rutas sintéticas']],
 ['analitica-cuantitativa','sub-analisis-clasico','Química analítica cuantitativa','Planear determinaciones cuantitativas e interpretar su calidad metrológica.', ['Medición|Muestreo y preparación de muestras|Incertidumbre y trazabilidad','Métodos clásicos|Gravimetría|Volumetría y curvas de valoración','Calidad|Calibración y materiales de referencia|Validación de métodos']],
 ['instrumental','sub-analisis-instrumental','Análisis instrumental avanzado','Seleccionar técnicas instrumentales atendiendo a la matriz y a la pregunta analítica.', ['Espectroscopía|UV-visible y fluorescencia|Absorción y emisión atómica','Espectrometría|Ionización y analizadores de masas|Fragmentación e interpretación espectral','Diseño analítico|Preparación y efectos de matriz|Validación y aseguramiento de calidad']],
 ['cromatografia','sub-separaciones','Cromatografía y técnicas acopladas','Comparar estrategias de separación y detección para mezclas complejas.', ['Fundamentos|Retención, selectividad y resolución|Eficiencia y ensanchamiento de bandas','Plataformas|Cromatografía de gases y GC-MS|Cromatografía líquida y LC-MS','Desarrollo de métodos|Optimización de separación|Identificación y cuantificación']],
 ['termodinamica','sub-termodinamica','Termodinámica química','Aplicar funciones termodinámicas a fases, mezclas y reacciones.', ['Leyes y funciones|Primera y segunda ley|Potenciales termodinámicos','Sistemas multicomponente|Potencial químico y actividad|Equilibrio de fases','Reacciones|Equilibrio químico|Dependencia con temperatura y presión']],
 ['cinetica-catalisis','sub-cinetica','Cinética y catálisis','Construir y contrastar modelos cinéticos con evidencia experimental.', ['Modelos cinéticos|Leyes integradas y ajuste|Dependencia con la temperatura','Mecanismos|Estado estacionario y preequilibrio|Reacciones consecutivas y paralelas','Catálisis|Catálisis homogénea y heterogénea|Cinética enzimática']],
 ['cuantica-computacional','sub-quimica-cuantica','Química cuántica y computacional','Interpretar modelos moleculares y evaluar sus aproximaciones.', ['Fundamentos|Operadores y ecuación de Schrödinger|Modelos cuánticos sencillos','Estructura electrónica|Orbitales moleculares|Métodos ab initio y funcionales de densidad','Cálculo molecular|Geometrías y frecuencias|Energías y límites del modelo']],
 ['bioquimica-avanzada','sub-metabolismo','Bioquímica avanzada','Integrar regulación metabólica, bioenergética y evidencia experimental.', ['Estructura y función|Interacciones proteína-ligando|Regulación enzimática','Metabolismo|Rutas centrales y bioenergética|Integración y regulación metabólica','Investigación bioquímica|Diseño de ensayos|Interpretación de datos bioquímicos']],
 ['ambiental-avanzada','rama-6','Química ambiental avanzada','Analizar el destino de sustancias en sistemas ambientales.', ['Procesos ambientales|Especiación y biodisponibilidad|Transporte y partición','Transformaciones|Degradación y persistencia|Procesos fotoquímicos y redox','Evaluación|Diseño de monitoreo|Tratamiento y prevención de contaminación']],
 ['quimiometria','sub-quimiometria','Quimiometría','Extraer información de datos químicos mediante estadística y modelos validados.', ['Diseño y datos|Diseño de experimentos|Preprocesamiento, escalado y datos faltantes','Exploración multivariada|Análisis de componentes principales (PCA)|Agrupamiento y detección de valores atípicos','Modelado y validación|Regresión multivariada y PLS|Validación cruzada, prueba externa y fuga de información']],
 ['metabolomica','sub-metabolomica','Metabolómica','Diseñar e interpretar estudios de metabolitos con controles analíticos y criterios de identificación.', ['Diseño del estudio|Enfoques dirigidos y no dirigidos|Muestreo, aleatorización y controles de calidad','Adquisición y procesamiento|LC-MS, GC-MS y RMN|Detección, alineamiento y normalización de señales','Interpretación|Anotación e identificación de metabolitos|Estadística, rutas metabólicas y reproducibilidad']],
 ['volatilomica','sub-volatilomica','Volatilómica','Estudiar perfiles de compuestos volátiles mediante muestreo, análisis instrumental y tratamiento de datos.', ['Muestreo de volátiles|Espacio de cabeza y microextracción (SPME)|Blancos, contaminación y estabilidad de muestra','Caracterización|GC-MS y separación de volátiles|Índices de retención y bibliotecas espectrales','Interpretación de perfiles|Quimiometría de perfiles volátiles|Aplicaciones, validación y límites de inferencia']],
];
export const universityContent:Item[]=[
 make('sub-quimiometria','subbranch','Quimiometría',{parent:'rama-3',position:30,description:'Estadística, diseño experimental y análisis multivariado de datos químicos.'}),
 make('sub-metabolomica','subbranch','Metabolómica',{parent:'rama-5',position:31,description:'Estudio de metabolitos y sus variaciones en sistemas biológicos.'}),
 make('sub-volatilomica','subbranch','Volatilómica',{parent:'rama-3',position:32,description:'Estudio de perfiles de compuestos volátiles; también denominada volatolómica. Conecta química analítica, metabolómica y ambiente.'}),
];
for(const [slug,parent,title,objectives,units] of courses){const id='pregrado-'+slug;
 universityContent.push(make(id,'course',title,{parent,position:courses.findIndex(c=>c[0]===slug),description:objectives,objectives,example:true,body:'Espacio de asignatura de pregrado. Organización inicial editable: ajustar requisitos, profundidad y actividades al programa universitario. Las guías, clases, ejercicios y videos se publicarán progresivamente.'}));
 units.forEach((entry,position)=>{const [title,...topics]=entry.split('|');const unit=id+'-u'+(position+1);universityContent.push(make(unit,'unit',title,{parent:id,position,example:true}));topics.forEach((title,n)=>universityContent.push(make(unit+'-t'+(n+1),'topic',title,{parent:unit,position:n,example:true,description:'Tema propuesto para '+courses.find(c=>c[0]===slug)![2]+'.',body:'Espacio preparado para desarrollar este tema a nivel de pregrado. La explicación, los ejemplos, las actividades y la bibliografía están pendientes de incorporar.'})));});
}
