import type {Item} from './content';
const cellReading='NHGRI · Célula (glosario en español)\nhttps://www.genome.gov/es/genetics-glossary/Celula';
const moleculeReading='OpenStax · Química 2ed: estructura molecular y polaridad\nhttps://openstax.org/books/qu%C3%ADmica-2ed/pages/7-6-estructura-molecular-y-polaridad';
const lessons:Record<string,Partial<Item>>={
 'realidad-aumentada':{
  description:'Aprende a interpretar modelos de células y moléculas mediante exploración visual, comparación y registro de evidencias.',
  body:'Ruta de trabajo\n\n1. Estructura celular: reconoce componentes y relaciona su organización con sus funciones.\n2. Geometría molecular: interpreta la distribución espacial de los átomos y diferencia forma, enlace y polaridad.\n3. Actividades de observación: formula una pregunta, registra resultados y construye una explicación.\n\nPuedes trabajar con la vista de práctica sin cámara. El giro, el tamaño y la posición permiten explorar el esquema: no modifican las propiedades del objeto representado. Los modelos son apoyos didácticos; no sustituyen una micrografía ni una medición experimental.\n\nCada tema contiene una guía de estudio, un ejemplo, una actividad con entrega y lecturas en español. Las presentaciones y los archivos que publique el docente se consultan en el tema correspondiente.',
  objectives:'Identificar estructuras celulares y explicar sus funciones.\nRelacionar estructuras de Lewis con modelos moleculares sencillos.\nDistinguir observación, interpretación y limitaciones de una representación.\nComunicar conclusiones mediante dibujos rotulados, tablas y argumentos basados en evidencia.'
 },
 'realidad-aumentada-unidad-1':{description:'De la organización celular a la relación entre estructura y función.',objectives:'Comparar células animales, vegetales y procariotas; interpretar la escala y las convenciones de un esquema.'},
 'realidad-aumentada-unidad-2':{description:'De los enlaces en el papel a la distribución espacial de los átomos.',objectives:'Distinguir geometría electrónica y molecular; justificar la polaridad en ejemplos sencillos.'},
 'realidad-aumentada-unidad-3':{description:'Una secuencia para observar, registrar, comparar y argumentar.',objectives:'Producir un registro reproducible y una conclusión que reconozca los límites del modelo.'},
 'realidad-aumentada-tema-1':{
  title:'Estructura celular: componentes, funciones y comparación',description:'Guía de exploración de células con ejemplos y una actividad comparativa.',
  body:'La célula como sistema\n\nUna célula intercambia materia y energía con el entorno, utiliza información genética y mantiene procesos organizados. La membrana delimita la célula y regula intercambios; el citoplasma contiene los componentes donde ocurren numerosas reacciones. El material genético participa en la continuidad de la información y los ribosomas en la síntesis de proteínas.\n\nOrganización y funciones\n\nEn las células eucariotas, el núcleo aloja la mayor parte del ADN. Las mitocondrias participan en la respiración celular; el retículo endoplasmático y el aparato de Golgi intervienen en la producción, modificación y transporte de sustancias. Las células vegetales suelen presentar pared celular y una gran vacuola; las fotosintéticas poseen cloroplastos. También tienen mitocondrias. Las procariotas carecen de núcleo rodeado por membrana, pero poseen ADN y ribosomas.\n\nCómo leer el modelo\n\nSelecciona una estructura y relaciona su ubicación con una función. Los colores son convenciones gráficas: no demuestran el color real del orgánulo. Un esquema tampoco permite deducir tamaños exactos ni contiene necesariamente todos los componentes. Agrandar el dibujo mejora su lectura, pero no equivale a aumentar la resolución de un microscopio.',
  examples:'Comparación razonada\n\nUna célula de una hoja fotosintética puede representar cloroplastos, pared, vacuola y mitocondrias. Una célula animal no tiene cloroplastos ni pared celular. Ambas requieren membrana, información genética y maquinaria para producir proteínas. Una célula de raíz puede carecer de cloroplastos: no todas las células vegetales realizan fotosíntesis.\n\nError frecuente: interpretar que un orgánulo no existe porque no aparece en un dibujo simplificado. Primero comprueba qué tipo de célula y qué propósito tiene la representación.',
  activities:'Taller: comparar sin confundir el modelo con la realidad · 35–45 minutos\n\n1. Antes de abrir el visor, dibuja cómo imaginas una célula y escribe dos preguntas.\n2. En el aula visual, selecciona un modelo celular. Identifica membrana, citoplasma y las estructuras disponibles; registra nombre, función y evidencia del dibujo.\n3. Compara dos tipos celulares. Si uno no está disponible en el visor, utiliza una ilustración rotulada del material docente e identifica la fuente.\n4. Elabora una tabla: estructura | presente en el modelo A | presente en B | función | duda pendiente. No interpretes una ausencia gráfica como ausencia biológica.\n5. Corrige tu dibujo inicial y explica dos cambios en tu comprensión.\n\nEntrega: dibujos propios rotulados, tabla comparativa y una conclusión de 100–150 palabras. Evaluación: precisión de funciones, comparación sustentada y reconocimiento de dos límites del esquema. Ampliación: explica por qué tamaño aparente y tamaño real requieren una escala.',
  bibliography:cellReading
 },
 'realidad-aumentada-tema-2':{
  title:'Geometría molecular: forma, enlaces y polaridad',description:'Relaciona la estructura de Lewis con la forma de moléculas sencillas.',
  body:'Del dibujo plano a la distribución espacial\n\nLa estructura de Lewis representa enlaces y pares no enlazantes, pero no muestra por sí sola la forma tridimensional. El modelo de repulsión de regiones electrónicas permite estimar la disposición alrededor de un átomo central. Un enlace doble o triple cuenta como una región al determinar la geometría básica.\n\nDos geometrías que conviene distinguir\n\nLa geometría electrónica incluye todas las regiones; la molecular describe la posición de los átomos. Dos regiones originan una disposición lineal; tres, trigonal plana; cuatro, tetraédrica. Los pares no enlazantes pueden hacer que la forma molecular difiera de esa disposición.\n\nForma y polaridad\n\nLa polaridad depende de los enlaces y de su orientación. No basta con encontrar enlaces polares: hay que considerar si sus contribuciones se compensan. Girar una representación cambia la perspectiva del observador, no los ángulos internos ni la identidad molecular. Los modelos de bolas y barras simplifican la distribución electrónica.',
  examples:'El CO₂ es lineal y sus dipolos de enlace se compensan. El agua es angular y posee un dipolo neto. El CH₄ es tetraédrico. Estos ejemplos muestran por qué la fórmula molecular debe acompañarse de información estructural.\n\nPregunta de aplicación: si dos representaciones del agua aparecen orientadas de manera distinta, ¿qué evidencia usarías para reconocer que corresponden a la misma molécula?',
  activities:'Taller: del papel al modelo · 40 minutos\n\n1. Dibuja las estructuras de Lewis de H₂O, CO₂ y CH₄. Comprueba el número total de electrones de valencia.\n2. Completa una tabla con átomo central, regiones electrónicas, pares no enlazantes, geometría molecular y predicción de polaridad.\n3. Explora los modelos disponibles en el aula visual. Para los ausentes utiliza tus dibujos o material del docente. Conserva la misma molécula mientras cambias su orientación.\n4. Haz dos dibujos desde perspectivas distintas e indica qué propiedades permanecen iguales. No midas ángulos moleculares usando distancias aparentes en una proyección plana.\n5. Explica por qué identificar una molécula exige algo más que contar esferas de colores.\n\nEntrega: tabla, estructuras de Lewis y explicación breve de la polaridad. Evaluación: conteo electrónico, distinción entre las dos geometrías y argumento coherente. Ampliación: analiza NH₃ y compara la influencia de sus pares no enlazantes con la del agua.',
  bibliography:moleculeReading
 },
 'realidad-aumentada-tema-3':{
  title:'Observación científica: registro, comparación y conclusiones',description:'Desarrolla una investigación guiada con modelos celulares o moleculares.',
  body:'Observar con una pregunta\n\nLa observación científica es un registro intencional y organizado. Antes de explorar, establece qué quieres comparar y qué información necesitas. Una pregunta útil para el aula visual es: ¿qué características de una representación permanecen iguales al cambiar su orientación? Evita preguntas que el modelo no puede resolver, como medir la actividad metabólica de una célula dibujada.\n\nSeparar registro e interpretación\n\nUna observación describe lo visible: número de componentes, etiquetas o relaciones espaciales representadas. Una interpretación utiliza conocimientos para explicar ese registro. Escribe ambos en columnas distintas. La confianza de una conclusión depende de la calidad y pertinencia de la evidencia, no de la cantidad de detalles decorativos del dibujo.\n\nComparaciones justas\n\nCuando compares modelos, identifica qué cambia y conserva criterios comunes: vista, escala de presentación y estructuras que vas a describir. El cambio de tamaño en pantalla es una condición de visualización, no un crecimiento del organismo ni una expansión real de la molécula.\n\nComunicar límites\n\nUn modelo puede omitir componentes, usar colores convencionales o representar procesos de manera estática. Estas limitaciones deben aparecer en el informe. Una conclusión válida responde a la pregunta inicial y distingue lo que se encontró de lo que aún habría que investigar con otras fuentes o instrumentos.',
  examples:'Registro: “El modelo muestra dos esferas pequeñas unidas a una mayor”. Interpretación: “La leyenda identifica una molécula de agua”. La primera frase describe el dibujo; la segunda requiere consultar cómo se codifican los elementos.\n\nRegistro: “Al girar el modelo se superponen dos componentes en pantalla”. Conclusión incorrecta: “Desapareció una parte de la molécula”. Explicación alternativa: la proyección oculta temporalmente un componente.\n\nEn biología, encontrar una etiqueta de cloroplasto apoya la identificación del modelo, pero no demuestra que una célula real esté realizando fotosíntesis en ese momento.',
  activities:'Investigación guiada · 45–60 minutos\n\n1. Elige célula o molécula y formula una pregunta que el visor permita explorar. Escribe una predicción razonada.\n2. Registra modelo, fecha, fuente y condiciones iniciales. Trabaja sin cámara si no la necesitas.\n3. Cambia una condición de visualización cada vez: orientación, tamaño o posición. Describe qué cambia en la imagen y qué permanece.\n4. Completa una tabla de al menos tres observaciones: condición | observación literal | interpretación | explicación alternativa.\n5. Contrasta una interpretación con una lectura en español. Indica título y enlace.\n6. Redacta una conclusión que responda a la pregunta; incluye dos límites del modelo y una pregunta nueva.\n\nEntrega: pregunta, predicción, procedimiento reproducible, tabla y conclusión de 150–200 palabras. Criterios: pregunta comprobable en el visor, separación entre observación e inferencia, evidencia suficiente y límites explícitos. No se exige grabar personas ni utilizar la cámara.\n\nAutoevaluación: ¿otra persona podría repetir mis pasos? ¿Mi conclusión afirma algo que no observé? ¿Qué dato adicional necesito?',
  bibliography:'Lecturas para contrastar las interpretaciones según el modelo elegido:\n\n'+cellReading+'\n\n'+moleculeReading
 }
};
/** Only upgrade unedited defaults; a teacher save remains authoritative. */
export function enrichVisualLessons(items:Item[]):Item[]{return items.map(item=>lessons[item.id]&&!item.updatedAt?{...item,...lessons[item.id]}:item);}
