import type {Item} from './content';
export const volatileCourseId='pregrado-volatilomica';
export const volatileLabId='volatilomica-gcms-python';
export type Reading={title:string;citation:string;url:string;language:string;use:string};
export const volatileReadings:Record<string,Reading>={
 quechers:{title:'Método QuEChERS original',citation:'Anastassiades, Lehotay, Štajnbaher y Schenck (2003). Fast and Easy Multiresidue Method Employing Acetonitrile Extraction/Partitioning and Dispersive Solid-Phase Extraction for the Determination of Pesticide Residues in Produce. Journal of AOAC International, 86, 412–431.',url:'https://doi.org/10.1093/jaoac/86.2.412',language:'Inglés · acceso según licencia',use:'Conocer el alcance original en residuos de plaguicidas y discutir por qué no equivale a una extracción universal del volatiloma.'},
 gc:{title:'Principios de GC-MS',citation:'Agilent. Gas chromatography mass spectrometry basic principles.',url:'https://www.agilent.com/en/product/gas-chromatography-mass-spectrometry-gc-ms/gcms-fundamentals',language:'Inglés · guía del fabricante',use:'Revisar separación, ionización y detección antes de interpretar cromatogramas.'},
 gcxgc:{title:'GC×GC y espectrometría de masas',citation:'Comprehensive two-dimensional gas chromatography–mass spectrometry. Nature Reviews Methods Primers (2025). DOI: 10.1038/s43586-024-00379-3.',url:'https://www.nature.com/articles/s43586-024-00379-3',language:'Inglés · acceso según licencia',use:'Revisar modulación, separación bidimensional y tratamiento de datos.'},
 sirius:{title:'SIRIUS y espectros en tándem',citation:'Dührkop et al. (2019). SIRIUS 4: a rapid tool for turning tandem mass spectra into metabolite structure information. Nature Methods, 16, 299–302.',url:'https://www.nature.com/articles/s41592-019-0344-8',language:'Inglés · artículo científico',use:'Examinar qué información de MS/MS necesita el método y sus límites frente a espectros EI.'},
 metacyc:{title:'MetaCyc y redes metabólicas',citation:'Caspi et al. (2016). The MetaCyc database of metabolic pathways and enzymes and the BioCyc collection of pathway/genome databases. Nucleic Acids Research, 44, D471–D480.',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC4702838/',language:'Inglés · acceso abierto',use:'Distinguir rutas curadas de predicciones en bases específicas de organismos.'},
 gephi:{title:'Visualización de redes con Gephi',citation:'Gephi. Quickstart y tutoriales oficiales.',url:'https://gephi.org/quickstart/',language:'Inglés · documentación abierta',use:'Preparar nodos y aristas, importar una red y describir el significado de sus conexiones.'},
 cytoscape:{title:'Cytoscape para redes biomoleculares',citation:'Shannon et al. (2003). Cytoscape: a software environment for integrated models of biomolecular interaction networks. Genome Research, 13, 2498–2504.',url:'https://genome.cshlp.org/content/13/11/2498',language:'Inglés · artículo del software',use:'Relacionar atributos de nodos con una red sin confundir visualización y validación.'},
 sensors:{title:'Narices electrónicas: sensores y procesamiento',citation:'Electronic Noses: From Gas-Sensitive Components and Practical Applications to Data Processing. Sensors (2024), 24, 4806.',url:'https://www.mdpi.com/1424-8220/24/15/4806',language:'Inglés · revisión abierta',use:'Examinar transductores, aplicaciones y procesamiento de patrones.'},
 ecology:{title:'Biosíntesis y función de los volátiles vegetales',citation:'Dudareva, Klempien, Muhlemann y Kaplan (2013). Biosynthesis, function and metabolic engineering of plant volatile organic compounds. New Phytologist, 198, 16–32.',url:'https://doi.org/10.1111/nph.12145',language:'Inglés · revisión científica',use:'Relacionar familias químicas, biosíntesis e interacciones ecológicas. Revisar acceso en la editorial.'},
 ebi:{title:'Introducción a la metabolómica',citation:'EMBL-EBI Training. Metabolomics: an introduction. Curso institucional en línea.',url:'https://www.ebi.ac.uk/training/online/courses/metabolomics-introduction/',language:'Inglés · acceso abierto',use:'Definir enfoques dirigidos y no dirigidos y ordenar el flujo de un estudio.'},
 design:{title:'Diseño experimental en estudios metabolómicos',citation:'EMBL-EBI Training. Design experiment.',url:'https://www.ebi.ac.uk/training/online/courses/metabolomics-introduction/designing-a-metabolomics-study/design-experiment/',language:'Inglés · acceso abierto',use:'Revisar aleatorización, tamaño muestral, conservación y factores de confusión.'},
 spme:{title:'Fundamento original de SPME',citation:'Arthur y Pawliszyn (1990). Solid phase microextraction with thermal desorption using fused silica optical fibers. Analytical Chemistry, 62, 2145–2148.',url:'https://doi.org/10.1021/ac00218a019',language:'Inglés · acceso según licencia editorial',use:'Estudiar el principio de extracción y desorción; contrastarlo con variantes actuales.'},
 insst:{title:'Captación de COV y análisis por DT-CG-EM',citation:'INSST (2013). NTP 978: Compuestos orgánicos volátiles: determinación por captación en tubos multilecho y análisis DT-CG-EM.',url:'https://www.insst.es/documentacion/colecciones-tecnicas/ntp-notas-tecnicas-de-prevencion/28-serie-ntp-numeros-961-a-995-ano-2013/nota-tecnica-de-prevencion-ntp-978',language:'Español · acceso abierto',use:'Ejemplo de muestreo ambiental, blancos y desorción térmica. Su alcance no cubre todas las matrices biológicas.'},
 arrow:{title:'SPME Arrow',citation:'Restek. PAL SPME Arrow: Set Your Sights on Superior Performance. Nota técnica del fabricante.',url:'https://discover.restek.com/articles/gnss2642/set-your-sights-on-superior-performance',language:'Inglés · documentación técnica',use:'Comparar geometría, recubrimiento y compatibilidad; distinguir evidencia de afirmaciones comerciales.'},
 sbse:{title:'Extracción por sorción en barra',citation:'GERSTEL. Twister / SBSE. Documentación de tecnología.',url:'https://www.gerstel.com/en/products/sample-preparation/extraction/Twister-SBSE',language:'Inglés · documentación técnica',use:'Reconocer el principio SBSE y sus requisitos de desorción.'},
 hisorb:{title:'Extracción sorptiva HiSorb',citation:'Markes International. HiSorb sorptive extraction.',url:'https://markes.com/sampling-technologies/hisorb-sorptive-extraction',language:'Inglés · documentación técnica',use:'Comparar muestreo en espacio de cabeza e inmersión y capacidad del sorbente.'},
 nist:{title:'Datos de retención cromatográfica',citation:'NIST. Chemistry WebBook, SRD 69: Gas Chromatographic Retention Data.',url:'https://webbook.nist.gov/chemistry/gc-ri/',language:'Inglés · consulta abierta',use:'Buscar índices y condiciones de separación; no confundir coincidencia con confirmación de identidad.'},
 amdis:{title:'Manual de AMDIS',citation:'NIST. AMDIS Manual: Automated Mass Spectral Deconvolution and Identification System.',url:'https://www.nist.gov/system/files/documents/srd/AMDISMan.pdf',language:'Inglés · manual abierto',use:'Estudiar detección de componentes, deconvolución y comparación espectral.'},
 msdial:{title:'MS-DIAL para proyectos GC-MS',citation:'Computational Metabolomics / RIKEN. MS-DIAL: documentación, tutoriales y datos de demostración.',url:'https://systemsomicslab.github.io/compms/msdial/main.html',language:'Inglés · documentación abierta',use:'Consultar el flujo GC-MS, índices, alineamiento y exportación de matrices.'},
 mzmine:{title:'Documentación de MZmine',citation:'MZmine Development Team. MZmine documentation.',url:'https://mzmine.github.io/mzmine_documentation/',language:'Inglés · documentación abierta',use:'Comparar flujos según adquisición; revisar compatibilidad GC-EI-MS antes de elegir módulos.'},
 gnps:{title:'Deconvolución y redes de datos GC-MS',citation:'Aksenov et al. (2021; publicación en línea 2020). Auto-deconvolution and molecular networking of gas chromatography–mass spectrometry data. Nature Biotechnology, 39, 169–173.',url:'https://www.nature.com/articles/s41587-020-0700-3',language:'Inglés · artículo científico',use:'Distinguir similitud espectral, anotación y redes bioquímicas.'},
 ptr:{title:'Fundamentos de PTR-MS',citation:'IONICON. PTR-MS: Knowledge Base. Documentación del fabricante.',url:'https://www.ionicon.com/knowledge-base/detail/ptr-ms',language:'Inglés · documentación técnica',use:'Contrastar medición directa por transferencia de protones con separación cromatográfica.'},
 qc:{title:'Buenas prácticas y reporte de metabolómica',citation:'Viant et al. (2019). Use cases, best practice and reporting standards for metabolomics in regulatory toxicology. Nature Communications, 10, 3041.',url:'https://www.nature.com/articles/s41467-019-10900-y',language:'Inglés · artículo de acceso abierto',use:'Revisar controles, trazabilidad y límites de interpretación en su contexto toxicológico.'},
 validation:{title:'Validación cruzada y separación de datos',citation:'scikit-learn developers. Cross-validation: evaluating estimator performance.',url:'https://scikit-learn.org/stable/modules/cross_validation.html',language:'Inglés · documentación abierta',use:'Diseñar validación sin mezclar sujetos ni filtrar información del conjunto de prueba.'},
 kegg:{title:'Mapas de rutas metabólicas',citation:'KEGG. KEGG PATHWAY database.',url:'https://www.kegg.jp/kegg/pathway.html',language:'Inglés · consulta; revisar condiciones de uso',use:'Seleccionar organismo e identificadores antes de interpretar rutas.'},
 python:{title:'Tutorial de Python',citation:'Python Software Foundation. El tutorial de Python.',url:'https://docs.python.org/es/3/tutorial/',language:'Español · documentación abierta',use:'Repasar variables, funciones, archivos y entornos antes del taller.'},
 pyteomics:{title:'Lectura de mzML en Python',citation:'Pyteomics developers. Data Access: mzML and mzXML.',url:'https://pyteomics.readthedocs.io/en/latest/data.html',language:'Inglés · documentación abierta',use:'Comprender espectros, matrices de intensidad y unidades de tiempo.'},
 pymassspec:{title:'Procesamiento GC-MS con PyMassSpec',citation:'PyMassSpec developers. User guide and examples.',url:'https://pymassspec.readthedocs.io/en/master/',language:'Inglés · documentación abierta',use:'Ampliar el taller con matrices de intensidad, detección y alineamiento GC-MS.'},
 gnpsdocs:{title:'GNPS y flujos GC-MS EI',citation:'GNPS / UC San Diego. Analyze, Connect, and Network with your Mass Spectrometry Data.',url:'https://gnps.ucsd.edu/ProteoSAFe/static/gnps-splash.jsp',language:'Inglés · portal y documentación',use:'Localizar el flujo específico GC-MS EI y los conjuntos públicos de datos.'},
 hisorbfood:{title:'Aplicación de extracción sorptiva a bebidas',citation:'Markes International. Application note 124: Flavour profiling of alcoholic spirits using HiSorb sorptive extraction and TD–GC–MS.',url:'https://markes.com/content-hub/application-notes/application-note-124',language:'Inglés · caso técnico del fabricante',use:'Ejercicio de crítica de método y matriz; no representa resultados de GICTA.'},
};
type TopicPlan={title:string;scope:string;refs:string[]};
type WeekPlan={id:string;title:string;modules:string;outcome:string;activity:string;topics:TopicPlan[]};
const t=(title:string,scope:string,refs:string[]):TopicPlan=>({title,scope,refs});
export const volatileWeeks:WeekPlan[]=[
 {id:'volatilomica-semana-1',title:'Ecología química y fundamentos del volatiloma',modules:'Módulos 1 y 2',outcome:'Explicar el papel de los VOCs y formular una pregunta volatilómica.',activity:'Construir un mapa de comunicación química con emisor, receptor, compuesto, contexto y evidencia; proponer una pregunta dirigida o no dirigida.',topics:[
 t('Historia y lenguaje químico de la naturaleza','Historia de la ecología química, comunicación mediante VOCs y relación con metabolómica. Distinguir una señal biológica de una emisión incidental.', ['ecology','ebi']),
 t('Semioquímicos y relaciones ecológicas','Feromonas, kairomonas, alomonas y sinomonas: clasificar por emisor, receptor y efecto. La función depende del contexto y requiere evidencia conductual o fisiológica.', ['ecology']),
 t('Interacciones planta-planta, planta-insecto y planta-microorganismo','Comparar defensa, atracción, estrés y asociaciones microbianas. Diseñar un control que permita separar origen vegetal, microbiano y ambiental.', ['ecology','design']),
 t('Volatiloma, VOCs y propiedades fisicoquímicas','Definir volatiloma; relacionar presión de vapor, partición y temperatura con lo que realmente se detecta. Diferenciar concentración en muestra, fase gaseosa y tasa de emisión.', ['ebi','insst']),
 t('Estudios dirigidos, no dirigidos y flujo de trabajo','De la pregunta al reporte: muestreo, extracción, adquisición, control de calidad, anotación e interpretación. Definir la unidad experimental y el producto esperado.', ['ebi','qc']),
 ]},
 {id:'volatilomica-semana-2',title:'Diseño experimental, muestreo y extracción',modules:'Módulos 3 y 4',outcome:'Justificar un protocolo de muestreo y una estrategia de extracción para una matriz.',activity:'Entregar protocolo con variables, conservación, aleatorización, blancos, QC y comparación de dos técnicas de extracción.',topics:[
 t('Diseño experimental, campo y muestreo in situ','Factores, réplicas biológicas y técnicas, aleatorización, metadatos y confusores. Especificar temperatura, humedad, flujo, materiales y conservación del volatiloma.', ['design','insst','qc']),
 t('Headspace estático, dinámico y purge and trap','Comparar equilibrio con extracción dinámica, caudal, tiempo y captura del analito. Evaluar pérdidas, contaminación y saturación del adsorbente.', ['insst','spme']),
 t('HS-SPME y SPME Arrow','Recubrimientos, equilibrio, cinética, competencia y desorción. Comparar la fibra con Arrow sin asumir equivalencia de recuperación o compatibilidad instrumental.', ['spme','arrow']),
 t('SBSE y HiSorb','Principios de extracción sorptiva por inmersión o espacio de cabeza y desorción. Seleccionar según matriz, volumen, afinidad y volatilidad.', ['sbse','hisorb']),
 t('QuEChERS y selección comparada de metodologías','Situar QuEChERS como preparación por partición y limpieza; discutir pérdidas de analitos muy volátiles. Comparar con métodos de espacio de cabeza y diseñar ensayos de recuperación antes de adoptarlo.', ['quechers','design','qc']),
 ]},
 {id:'volatilomica-semana-3',title:'GC-MS y plataformas complementarias',modules:'Módulo 5',outcome:'Interpretar la relación entre separación, espectro de masas y confianza de identificación.',activity:'Preparar una ficha instrumental y un dossier de un candidato con espectro, retención, blancos y limitaciones.',topics:[
 t('Cromatografía de gases y acoplamiento GC-MS','Inyección, columna, programa de temperatura, resolución y detector. Diferenciar TIC, EIC y espectro de masas; reconocer coelución y arrastre.', ['gc','amdis','nist']),
 t('Ionización, analizadores de masas y HRMS','Comparar ionización electrónica con otras adquisiciones, masa nominal y exacta, resolución y rango de adquisición. Una masa o fragmento aislado no identifica un compuesto.', ['gc','msdial','amdis']),
 t('GC×GC y separación bidimensional','Interpretar dos dimensiones de retención y modulación. Comparar la complejidad y los requisitos de procesamiento con un experimento GC-MS convencional.', ['gcxgc','msdial','qc']),
 t('PTR-MS, IMS y medición directa','Principios de transferencia de protones y movilidad iónica. Distinguir resolución temporal, separación y selectividad; considerar humedad e interferencias.', ['ptr','qc']),
 t('Bibliotecas espectrales e índices de retención','Coincidencia EI, índices calculados con una serie de referencia y comparación de fase estacionaria. Diferenciar anotación tentativa de confirmación con estándar auténtico.', ['nist','amdis','msdial']),
 ]},
 {id:'volatilomica-semana-4',title:'Procesamiento e identificación de señales',modules:'Módulo 6',outcome:'Documentar la transformación de archivos instrumentales en una matriz de características.',activity:'Comparar dos ajustes de procesamiento y entregar parámetros, matriz, tabla de anotaciones y reporte de calidad.',topics:[
 t('Archivos, metadatos y control de calidad inicial','Conservar originales; revisar conversión, unidades, TIC, blancos y QC. Registrar instrumento, adquisición y versión del software antes de filtrar o corregir señales.', ['pyteomics','qc']),
 t('AMDIS: componentes y deconvolución','Separar componentes coeluyentes mediante información espectral. Evaluar umbrales, iones y espectros recuperados; distinguir detección de identificación.', ['amdis','nist']),
 t('MS-DIAL y MZmine: alineamiento y matrices','Elegir el flujo compatible con GC-EI-MS, revisar alineamiento, tolerancias y faltantes. Conservar parámetros y distinguir picos de compuestos anotados.', ['msdial','mzmine']),
 t('SIRIUS y anotación computacional: alcance y límites','Examinar qué tipo de espectros y adquisiciones admite cada herramienta. SIRIUS y métodos orientados a MS/MS no sustituyen automáticamente una búsqueda de espectros EI de GC-MS.', ['sirius','msdial','gnps','nist']),
 t('GNPS y redes de espectros GC-MS','Comparar deconvolución, búsqueda de bibliotecas EI y agrupación por similitud. No interpretar una arista espectral como una reacción bioquímica.', ['gnps','gnpsdocs']),
 ]},
 {id:'volatilomica-semana-5',title:'Quimiometría y significado biológico',modules:'Módulos 7 y 8',outcome:'Interpretar patrones y rutas sin confundir separación estadística con validación biológica.',activity:'Entregar figuras exploratorias, estrategia de validación y mapa de una hipótesis biológica con evidencia y limitaciones.',topics:[
 t('Preparación de matrices, PCA y mapas de calor','Revisar faltantes, blancos, QC, transformación y escalado. Leer scores y loadings; describir patrones sin presentar PCA como un clasificador validado.', ['validation','qc']),
 t('PLS-DA, OPLS y validación de modelos','Separar entrenamiento y prueba por unidad independiente; ajustar preprocesamiento dentro de cada partición. Considerar sobreajuste, permutaciones y validación externa.', ['validation']),
 t('Volcano plots y candidatos a biomarcadores','Combinar tamaño de efecto, incertidumbre y corrección por comparaciones múltiples. Diferenciar asociación, capacidad predictiva y causalidad.', ['qc','validation']),
 t('KEGG, MetaCyc e interpretación de rutas','Mapear identificadores y seleccionar organismo antes del enriquecimiento. Registrar cobertura, universo medido y ambigüedades; no convertir una lista de VOCs en afirmaciones de flujo.', ['kegg','metacyc','ecology','qc']),
 t('GNPS, Cytoscape y Gephi: lectura de redes','Distinguir redes espectrales, de correlación y de reacciones. Definir nodos, aristas, pesos y criterios de filtrado antes de utilizar una visualización.', ['gnps','gephi','cytoscape','kegg']),
 ]},
 {id:'volatilomica-semana-6',title:'Aplicaciones, proyecto y perspectivas',modules:'Módulos 9 y 10',outcome:'Defender un caso de aplicación y un plan reproducible de análisis.',activity:'Presentar un caso crítico y una carpeta reproducible. Incorporar el artículo GICTA asignado por el docente cuando esté disponible.',topics:[
 t('Frutas, café y calidad de alimentos','Comparar perfiles en café, tomate de árbol, feijoa y aguacate Hass. Relacionar maduración, procesamiento y matriz; discutir diferencia entre abundancia instrumental y contribución sensorial.', ['hisorbfood','spme','qc']),
 t('Hongos, plantas y Araceae','Comparar emisiones y posibles funciones en hongos, plantas ornamentales y Araceae. Separar respuestas a estrés de efectos de microbiota, cultivo y manipulación.', ['ecology','design']),
 t('Ambiente, salud y xenometabolómica','Contaminantes y compuestos exógenos: estudiar exposición, origen de muestra y confusores. Delimitar el alcance de posibles biomarcadores y su validación.', ['insst','qc']),
 t('IA, e-nose, e-tongue y volatilómica emergente','Comparar sensores y perfiles químicos; distinguir e-tongue en fase líquida de medición de VOCs. Examinar aprendizaje automático, spatial volatilomics y dark metabolomics como líneas que requieren validación.', ['sensors','validation','ptr','gnps']),
 t('Agricultura digital y defensa del proyecto GICTA','Evaluar utilidad en agricultura de precisión y reproducibilidad. Espacio para artículos, datos y experiencias del Grupo GICTA suministrados por el docente; no atribuirles estudios externos.', ['ecology','qc','python']),
 ]},
];
export const topicId=(week:string,index:number)=>`${week}-tema-${index+1}`;
export function readingText(ids:string[]){return [...new Set(ids)].map(id=>{const r=volatileReadings[id];return `${r.citation}\n${r.language}. Para trabajar: ${r.use}\n${r.url}`}).join('\n\n')}
export const volatilomicsContent:Item[]=volatileWeeks.flatMap((w,n)=>[
 {id:w.id,kind:'unit',parent:volatileCourseId,title:`Semana ${n+1} · ${w.title}`,status:'published',position:n,description:`${w.modules} de la propuesta BIOPGR / GICTA.`,objectives:w.outcome,body:w.activity,bibliography:readingText(w.topics.flatMap(t=>t.refs)),volatileWeek:n+1},
 ...w.topics.map((t,i)=>({id:topicId(w.id,i),kind:'topic',parent:w.id,title:t.title,status:'published',position:i,description:t.scope,body:`Alcance del tema\n\n${t.scope}\n\nTrabajo de la semana\n\n${w.outcome} Registra qué decisiones dependen de la matriz y cuáles requieren evidencia adicional. Contrasta tus argumentos con las fuentes indicadas; no extrapoles resultados entre matrices sin justificación.`,objectives:w.outcome,examples:`Discusión guiada\n\nSelecciona un caso relacionado con ${t.title.toLowerCase()}. Identifica la pregunta, el tipo de muestra, el método utilizado y una limitación. Explica qué control o dato adicional permitiría evaluar tu interpretación.`,activities:`Actividad de la semana\n\n${w.activity}\n\nPara este tema: prepara una ficha de lectura con objetivo, método, resultado principal y limitación de una referencia. Las presentaciones, videos, modelos y archivos del docente se incorporan en el espacio de este tema.`,bibliography:readingText(t.refs),volatileWeek:n+1})),
]);
volatilomicsContent.push({id:volatileLabId,kind:'topic',parent:volatileCourseId,title:'Taller final · Procesamiento de datos GC-MS con Python',status:'published',position:99,description:'De mzML y cromatogramas a controles, integración dirigida y análisis exploratorio reproducible.',body:'Trabaja en Python con una copia de los datos y conserva los archivos originales. Verifica el tipo de adquisición, las unidades de retención y los metadatos antes de extraer TIC y EIC. Revisa blancos y QC, documenta las regiones de integración y conserva parámetros y versiones. El taller diferencia el procesamiento dirigido de una deconvolución no dirigida.',examples:'Compara el cromatograma de una muestra y un blanco con la misma ventana de m/z. Una señal en ambos exige revisar contaminación antes de proponer una interpretación biológica.',activities:'Entregar cromatogramas, parámetros, áreas revisadas, matriz y un informe de limitaciones. Ejecutar los scripts en un entorno Python propio; la web ofrece la guía y las descargas.',bibliography:readingText(['python','pyteomics','pymassspec','amdis','msdial','validation'])});
